import { createHash, randomUUID } from "node:crypto";
import type { ExternalPrincipal } from "../auth/externalPrincipal";
import { hasActivePaymentAccess } from "../allowlist/allowlistEntry";
import { AccountAccessDeniedError, AccountProvisioningService } from "../identity/accountProvisioningService";
import type { PaymentPersistence } from "../storage/storageContracts";
import type { ExecutionRepository } from "./executionRepository";
import { toPublicExecution } from "./executionTypes";
import { toPublicReceipt } from "./executionReceiptTypes";

export class ExecutionApplicationError extends Error { constructor(readonly kind:"ACCESS_DENIED"|"NOT_FOUND"|"CONFLICT"|"INVALID",message:string){super(message);this.name="ExecutionApplicationError";} }
export class PaymentExecutionService {
  constructor(private accounts:AccountProvisioningService,private payments:PaymentPersistence,private executions:ExecutionRepository,private clock=()=>new Date().toISOString(),private id=()=>randomUUID()){}
  async execute(principal:ExternalPrincipal,paymentIntentId:string,body:unknown){if(!body||typeof body!=="object"||Array.isArray(body)||Object.keys(body as object).some(k=>!["requestHash","expectedVersion"].includes(k)))throw new ExecutionApplicationError("INVALID","Execute request contains unsupported fields.");const actor=await this.actor(principal);const allow=await this.payments.findAllowlistEntry(actor.actorSubject);if(!hasActivePaymentAccess(allow,this.clock()))throw new ExecutionApplicationError("ACCESS_DENIED","Beta payment access is unavailable.");const payment=await this.payments.findPayment(paymentIntentId);if(!payment||payment.actorSubject!==actor.actorSubject)throw new ExecutionApplicationError("NOT_FOUND","Payment intent was not found.");if(payment.status!=="PROCESSING"||!payment.userConfirmedAt)throw new ExecutionApplicationError("CONFLICT","Payment intent is not confirmed for execution.");const b=body as any;if(b.requestHash!==payment.requestHash||String(b.expectedVersion)!==payment.version.toString())throw new ExecutionApplicationError("CONFLICT","Payment intent confirmation is stale or mismatched.");const executionId=this.id();const providerKey=createHash("sha256").update(`zephipay-execution-v1:${payment.id}`).digest("hex");const result=await this.executions.createOrGet({executionId,paymentIntentId:payment.id,actorSubject:actor.actorSubject,providerIdempotencyKey:providerKey,now:this.clock()});return{execution:toPublicExecution(result.execution),created:result.created};}
  async find(principal:ExternalPrincipal,paymentIntentId:string){const actor=await this.actor(principal);const payment=await this.payments.findPayment(paymentIntentId);if(!payment||payment.actorSubject!==actor.actorSubject)throw new ExecutionApplicationError("NOT_FOUND","Payment intent was not found.");const execution=await this.executions.findByPaymentIntent(paymentIntentId);if(!execution)throw new ExecutionApplicationError("NOT_FOUND","Payment execution was not found.");const receipt=await this.executions.findReceiptByPaymentIntent(paymentIntentId);return toPublicExecution(execution,receipt?.receiptId);}
  async receipt(principal:ExternalPrincipal,paymentIntentId:string){const actor=await this.actor(principal);const payment=await this.payments.findPayment(paymentIntentId);if(!payment||payment.actorSubject!==actor.actorSubject)throw new ExecutionApplicationError("NOT_FOUND","Payment receipt was not found.");const receipt=await this.executions.findReceiptByPaymentIntent(paymentIntentId);if(!receipt||receipt.actorSubject!==actor.actorSubject)throw new ExecutionApplicationError("NOT_FOUND","Payment receipt was not found.");return toPublicReceipt(receipt);}
  async activity(principal:ExternalPrincipal,limit:number){const actor=await this.actor(principal);const payments=await this.payments.listPaymentsByActor(actor.actorSubject,limit);return Promise.all(payments.map(async payment=>{const execution=await this.executions.findByPaymentIntent(payment.id);const receipt=await this.executions.findReceiptByPaymentIntent(payment.id);const status=!execution?payment.userConfirmedAt?"ready":"awaiting_confirmation":execution.status==="SETTLED"?"completed":execution.status==="UNKNOWN"?"pending":execution.status==="FAILED"?"failed":execution.status==="CANCELLED"?"cancelled":execution.status==="READY"?"ready":"processing";return Object.freeze({paymentIntentId:payment.id,...(execution?{executionId:execution.executionId}:{}),...(receipt?{receiptId:receipt.receiptId}:{}),status,recipient:payment.recipientSnapshot?{type:"payment_identity",displayName:payment.recipientSnapshot.displayName,username:payment.recipientSnapshot.username,verificationState:payment.recipientSnapshot.verificationState.toLowerCase(),trustOutcome:payment.recipientSnapshot.trustOutcome.toLowerCase()}:{type:"direct_wallet",displayName:"Wallet recipient"},amountRaw:payment.amountRaw.toString(),amount:formatAmount(payment.amountRaw.toString(),6),asset:payment.asset,memo:payment.purpose,createdAt:payment.createdAt,...(execution?.settledAt?{settledAt:execution.settledAt}:{}),receiptAvailable:receipt!==undefined});}));}
  private async actor(p:ExternalPrincipal){try{return(await this.accounts.resolve(p)).account;}catch(e){if(e instanceof AccountAccessDeniedError)throw new ExecutionApplicationError("ACCESS_DENIED","Payment access is unavailable.");throw e;}}
}
function formatAmount(units:string,decimals:number){const padded=units.padStart(decimals+1,"0");const whole=padded.slice(0,-decimals)||"0";const fraction=padded.slice(-decimals).replace(/0+$/,"");return fraction?`${whole}.${fraction}`:whole;}
