import { createHash, randomUUID } from "node:crypto";
import type { ExternalPrincipal } from "../auth/externalPrincipal";
import { hasActivePaymentAccess } from "../allowlist/allowlistEntry";
import { AccountAccessDeniedError, AccountProvisioningService } from "../identity/accountProvisioningService";
import type { PaymentPersistence } from "../storage/storageContracts";
import type { ExecutionRepository } from "./executionRepository";
import { toPublicExecution } from "./executionTypes";
import { toPublicReceipt } from "./executionReceiptTypes";
import type { ActivityFact, ActivityRepository } from "./activityRepository";

export class ExecutionApplicationError extends Error { constructor(readonly kind:"ACCESS_DENIED"|"NOT_FOUND"|"CONFLICT"|"INVALID",message:string){super(message);this.name="ExecutionApplicationError";} }
export class PaymentExecutionService {
  constructor(private accounts:AccountProvisioningService,private payments:PaymentPersistence,private executions:ExecutionRepository,private clock=()=>new Date().toISOString(),private id=()=>randomUUID(),private activityRepository?:ActivityRepository){}
  async execute(principal:ExternalPrincipal,paymentIntentId:string,body:unknown){if(!body||typeof body!=="object"||Array.isArray(body)||Object.keys(body as object).some(k=>!["requestHash","expectedVersion"].includes(k)))throw new ExecutionApplicationError("INVALID","Execute request contains unsupported fields.");const actor=await this.actor(principal);const allow=await this.payments.findAllowlistEntry(actor.actorSubject);if(!hasActivePaymentAccess(allow,this.clock()))throw new ExecutionApplicationError("ACCESS_DENIED","Beta payment access is unavailable.");const payment=await this.payments.findPayment(paymentIntentId);if(!payment||payment.actorSubject!==actor.actorSubject)throw new ExecutionApplicationError("NOT_FOUND","Payment intent was not found.");if(payment.status!=="PROCESSING"||!payment.userConfirmedAt)throw new ExecutionApplicationError("CONFLICT","Payment intent is not confirmed for execution.");const b=body as any;if(b.requestHash!==payment.requestHash||String(b.expectedVersion)!==payment.version.toString())throw new ExecutionApplicationError("CONFLICT","Payment intent confirmation is stale or mismatched.");const executionId=this.id();const providerKey=createHash("sha256").update(`zephipay-execution-v1:${payment.id}`).digest("hex");const result=await this.executions.createOrGet({executionId,paymentIntentId:payment.id,actorSubject:actor.actorSubject,providerIdempotencyKey:providerKey,now:this.clock()});return{execution:toPublicExecution(result.execution),created:result.created};}
  async find(principal:ExternalPrincipal,paymentIntentId:string){const actor=await this.actor(principal);const payment=await this.payments.findPayment(paymentIntentId);if(!payment||payment.actorSubject!==actor.actorSubject)throw new ExecutionApplicationError("NOT_FOUND","Payment intent was not found.");const execution=await this.executions.findByPaymentIntent(paymentIntentId);if(!execution)throw new ExecutionApplicationError("NOT_FOUND","Payment execution was not found.");const receipt=await this.executions.findReceiptByPaymentIntent(paymentIntentId);return toPublicExecution(execution,receipt?.receiptId);}
  async receipt(principal:ExternalPrincipal,paymentIntentId:string){const actor=await this.actor(principal);const payment=await this.payments.findPayment(paymentIntentId);if(!payment||payment.actorSubject!==actor.actorSubject)throw new ExecutionApplicationError("NOT_FOUND","Payment receipt was not found.");const receipt=await this.executions.findReceiptByPaymentIntent(paymentIntentId);if(!receipt||receipt.actorSubject!==actor.actorSubject)throw new ExecutionApplicationError("NOT_FOUND","Payment receipt was not found.");return toPublicReceipt(receipt);}
  async activity(principal:ExternalPrincipal,limit:number){const actor=await this.actor(principal);if(this.activityRepository)return (await this.activityRepository.listByActor(actor.actorSubject,limit)).map(projectActivity);const payments=await this.payments.listPaymentsByActor(actor.actorSubject,limit);return Promise.all(payments.map(async payment=>{const execution=await this.executions.findByPaymentIntent(payment.id);const receipt=await this.executions.findReceiptByPaymentIntent(payment.id);return projectActivity({paymentIntentId:payment.id,userConfirmedAt:payment.userConfirmedAt,recipientSnapshot:payment.recipientSnapshot,amountUnits:payment.amountRaw.toString(),asset:payment.asset,memo:payment.purpose,createdAt:payment.createdAt,executionId:execution?.executionId,executionStatus:execution?.status,settledAt:execution?.settledAt,receiptId:receipt?.receiptId});}));}
  private async actor(p:ExternalPrincipal){try{return(await this.accounts.resolve(p)).account;}catch(e){if(e instanceof AccountAccessDeniedError)throw new ExecutionApplicationError("ACCESS_DENIED","Payment access is unavailable.");throw e;}}
}
function projectActivity(fact:ActivityFact){const status=!fact.executionStatus?fact.userConfirmedAt?"ready":"awaiting_confirmation":fact.executionStatus==="SETTLED"?"completed":fact.executionStatus==="UNKNOWN"?"pending":fact.executionStatus==="FAILED"?"failed":fact.executionStatus==="CANCELLED"?"cancelled":fact.executionStatus==="READY"?"ready":"processing";return Object.freeze({paymentIntentId:fact.paymentIntentId,...(fact.executionId?{executionId:fact.executionId}:{}),...(fact.receiptId?{receiptId:fact.receiptId}:{}),status,recipient:fact.recipientSnapshot?{type:"payment_identity",displayName:fact.recipientSnapshot.displayName,username:fact.recipientSnapshot.username,verificationState:fact.recipientSnapshot.verificationState.toLowerCase(),trustOutcome:fact.recipientSnapshot.trustOutcome.toLowerCase()}:{type:"direct_wallet",displayName:"Wallet recipient"},amountRaw:fact.amountUnits,amount:formatAmount(fact.amountUnits,6),asset:fact.asset,memo:fact.memo,createdAt:fact.createdAt,...(fact.settledAt?{settledAt:fact.settledAt}:{}),receiptAvailable:fact.receiptId!==undefined});}
function formatAmount(units:string,decimals:number){const padded=units.padStart(decimals+1,"0");const whole=padded.slice(0,-decimals)||"0";const fraction=padded.slice(-decimals).replace(/0+$/,"");return fraction?`${whole}.${fraction}`:whole;}
