import{Router,type RequestHandler,type Response}from"express";import{externalPrincipalFrom}from"../auth/authMiddleware";import{PaymentRequestApplicationError,PaymentRequestService}from"../paymentRequests/paymentRequestService";import{parseIdempotencyKey,parsePaymentRequestCreate,parsePaymentRequestId,parsePaymentRequestTransition,PaymentRequestInputError}from"../paymentRequests/paymentRequestValidation";
export function createPaymentRequestsRouter(i:{service:PaymentRequestService;readAuth:readonly RequestHandler[];writeAuth:readonly RequestHandler[];rateLimiter?:RequestHandler}){const r=Router();r.use((_q,s,n)=>{s.set("Cache-Control","no-store, private");s.set("Pragma","no-cache");n()});if(i.rateLimiter)r.use(i.rateLimiter);
 r.post("/",...i.writeAuth,async(q,s)=>{try{const result=await i.service.create(externalPrincipalFrom(s),{...parsePaymentRequestCreate(q.body),idempotencyKey:parseIdempotencyKey(q.header("idempotency-key"))});return s.status(result.created?201:200).json({ok:true,...result,requestId:s.locals.requestId})}catch(e){return handle(e,s)}});
 r.get("/",...i.readAuth,async(q,s)=>{try{const limit=q.query.limit===undefined?20:Number(q.query.limit);return s.json({ok:true,items:await i.service.list(externalPrincipalFrom(s),limit),requestId:s.locals.requestId})}catch(e){return handle(e,s)}});
 r.get("/:id",...i.readAuth,async(q,s)=>{try{return s.json({ok:true,paymentRequest:await i.service.find(externalPrincipalFrom(s),parsePaymentRequestId(q.params.id)),requestId:s.locals.requestId})}catch(e){return handle(e,s)}});
 r.post("/:id/accept",...i.writeAuth,async(q,s)=>{try{return s.json({ok:true,...await i.service.accept(externalPrincipalFrom(s),parsePaymentRequestId(q.params.id),parsePaymentRequestTransition(q.body,true)),requestId:s.locals.requestId})}catch(e){return handle(e,s)}});
 r.post("/:id/decline",...i.writeAuth,async(q,s)=>{try{const b=parsePaymentRequestTransition(q.body);return s.json({ok:true,...await i.service.decline(externalPrincipalFrom(s),parsePaymentRequestId(q.params.id),b.expectedVersion),requestId:s.locals.requestId})}catch(e){return handle(e,s)}});
 r.post("/:id/cancel",...i.writeAuth,async(q,s)=>{try{const b=parsePaymentRequestTransition(q.body);return s.json({ok:true,...await i.service.cancel(externalPrincipalFrom(s),parsePaymentRequestId(q.params.id),b.expectedVersion),requestId:s.locals.requestId})}catch(e){return handle(e,s)}});return r}
function handle(e:unknown,s:Response){if(e instanceof PaymentRequestInputError)return s.status(400).json({ok:false,error:e.message,requestId:s.locals.requestId});if(e instanceof PaymentRequestApplicationError)return s.status(e.kind==="INVALID"?400:e.kind==="ACCESS_DENIED"?403:e.kind==="NOT_FOUND"?404:409).json({ok:false,error:e.message,requestId:s.locals.requestId});throw e}
