import type {CreatePaymentRequestRecord,PaymentRequestClaim,PaymentRequestRecord,PaymentRequestRepository} from "../../paymentRequests/paymentRequestTypes";
import {PaymentRequestVersionConflictError} from "../../paymentRequests/paymentRequestTypes";

export class InMemoryPaymentRequestRepository implements PaymentRequestRepository{
 private requests=new Map<string,PaymentRequestRecord>();private keys=new Map<string,string>();
 async claim(input:CreatePaymentRequestRecord):Promise<PaymentRequestClaim>{const key=`${input.requesterActorSubject}\0${input.idempotencyKey}`,priorId=this.keys.get(key),prior=priorId?this.requests.get(priorId):undefined;if(prior)return{outcome:prior.requestHash===input.requestHash?"EXISTING":"HASH_CONFLICT",request:prior};const{occurredAt,...record}=input;const request=Object.freeze({...record,status:"PENDING" as const,version:0n,createdAt:occurredAt,updatedAt:occurredAt});this.requests.set(request.requestId,request);this.keys.set(key,request.requestId);return{outcome:"CLAIMED",request}}
 async findByIdempotencyKey(requesterActorSubject:string,idempotencyKey:string){const id=this.keys.get(`${requesterActorSubject}\0${idempotencyKey}`);return id?this.requests.get(id):undefined}
 async find(id:string){return this.requests.get(id)}
 async listVisible(accountId:string,limit:number){return[...this.requests.values()].filter(r=>r.requesterAccountId===accountId||r.payerAccountId===accountId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||b.requestId.localeCompare(a.requestId)).slice(0,limit)}
 async transition(input:Parameters<PaymentRequestRepository["transition"]>[0]){const current=this.requests.get(input.requestId);if(!current)throw new Error("NOT_FOUND");if(current.version!==input.expectedVersion)throw new PaymentRequestVersionConflictError();if(current.status!=="PENDING")throw new Error("ILLEGAL_TRANSITION");if(input.toStatus==="CANCELLED"?current.requesterAccountId!==input.actorAccountId:current.payerAccountId!==input.actorAccountId)throw new Error("NOT_FOUND");if(input.toStatus==="ACCEPTED"&&!input.linkedPaymentIntentId)throw new Error("LINK_REQUIRED");const updated=Object.freeze({...current,status:input.toStatus,version:current.version+1n,updatedAt:input.occurredAt,...(input.toStatus==="ACCEPTED"?{acceptedAt:input.occurredAt,linkedPaymentIntentId:input.linkedPaymentIntentId}:input.toStatus==="DECLINED"?{declinedAt:input.occurredAt}:{cancelledAt:input.occurredAt})});this.requests.set(updated.requestId,updated);return updated}
 async markPaidByPaymentIntent(input:Parameters<PaymentRequestRepository["markPaidByPaymentIntent"]>[0]){const current=[...this.requests.values()].find(r=>r.linkedPaymentIntentId===input.paymentIntentId);if(!current)return;if(current.status==="PAID")return current;if(current.status!=="ACCEPTED")throw new Error("ILLEGAL_TRANSITION");const updated=Object.freeze({...current,status:"PAID" as const,version:current.version+1n,paidAt:input.paidAt,updatedAt:input.paidAt,linkedExecutionId:input.executionId,linkedReceiptId:input.receiptId});this.requests.set(updated.requestId,updated);return updated}
}
