import type{Pool,PoolClient}from"pg";
import type{DevnetRecoveryCandidate,DevnetRecoveryRepository,DevnetRecoveryTaskKind}from"../../devnet/devnetRecoveryRepository";
import type{PostgresDevnetExecutionStateRepository}from"./postgresDevnetExecutionStateRepository";
import{observeTransaction,runWithReliabilityContext}from"../../observability/reliabilityObservability";

export class PostgresDevnetRecoveryRepository implements DevnetRecoveryRepository{
  constructor(private readonly pool:Pool,private readonly states:PostgresDevnetExecutionStateRepository){}
  claimPreparation(workerId:string,now:string,leaseExpiresAt:string,currentBlockHeight:string){if(!/^(0|[1-9]\d*)$/.test(currentBlockHeight))return Promise.reject(new Error("Current Devnet block height is invalid."));return this.claim("PREPARATION",workerId,now,leaseExpiresAt,currentBlockHeight);}
  claimReconciliation(workerId:string,now:string,leaseExpiresAt:string){return this.claim("RECONCILIATION",workerId,now,leaseExpiresAt);}
  claimReconciliationExecution(executionId:string,workerId:string,now:string,leaseExpiresAt:string){return this.claim("RECONCILIATION",workerId,now,leaseExpiresAt,undefined,executionId);}
  async renew(executionId:string,taskKind:DevnetRecoveryTaskKind,workerId:string,claimedAt:string,_now:string,leaseExpiresAt:string){const result=await this.pool.query("UPDATE devnet_recovery_leases SET lease_expires_at=$5 WHERE execution_id=$1 AND task_kind=$2 AND lease_owner=$3 AND claimed_at=$4 AND lease_expires_at>clock_timestamp() AND $5::timestamptz>clock_timestamp() RETURNING execution_id",[executionId,taskKind,workerId,claimedAt,leaseExpiresAt]);return result.rowCount===1;}
  async inspectUnresolvedBacklog(now:string){const result=await runWithReliabilityContext({dbOperation:"EXECUTION_READ"},()=>this.pool.query(`SELECT count(*)::int AS unresolved_count,min(c.committed_at) AS oldest_committed_at FROM payment_executions e JOIN devnet_submission_commitments c ON c.execution_id=e.execution_id WHERE e.execution_mode='devnet_validation' AND e.selected_rail='solana' AND e.settlement_network='solana-devnet' AND e.status NOT IN ('SETTLED','FAILED','CANCELLED')`));const row=result.rows[0],oldest=row.oldest_committed_at?new Date(row.oldest_committed_at).toISOString():undefined;return Object.freeze({unresolvedCount:Number(row.unresolved_count),...(oldest?{oldestCommittedAt:oldest,oldestUnresolvedAgeMs:Math.max(0,Date.parse(now)-Date.parse(oldest))}:{})});}
  async release(executionId:string,taskKind:DevnetRecoveryTaskKind,workerId:string,claimedAt:string){await this.pool.query("DELETE FROM devnet_recovery_leases WHERE execution_id=$1 AND task_kind=$2 AND lease_owner=$3 AND claimed_at=$4",[executionId,taskKind,workerId,claimedAt]);}
  private claim(kind:DevnetRecoveryTaskKind,workerId:string,now:string,leaseExpiresAt:string,currentBlockHeight?:string,executionId?:string){return runWithReliabilityContext({dbOperation:"EXECUTION_CLAIM"},()=>this.tx(async client=>{if(!workerId||workerId.trim()!==workerId)throw new Error("Devnet recovery worker ID is invalid.");const query=kind==="PREPARATION"?PREPARATION_CLAIM:executionId===undefined?RECONCILIATION_CLAIM:RECONCILIATION_EXECUTION_CLAIM,parameters=kind==="PREPARATION"?[kind,now,workerId,leaseExpiresAt,currentBlockHeight]:executionId===undefined?[kind,now,workerId,leaseExpiresAt]:[kind,now,workerId,leaseExpiresAt,executionId];const result=await client.query(query,parameters);const row=result.rows[0];if(!row)return undefined;const base={executionId:String(row.execution_id),paymentIntentId:String(row.payment_intent_id),actorSubject:String(row.actor_subject),providerIdempotencyKey:String(row.provider_idempotency_key),recoveryLease:Object.freeze({taskKind:kind,leaseOwner:workerId,claimedAt:now,leaseExpiresAt})};return base;})).then(async(value)=>{if(!value)return undefined;const preparation=await this.states.findPreparation(value.executionId,value.actorSubject);return Object.freeze({...value,...(preparation?{preparation}:{})})as DevnetRecoveryCandidate;});}
  private async tx<T>(fn:(client:PoolClient)=>Promise<T>){const client=await this.pool.connect();try{return await observeTransaction(this.pool,async()=>{try{await client.query("BEGIN");const value=await fn(client);await client.query("COMMIT");return value;}catch(error){await client.query("ROLLBACK");throw error;}});}finally{client.release();}}
}
const BASE=`WITH candidate AS (SELECT e.execution_id,e.payment_intent_id,e.actor_subject,e.provider_idempotency_key FROM payment_executions e LEFT JOIN devnet_execution_preparations p ON p.execution_id=e.execution_id AND p.lifecycle_state<>'ABANDONED_PRE_CONTACT' LEFT JOIN devnet_recovery_leases l ON l.execution_id=e.execution_id AND l.task_kind=$1 WHERE e.execution_mode='devnet_validation' AND e.selected_rail='solana' AND e.settlement_network='solana-devnet' AND e.status NOT IN ('SETTLED','FAILED','CANCELLED') AND (l.execution_id IS NULL OR l.lease_expires_at<=$2)`;
const END=` ORDER BY e.created_at,e.execution_id FOR UPDATE OF e SKIP LOCKED LIMIT 1), leased AS (INSERT INTO devnet_recovery_leases(execution_id,task_kind,lease_owner,claimed_at,lease_expires_at) SELECT execution_id,$1,$3,$2,$4 FROM candidate ON CONFLICT(execution_id,task_kind) DO UPDATE SET lease_owner=EXCLUDED.lease_owner,claimed_at=EXCLUDED.claimed_at,lease_expires_at=EXCLUDED.lease_expires_at WHERE devnet_recovery_leases.lease_expires_at<=EXCLUDED.claimed_at RETURNING execution_id) SELECT candidate.* FROM candidate JOIN leased USING(execution_id)`;
const PREPARATION_CLAIM=`${BASE} AND (p.preparation_id IS NULL OR (p.lifecycle_state='PREPARED_NOT_CONTACTED' AND p.last_valid_block_height<$5::numeric))${END}`;
const RECONCILIATION_CLAIM=`${BASE} AND p.lifecycle_state IN ('SUBMISSION_COMMITTED_RECONCILE_ONLY','ACCEPTED_PENDING','UNKNOWN_RECONCILIATION_REQUIRED','SETTLED','FAILED') AND EXISTS(SELECT 1 FROM devnet_submission_commitments c WHERE c.execution_id=e.execution_id AND c.preparation_id=p.preparation_id)${END}`;
const RECONCILIATION_EXECUTION_CLAIM=`${BASE} AND p.lifecycle_state IN ('SUBMISSION_COMMITTED_RECONCILE_ONLY','ACCEPTED_PENDING','UNKNOWN_RECONCILIATION_REQUIRED','SETTLED','FAILED') AND EXISTS(SELECT 1 FROM devnet_submission_commitments c WHERE c.execution_id=e.execution_id AND c.preparation_id=p.preparation_id) AND e.execution_id=$5${END}`;
