import { CIRCLE_SOLANA_DEVNET_USDC_DECIMALS, CIRCLE_SOLANA_DEVNET_USDC_MINT } from "../../devnet/canonicalDevnetAsset";
import { devnetPreparationPolicy, hashDevnetPolicy } from "../../devnet/devnetPreparationPolicy";
import type{Pool,PoolClient}from"pg";import type{BrowserDevnetAggregate,BrowserDevnetExecutionStore}from"../../devnet/browserDevnetExecution";import type{PersistedDevnetPreparation}from"../../devnet/devnetExecutionState";
export class PostgresBrowserDevnetExecutionStore implements BrowserDevnetExecutionStore{constructor(private pool:Pool){}
 async createOrGet(input:Parameters<BrowserDevnetExecutionStore["createOrGet"]>[0]){return this.tx(async client=>{const inserted=await client.query(`INSERT INTO payment_executions(execution_id,payment_intent_id,actor_subject,status,selected_rail,execution_mode,settlement_network,policy_hash,provider_idempotency_key,created_at,updated_at) VALUES($1,$2,$3,'READY','solana','devnet_validation','solana-devnet',decode($4,'hex'),$5,$6,$6) ON CONFLICT(payment_intent_id) DO NOTHING RETURNING execution_id`,[input.executionId,input.paymentIntentId,input.actorSubject,input.policyHash,input.providerIdempotencyKey,input.now]);const row=await this.load(client,input.paymentIntentId,input.actorSubject,true);if(!row)throw new Error("Devnet execution ownership mismatch.");if(row.execution_mode!=="devnet_validation"||row.selected_rail!=="solana"||row.settlement_network!=="solana-devnet"||Buffer.from(row.policy_hash).toString("hex")!==input.policyHash||row.provider_idempotency_key!==input.providerIdempotencyKey)throw new Error("Payment intent already has an incompatible execution.");if(inserted.rows[0])await client.query("INSERT INTO payment_execution_events(execution_id,sequence_number,event_type,to_status,occurred_at) VALUES($1,1,'execution_created','READY',$2) ON CONFLICT DO NOTHING",[row.execution_id,input.now]);return{aggregate:map(row),created:Boolean(inserted.rows[0])};});}
 async find(paymentIntentId:string,actorSubject:string){const result=await this.pool.query(`${SELECT} WHERE e.payment_intent_id=$1 AND e.actor_subject=$2`,[paymentIntentId,actorSubject]);return result.rows[0]?map(result.rows[0]):undefined;}
 async applyLifecycle(input:Readonly<{aggregate:BrowserDevnetAggregate;preparation:PersistedDevnetPreparation;signature?:string;observedAt:string;slot?:string;confirmationStatus?:string;failureCode?:string}>){return this.tx(async client=>{const found=await this.load(client,input.aggregate.paymentIntentId,input.aggregate.actorSubject,true);if(!found||String(found.execution_id)!==input.aggregate.executionId)throw new Error("Devnet execution ownership mismatch.");const payment=(await client.query("SELECT * FROM payments WHERE id=$1 AND actor_subject=$2 FOR UPDATE",[input.aggregate.paymentIntentId,input.aggregate.actorSubject])).rows[0];if(!payment)throw new Error("Devnet payment ownership mismatch.");let target=aggregateStatus(input.preparation.state);
  let mismatches:string[]=[];
  if(target==="SETTLED"){
    // Resolve and lock the committed generation here, inside the same transaction
    // that changes execution/payment truth and creates the receipt. Caller snapshots
    // are identity hints only; economics and finality come from durable rows.
    const verified=await this.settledPreparation(client,found,payment,input.preparation);
    input={...input,...verified.evidence};
    mismatches=verified.mismatches;
    if(mismatches.length)target="UNKNOWN";
  }else if(found.review_reason===SETTLEMENT_ECONOMICS_MISMATCH){target="UNKNOWN";}
  let current=String(found.status);
  if(mismatches.length&&["SETTLED","FAILED","CANCELLED"].includes(current))throw new Error("Terminal Devnet execution conflicts with settlement economics.");for(const next of path(current,target)){await client.query(`UPDATE payment_executions SET status=$2::payment_execution_status,version=version+1,provider_reference=COALESCE(provider_reference,$3),submitted_at=CASE WHEN $2::payment_execution_status IN ('PROCESSING','UNKNOWN','SETTLED','FAILED') THEN COALESCE(submitted_at,$4::timestamptz) ELSE submitted_at END,settled_at=CASE WHEN $2::payment_execution_status='SETTLED' THEN COALESCE(settled_at,$4::timestamptz) ELSE settled_at END,failed_at=CASE WHEN $2::payment_execution_status='FAILED' THEN COALESCE(failed_at,$4::timestamptz) ELSE failed_at END,failure_code=CASE WHEN $2::payment_execution_status='FAILED' THEN COALESCE(failure_code,$5,'DEVNET_EXECUTION_FAILED') ELSE failure_code END,failure_category=CASE WHEN $2::payment_execution_status='FAILED' THEN COALESCE(failure_category,'DEVNET') ELSE failure_category END,failure_retryable=CASE WHEN $2::payment_execution_status='FAILED' THEN false ELSE failure_retryable END,settlement_evidence=CASE WHEN $2::payment_execution_status='SETTLED' THEN COALESCE(settlement_evidence,jsonb_build_object('type','solana.signature','signature',$3,'network','solana-devnet')) ELSE settlement_evidence END,updated_at=$4 WHERE execution_id=$1`,[input.aggregate.executionId,next,input.signature??null,input.observedAt,input.failureCode??null]);await client.query(`INSERT INTO payment_execution_events(execution_id,sequence_number,event_type,from_status,to_status,occurred_at) SELECT $1,COALESCE(MAX(sequence_number),0)+1,$2,$3,$4,$5 FROM payment_execution_events WHERE execution_id=$1`,[input.aggregate.executionId,event(next),current,next,input.observedAt]);current=next;}
  if(mismatches.length){
    await client.query(`UPDATE payment_executions SET review_reason=$2,version=version+1,updated_at=$3 WHERE execution_id=$1 AND review_reason IS DISTINCT FROM $2`,[input.aggregate.executionId,SETTLEMENT_ECONOMICS_MISMATCH,input.observedAt]);
    // The execution lock serializes this append-only event, including concurrent
    // replay. Keep public evidence and bounded field names, never signed bytes.
    await client.query(`INSERT INTO payment_execution_events(execution_id,sequence_number,event_type,from_status,to_status,details,occurred_at)
      SELECT $1,COALESCE(MAX(sequence_number),0)+1,'settlement_projection_blocked','UNKNOWN','UNKNOWN',$2::jsonb,$3
      FROM payment_execution_events WHERE execution_id=$1
      HAVING NOT EXISTS(SELECT 1 FROM payment_execution_events WHERE execution_id=$1 AND event_type='settlement_projection_blocked')`,
      [input.aggregate.executionId,JSON.stringify({code:SETTLEMENT_ECONOMICS_MISMATCH,preparationId:input.preparation.preparationId,generation:input.preparation.generation,signature:input.signature,slot:input.slot,confirmationStatus:input.confirmationStatus,fields:mismatches}),input.observedAt]);
  }
  if(target==="SETTLED"){if(!input.signature||!input.slot||!/^(0|[1-9]\d*)$/.test(input.slot)||input.confirmationStatus!=="finalized")throw new Error("Finalized Devnet settlement evidence is required.");const receiptId=`receipt:${input.aggregate.executionId}`;await client.query(`INSERT INTO payment_execution_receipts(receipt_id,execution_id,payment_intent_id,actor_subject,runtime_transaction_id,rail,asset,amount_units,amount_decimals,sender_id,recipient_id,memo,provider_reference,settled_at,evidence_type,evidence_version,evidence,schema_version,request_hash,created_at) SELECT $4,e.execution_id,e.payment_intent_id,e.actor_subject,e.execution_id::text,'solana',p.asset,p.amount_raw,6,'server-custodied-signer','wallet:'||p.recipient_address,p.purpose,$2::text,$3::timestamptz,'solana.signature',1,jsonb_build_object('network','solana-devnet','signature',$2::text,'slot',$5::text,'confirmationStatus','finalized'),1,p.request_hash,$3::timestamptz FROM payment_executions e JOIN payments p ON p.id=e.payment_intent_id WHERE e.execution_id=$1 ON CONFLICT(execution_id) DO NOTHING`,[input.aggregate.executionId,input.signature,input.observedAt,receiptId,input.slot]);await client.query(`INSERT INTO payment_execution_events(execution_id,sequence_number,event_type,from_status,to_status,occurred_at) SELECT $1,COALESCE(MAX(sequence_number),0)+1,'receipt_created','SETTLED','SETTLED',$2 FROM payment_execution_events WHERE execution_id=$1 HAVING NOT EXISTS(SELECT 1 FROM payment_execution_events WHERE execution_id=$1 AND event_type='receipt_created')`,[input.aggregate.executionId,input.observedAt]);if(payment.status==="COMPLETED"){if(payment.execution_receipt_id!==receiptId||payment.solana_signature!==input.signature||String(payment.confirmed_slot)!==input.slot||new Date(payment.completed_at).toISOString()!==new Date(input.observedAt).toISOString())throw new Error("Completed Devnet payment projection conflicts with authoritative settlement.");}else{if(!["PROCESSING","UNKNOWN"].includes(String(payment.status)))throw new Error("Devnet payment is not eligible for settlement completion.");await client.query(`UPDATE payments SET status='COMPLETED',version=version+1,solana_signature=$2,confirmed_slot=$3::numeric,confirmation_status='finalized',completed_at=$4::timestamptz,execution_receipt_id=$5,updated_at=$4::timestamptz WHERE id=$1`,[input.aggregate.paymentIntentId,input.signature,input.slot,input.observedAt,receiptId]);await client.query(`INSERT INTO payment_events(payment_id,sequence_number,event_type,from_status,to_status,details,occurred_at) SELECT $1,COALESCE(MAX(sequence_number),0)+1,'SETTLEMENT_CONFIRMED',$2::payment_status,'COMPLETED',jsonb_build_object('executionId',$3::text,'receiptId',$4::text),$5::timestamptz FROM payment_events WHERE payment_id=$1 HAVING NOT EXISTS(SELECT 1 FROM payment_events WHERE payment_id=$1 AND event_type='SETTLEMENT_CONFIRMED')`,[input.aggregate.paymentIntentId,payment.status,input.aggregate.executionId,receiptId,input.observedAt]);}}
  const updated=await this.load(client,input.aggregate.paymentIntentId,input.aggregate.actorSubject,false);return map(updated);});}
 private async settledPreparation(client:PoolClient,execution:any,payment:any,claimed:PersistedDevnetPreparation){
  const prepared=(await client.query(`SELECT p.*,c.transaction_signature AS commitment_signature,c.signed_transaction_digest AS commitment_digest,c.committed_at AS commitment_time
    FROM devnet_submission_commitments c JOIN devnet_execution_preparations p ON p.preparation_id=c.preparation_id AND p.execution_id=c.execution_id
    WHERE c.execution_id=$1 FOR UPDATE OF p,c`,[execution.execution_id])).rows[0];
  if(!prepared||prepared.lifecycle_state!=="SETTLED"||prepared.abandoned_at!==null||!prepared.committed_at||
    prepared.execution_id!==execution.execution_id||prepared.payment_intent_id!==execution.payment_intent_id||
    prepared.payment_intent_id!==payment.id||prepared.actor_subject!==execution.actor_subject||prepared.actor_subject!==payment.actor_subject||
    prepared.preparation_id!==claimed.preparationId||prepared.execution_id!==claimed.executionId||
    prepared.payment_intent_id!==claimed.paymentIntentId||prepared.actor_subject!==claimed.actorSubject||Number(prepared.generation)!==claimed.generation||
    prepared.transaction_signature!==prepared.commitment_signature||!Buffer.from(prepared.signed_transaction_digest).equals(prepared.commitment_digest)||
    prepared.transaction_signature!==claimed.artifact.signature||Buffer.from(prepared.signed_transaction_digest).toString("hex")!==claimed.artifact.signedTransactionDigest||
    new Date(prepared.committed_at).getTime()!==new Date(prepared.commitment_time).getTime()){
    throw new Error("Authoritative committed Devnet preparation identity is required for settlement.");
  }
  // Observations and commitments are append-only; the preparation lock and its
  // immutable identity bind this finalized evidence to exactly one generation.
  const observation=(await client.query(`SELECT o.* FROM devnet_reconciliation_observations o
    WHERE o.execution_id=$1 AND o.preparation_id=$2 AND o.transaction_signature=$3 AND o.provider_id=$4
      AND o.outcome='SETTLED' AND o.confirmation_status='finalized' AND o.slot IS NOT NULL AND o.observed_at >= $5
    ORDER BY o.sequence_number DESC LIMIT 1`,[prepared.execution_id,prepared.preparation_id,prepared.transaction_signature,prepared.reconciliation_provider_id,prepared.commitment_time])).rows[0];
  if(!observation)throw new Error("Finalized Devnet settlement evidence is required.");
  return{mismatches:settlementEconomicsMismatches(prepared,execution,payment),evidence:{signature:String(observation.transaction_signature),slot:String(observation.slot),confirmationStatus:"finalized",observedAt:new Date(observation.observed_at).toISOString()}};
 }
 private async load(client:PoolClient,paymentId:string,actor:string,lock:boolean){const result=await client.query(`${SELECT} WHERE e.payment_intent_id=$1 AND e.actor_subject=$2${lock?" FOR UPDATE OF e":""}`,[paymentId,actor]);return result.rows[0];}
 private async tx<T>(fn:(client:PoolClient)=>Promise<T>){const client=await this.pool.connect();try{await client.query("BEGIN");const value=await fn(client);await client.query("COMMIT");return value}catch(error){await client.query("ROLLBACK");throw error}finally{client.release();}}
}
const SELECT=`SELECT e.*,p.amount_raw,p.recipient_address,p.purpose,r.receipt_id FROM payment_executions e JOIN payments p ON p.id=e.payment_intent_id LEFT JOIN payment_execution_receipts r ON r.execution_id=e.execution_id`;
function map(row:any):BrowserDevnetAggregate{return Object.freeze({executionId:String(row.execution_id),paymentIntentId:String(row.payment_intent_id),actorSubject:String(row.actor_subject),providerIdempotencyKey:String(row.provider_idempotency_key),amountRaw:String(row.amount_raw),recipientWallet:String(row.recipient_address),purpose:row.purpose===null?null:String(row.purpose),createdAt:new Date(row.created_at).toISOString(),...(row.receipt_id?{receiptId:String(row.receipt_id)}:{}),...(row.settled_at?{settledAt:new Date(row.settled_at).toISOString()}:{})});}
function aggregateStatus(state:PersistedDevnetPreparation["state"]){return state==="SETTLED"?"SETTLED":state==="FAILED"?"FAILED":state==="ACCEPTED_PENDING"?"PROCESSING":state==="UNKNOWN_RECONCILIATION_REQUIRED"?"UNKNOWN":state==="SUBMISSION_COMMITTED_RECONCILE_ONLY"?"SUBMITTING":"READY";}
function path(initial:string,target:string){let current=initial;if(current===target||["SETTLED","FAILED","CANCELLED"].includes(current))return[];const steps:string[]=[];if(current==="READY"&&target!=="READY"){steps.push("SUBMITTING");current="SUBMITTING";}if(current==="SUBMITTING"&&target==="SETTLED"){steps.push("PROCESSING");current="PROCESSING";}if(current==="SUBMITTING"&&["PROCESSING","UNKNOWN","FAILED"].includes(target)){steps.push(target);return steps;}if(current==="PROCESSING"&&["SETTLED","UNKNOWN","FAILED"].includes(target))steps.push(target);else if(current==="UNKNOWN"&&["PROCESSING","SETTLED","FAILED"].includes(target))steps.push(target);return steps;}
function event(status:string){return status==="SUBMITTING"?"submission_committed":status==="PROCESSING"?"submission_accepted":status==="UNKNOWN"?"submission_unknown":status==="SETTLED"?"execution_settled":"execution_failed";}

const SETTLEMENT_ECONOMICS_MISMATCH="DEVNET_SETTLEMENT_ECONOMICS_MISMATCH";
function settlementEconomicsMismatches(prepared:any,execution:any,payment:any):string[]{
 const fields:string[]=[];
 if(execution.execution_mode!=="devnet_validation"||execution.selected_rail!=="solana"||execution.settlement_network!=="solana-devnet")fields.push("executionPolicy");
 if(payment.network!=="solana-devnet"||payment.rail!=="solana"||payment.asset!=="USDC"||payment.recipient_type!=="DIRECT_WALLET"||!payment.user_confirmed_at)fields.push("paymentPolicy");
 if(payment.mint_address!==CIRCLE_SOLANA_DEVNET_USDC_MINT||prepared.mint_address!==CIRCLE_SOLANA_DEVNET_USDC_MINT)fields.push("mint");
 if(Number(prepared.amount_decimals)!==CIRCLE_SOLANA_DEVNET_USDC_DECIMALS)fields.push("decimals");
 if(String(prepared.amount_units)!==String(payment.amount_raw))fields.push("rawAmount");
 if(prepared.destination_address!==payment.recipient_address)fields.push("destination");
 // Reconstruct the historical policy from the immutable artifact, not today's
 // environment or signer. This preserves valid reconciliation after key rotation
 // while checking the existing signer/mint ATA and policy identity invariants.
 try{
   const hash=hashDevnetPolicy(devnetPreparationPolicy({mint:String(prepared.mint_address),decimals:Number(prepared.amount_decimals),sourceTokenAccount:String(prepared.source_token_account),signerKeyId:String(prepared.signer_key_id),signerKeyVersion:String(prepared.signer_key_version),signerPublicKey:String(prepared.signer_public_key),submissionProviderId:String(prepared.submission_provider_id),reconciliationProviderId:String(prepared.reconciliation_provider_id)}));
   if(hash!==Buffer.from(prepared.policy_hash).toString("hex")||hash!==Buffer.from(execution.policy_hash??[]).toString("hex"))fields.push("historicalPolicy");
 }catch{fields.push("signerSourcePolicy");}
 return fields;
}
