import { randomUUID } from "node:crypto";
import type { Pool, PoolClient } from "pg";
import type { CompleteOperationInput, CreateExecutionInput, ExecutionRepository } from "../../executions/executionRepository";
import type { ExecutionAttempt, ExecutionStatus, PaymentExecution } from "../../executions/executionTypes";

export class PostgresExecutionRepository implements ExecutionRepository {
  constructor(private readonly pool:Pool){}
  async createOrGet(input:CreateExecutionInput){return this.tx(async c=>{const result=await c.query(`INSERT INTO payment_executions(execution_id,payment_intent_id,actor_subject,provider_idempotency_key,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$5) ON CONFLICT(payment_intent_id) DO NOTHING RETURNING *`,[input.executionId,input.paymentIntentId,input.actorSubject,input.providerIdempotencyKey,input.now]);if(result.rows[0])return{execution:map(result.rows[0]),created:true};const existing=await c.query("SELECT * FROM payment_executions WHERE payment_intent_id=$1 FOR UPDATE",[input.paymentIntentId]);return{execution:map(existing.rows[0]),created:false};});}
  async findByPaymentIntent(id:string){const r=await this.pool.query("SELECT * FROM payment_executions WHERE payment_intent_id=$1",[id]);return r.rows[0]?map(r.rows[0]):undefined;}
  async claim(statuses:readonly ExecutionStatus[],workerId:string,now:string,leaseExpiresAt:string){return this.tx(async c=>{const r=await c.query(`SELECT * FROM payment_executions WHERE status=ANY($1::payment_execution_status[]) AND (next_attempt_at IS NULL OR next_attempt_at<=$2) AND (lease_expires_at IS NULL OR lease_expires_at<=$2) ORDER BY created_at,execution_id FOR UPDATE SKIP LOCKED LIMIT 1`,[statuses,now]);if(!r.rows[0])return undefined;const current=map(r.rows[0]);const operation=current.status==="READY"?"SUBMIT" as const:"RECONCILE" as const;const status=current.status==="READY"?"SUBMITTING":current.status;const u=await c.query(`UPDATE payment_executions SET status=$2,version=version+1,attempt_count=attempt_count+1,started_at=COALESCE(started_at,$3),lease_owner=$4,lease_expires_at=$5,updated_at=$3 WHERE execution_id=$1 RETURNING *`,[current.executionId,status,now,workerId,leaseExpiresAt]);const execution=map(u.rows[0]);return{execution,attempt:{attemptId:randomUUID(),executionId:execution.executionId,attemptNumber:execution.attemptCount,operation,startedAt:now}};});}
  async complete(i:CompleteOperationInput){return this.tx(async c=>{const r=await c.query(`UPDATE payment_executions SET status=$2,version=version+1,provider_reference=COALESCE($3,provider_reference),reconciliation_reference=COALESCE($4,reconciliation_reference),submitted_at=COALESCE($5,submitted_at),settled_at=COALESCE($6,settled_at),failed_at=COALESCE($7,failed_at),failure_code=COALESCE($8,failure_code),failure_category=COALESCE($9,failure_category),failure_retryable=COALESCE($10,failure_retryable),review_reason=COALESCE($11,review_reason),settlement_evidence=COALESCE($12,settlement_evidence),next_attempt_at=$13,observation_sequence=COALESCE($14,observation_sequence),last_reconciled_at=CASE WHEN $15='RECONCILE' THEN $16 ELSE last_reconciled_at END,lease_owner=NULL,lease_expires_at=NULL,updated_at=$16 WHERE execution_id=$1 AND version=$17 AND lease_owner=$18 RETURNING *`,[i.executionId,i.toStatus,i.providerReference??null,i.reconciliationReference??null,i.submittedAt??null,i.settledAt??null,i.failedAt??null,i.failureCode??null,i.failureCategory??null,i.failureRetryable??null,i.reviewReason??null,i.evidence?JSON.stringify(i.evidence):null,i.nextAttemptAt??null,i.observationSequence??null,i.operation,i.completedAt,i.expectedVersion.toString(),i.leaseOwner]);if(!r.rows[0])throw new Error("Execution version or lease conflict.");const e=map(r.rows[0]);await c.query(`INSERT INTO payment_execution_attempts(attempt_id,execution_id,attempt_number,operation,started_at,completed_at,outcome,failure_code,side_effect,recovery_action,evidence) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[i.attemptId,i.executionId,e.attemptCount,i.operation,e.startedAt??i.completedAt,i.completedAt,i.toStatus,i.failureCode??null,i.sideEffect??null,i.recoveryAction??null,i.evidence?JSON.stringify(i.evidence):null]);return e;});}
  async listAttempts(id:string):Promise<ExecutionAttempt[]>{const r=await this.pool.query("SELECT * FROM payment_execution_attempts WHERE execution_id=$1 ORDER BY attempt_number",[id]);return r.rows.map(x=>({attemptId:String(x.attempt_id),executionId:String(x.execution_id),attemptNumber:Number(x.attempt_number),operation:x.operation,startedAt:new Date(x.started_at).toISOString(),completedAt:x.completed_at?new Date(x.completed_at).toISOString():undefined,outcome:x.outcome??undefined,failureCode:x.failure_code??undefined,sideEffect:x.side_effect??undefined,recoveryAction:x.recovery_action??undefined,evidence:x.evidence??undefined}));}
  private async tx<T>(fn:(c:PoolClient)=>Promise<T>){const c=await this.pool.connect();try{await c.query("BEGIN");const v=await fn(c);await c.query("COMMIT");return v;}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
}
function iso(v:unknown){return v?new Date(String(v)).toISOString():undefined;}
function map(r:any):PaymentExecution{return Object.freeze({executionId:String(r.execution_id),paymentIntentId:String(r.payment_intent_id),actorSubject:String(r.actor_subject),status:r.status,version:BigInt(r.version),selectedRail:"mock",runtimeContractVersion:1,adapterVersion:1,providerIdempotencyKey:String(r.provider_idempotency_key),providerReference:r.provider_reference??undefined,reconciliationReference:r.reconciliation_reference??undefined,attemptCount:Number(r.attempt_count),observationSequence:Number(r.observation_sequence),nextAttemptAt:iso(r.next_attempt_at),lastReconciledAt:iso(r.last_reconciled_at),failureCode:r.failure_code??undefined,failureCategory:r.failure_category??undefined,failureRetryable:r.failure_retryable??undefined,reviewReason:r.review_reason??undefined,settlementEvidence:r.settlement_evidence??undefined,createdAt:iso(r.created_at)!,startedAt:iso(r.started_at),submittedAt:iso(r.submitted_at),settledAt:iso(r.settled_at),failedAt:iso(r.failed_at),cancelledAt:iso(r.cancelled_at),updatedAt:iso(r.updated_at)!,leaseOwner:r.lease_owner??undefined,leaseExpiresAt:iso(r.lease_expires_at)});}
