import type{Pool,PoolClient}from"pg";import type{BrowserDevnetAggregate,BrowserDevnetExecutionStore}from"../../devnet/browserDevnetExecution";import type{PersistedDevnetPreparation}from"../../devnet/devnetExecutionState";
export class PostgresBrowserDevnetExecutionStore implements BrowserDevnetExecutionStore{constructor(private pool:Pool){}
 async createOrGet(input:Parameters<BrowserDevnetExecutionStore["createOrGet"]>[0]){return this.tx(async client=>{const inserted=await client.query(`INSERT INTO payment_executions(execution_id,payment_intent_id,actor_subject,status,selected_rail,execution_mode,settlement_network,policy_hash,provider_idempotency_key,created_at,updated_at) VALUES($1,$2,$3,'READY','solana','devnet_validation','solana-devnet',decode($4,'hex'),$5,$6,$6) ON CONFLICT(payment_intent_id) DO NOTHING RETURNING execution_id`,[input.executionId,input.paymentIntentId,input.actorSubject,input.policyHash,input.providerIdempotencyKey,input.now]);const row=await this.load(client,input.paymentIntentId,input.actorSubject,true);if(!row)throw new Error("Devnet execution ownership mismatch.");if(row.execution_mode!=="devnet_validation"||row.selected_rail!=="solana"||row.settlement_network!=="solana-devnet"||Buffer.from(row.policy_hash).toString("hex")!==input.policyHash||row.provider_idempotency_key!==input.providerIdempotencyKey)throw new Error("Payment intent already has an incompatible execution.");if(inserted.rows[0])await client.query("INSERT INTO payment_execution_events(execution_id,sequence_number,event_type,to_status,occurred_at) VALUES($1,1,'execution_created','READY',$2) ON CONFLICT DO NOTHING",[row.execution_id,input.now]);return{aggregate:map(row),created:Boolean(inserted.rows[0])};});}
 async find(paymentIntentId:string,actorSubject:string){const result=await this.pool.query(`${SELECT} WHERE e.payment_intent_id=$1 AND e.actor_subject=$2`,[paymentIntentId,actorSubject]);return result.rows[0]?map(result.rows[0]):undefined;}
 async applyLifecycle(input:Readonly<{aggregate:BrowserDevnetAggregate;preparation:PersistedDevnetPreparation;signature?:string;observedAt:string;failureCode?:string}>){return this.tx(async client=>{const found=await this.load(client,input.aggregate.paymentIntentId,input.aggregate.actorSubject,true);if(!found||String(found.execution_id)!==input.aggregate.executionId)throw new Error("Devnet execution ownership mismatch.");const target=aggregateStatus(input.preparation.state);let current=String(found.status);for(const next of path(current,target)){await client.query(`UPDATE payment_executions SET status=$2,version=version+1,provider_reference=COALESCE(provider_reference,$3),submitted_at=CASE WHEN $2 IN ('PROCESSING','UNKNOWN','SETTLED','FAILED') THEN COALESCE(submitted_at,$4::timestamptz) ELSE submitted_at END,settled_at=CASE WHEN $2='SETTLED' THEN COALESCE(settled_at,$4::timestamptz) ELSE settled_at END,failed_at=CASE WHEN $2='FAILED' THEN COALESCE(failed_at,$4::timestamptz) ELSE failed_at END,failure_code=CASE WHEN $2='FAILED' THEN COALESCE(failure_code,$5,'DEVNET_EXECUTION_FAILED') ELSE failure_code END,failure_category=CASE WHEN $2='FAILED' THEN COALESCE(failure_category,'DEVNET') ELSE failure_category END,failure_retryable=CASE WHEN $2='FAILED' THEN false ELSE failure_retryable END,settlement_evidence=CASE WHEN $2='SETTLED' THEN COALESCE(settlement_evidence,jsonb_build_object('type','solana.signature','signature',$3,'network','solana-devnet')) ELSE settlement_evidence END,updated_at=$4 WHERE execution_id=$1`,[input.aggregate.executionId,next,input.signature??null,input.observedAt,input.failureCode??null]);await client.query(`INSERT INTO payment_execution_events(execution_id,sequence_number,event_type,from_status,to_status,occurred_at) SELECT $1,COALESCE(MAX(sequence_number),0)+1,$2,$3,$4,$5 FROM payment_execution_events WHERE execution_id=$1`,[input.aggregate.executionId,event(next),current,next,input.observedAt]);current=next;}
  if(target==="SETTLED"){await client.query(`INSERT INTO payment_execution_receipts(receipt_id,execution_id,payment_intent_id,actor_subject,runtime_transaction_id,rail,asset,amount_units,amount_decimals,sender_id,recipient_id,memo,provider_reference,settled_at,evidence_type,evidence_version,evidence,schema_version,request_hash,created_at) SELECT 'receipt:'||e.execution_id,e.execution_id,e.payment_intent_id,e.actor_subject,e.execution_id::text,'solana',p.asset,p.amount_raw,6,'server-custodied-signer','wallet:'||p.recipient_address,p.purpose,$2,$3,'solana.signature',1,jsonb_build_object('network','solana-devnet','signature',$2),1,p.request_hash,$3 FROM payment_executions e JOIN payments p ON p.id=e.payment_intent_id WHERE e.execution_id=$1 ON CONFLICT(execution_id) DO NOTHING`,[input.aggregate.executionId,input.signature,input.observedAt]);await client.query(`INSERT INTO payment_execution_events(execution_id,sequence_number,event_type,from_status,to_status,occurred_at) SELECT $1,COALESCE(MAX(sequence_number),0)+1,'receipt_created','SETTLED','SETTLED',$2 FROM payment_execution_events WHERE execution_id=$1 AND NOT EXISTS(SELECT 1 FROM payment_execution_events WHERE execution_id=$1 AND event_type='receipt_created')`,[input.aggregate.executionId,input.observedAt]);}
  const updated=await this.load(client,input.aggregate.paymentIntentId,input.aggregate.actorSubject,false);return map(updated);});}
 private async load(client:PoolClient,paymentId:string,actor:string,lock:boolean){const result=await client.query(`${SELECT} WHERE e.payment_intent_id=$1 AND e.actor_subject=$2${lock?" FOR UPDATE OF e":""}`,[paymentId,actor]);return result.rows[0];}
 private async tx<T>(fn:(client:PoolClient)=>Promise<T>){const client=await this.pool.connect();try{await client.query("BEGIN");const value=await fn(client);await client.query("COMMIT");return value}catch(error){await client.query("ROLLBACK");throw error}finally{client.release();}}
}
const SELECT=`SELECT e.*,p.amount_raw,p.recipient_address,p.purpose,r.receipt_id FROM payment_executions e JOIN payments p ON p.id=e.payment_intent_id LEFT JOIN payment_execution_receipts r ON r.execution_id=e.execution_id`;
function map(row:any):BrowserDevnetAggregate{return Object.freeze({executionId:String(row.execution_id),paymentIntentId:String(row.payment_intent_id),actorSubject:String(row.actor_subject),providerIdempotencyKey:String(row.provider_idempotency_key),amountRaw:String(row.amount_raw),recipientWallet:String(row.recipient_address),purpose:row.purpose===null?null:String(row.purpose),createdAt:new Date(row.created_at).toISOString(),...(row.receipt_id?{receiptId:String(row.receipt_id)}:{}),...(row.settled_at?{settledAt:new Date(row.settled_at).toISOString()}:{})});}
function aggregateStatus(state:PersistedDevnetPreparation["state"]){return state==="SETTLED"?"SETTLED":state==="FAILED"?"FAILED":state==="ACCEPTED_PENDING"?"PROCESSING":state==="UNKNOWN_RECONCILIATION_REQUIRED"?"UNKNOWN":state==="SUBMISSION_COMMITTED_RECONCILE_ONLY"?"SUBMITTING":"READY";}
function path(initial:string,target:string){let current=initial;if(current===target||["SETTLED","FAILED","CANCELLED"].includes(current))return[];const steps:string[]=[];if(current==="READY"&&target!=="READY"){steps.push("SUBMITTING");current="SUBMITTING";}if(current==="SUBMITTING"&&target==="SETTLED"){steps.push("PROCESSING");current="PROCESSING";}if(current==="SUBMITTING"&&["PROCESSING","UNKNOWN","FAILED"].includes(target)){steps.push(target);return steps;}if(current==="PROCESSING"&&["SETTLED","UNKNOWN","FAILED"].includes(target))steps.push(target);else if(current==="UNKNOWN"&&["PROCESSING","SETTLED","FAILED"].includes(target))steps.push(target);return steps;}
function event(status:string){return status==="SUBMITTING"?"submission_committed":status==="PROCESSING"?"submission_accepted":status==="UNKNOWN"?"submission_unknown":status==="SETTLED"?"execution_settled":"execution_failed";}
