import type{Pool,PoolClient}from"pg";import type{PaymentRequestClaim,PaymentRequestRecord,PaymentRequestRepository,PaymentRequestPartySnapshot}from"../../paymentRequests/paymentRequestTypes";import{PaymentRequestVersionConflictError}from"../../paymentRequests/paymentRequestTypes";
import{observeTransaction}from"../../observability/reliabilityObservability";
export class PostgresPaymentRequestRepository implements PaymentRequestRepository{constructor(private pool:Pool){}
 async claim(i:Parameters<PaymentRequestRepository["claim"]>[0]):Promise<PaymentRequestClaim>{return this.tx(async c=>{const inserted=await c.query(`INSERT INTO payment_requests(request_id,requester_account_id,requester_actor_subject,payer_account_id,requester_snapshot,payer_snapshot,amount_raw,asset,purpose,request_hash,idempotency_key,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,'USDC',$8,decode($9,'hex'),$10,$11,$11) ON CONFLICT(requester_actor_subject,idempotency_key) DO NOTHING RETURNING *`,[i.requestId,i.requesterAccountId,i.requesterActorSubject,i.payerAccountId,JSON.stringify(i.requesterSnapshot),JSON.stringify(i.payerSnapshot),i.amountRaw.toString(),i.purpose,i.requestHash,i.idempotencyKey,i.occurredAt]);if(inserted.rows[0]){await event(c,i.requestId,"CREATED",null,"PENDING",i.occurredAt);return{outcome:"CLAIMED",request:map(inserted.rows[0])}}const prior=map((await c.query("SELECT * FROM payment_requests WHERE requester_actor_subject=$1 AND idempotency_key=$2 FOR UPDATE",[i.requesterActorSubject,i.idempotencyKey])).rows[0]);return{outcome:prior.requestHash===i.requestHash?"EXISTING":"HASH_CONFLICT",request:prior}})}
 async findByIdempotencyKey(requesterActorSubject:string,idempotencyKey:string){const r=await this.pool.query("SELECT * FROM payment_requests WHERE requester_actor_subject=$1 AND idempotency_key=$2",[requesterActorSubject,idempotencyKey]);return r.rows[0]?map(r.rows[0]):undefined}
 async find(id:string){const r=await this.pool.query("SELECT * FROM payment_requests WHERE request_id=$1",[id]);return r.rows[0]?map(r.rows[0]):undefined}
 async listVisible(a:string,l:number){const r=await this.pool.query("SELECT * FROM payment_requests WHERE requester_account_id=$1 OR payer_account_id=$1 ORDER BY created_at DESC,request_id DESC LIMIT $2",[a,l]);return r.rows.map(map)}
 async transition(i:Parameters<PaymentRequestRepository["transition"]>[0]){return this.tx(async c=>{const prior=(await c.query("SELECT * FROM payment_requests WHERE request_id=$1 FOR UPDATE",[i.requestId])).rows[0];if(!prior)throw new Error("NOT_FOUND");const current=map(prior);if(current.version!==i.expectedVersion)throw new PaymentRequestVersionConflictError();if(current.status!=="PENDING")throw new Error("ILLEGAL_TRANSITION");if(i.toStatus==="CANCELLED"?current.requesterAccountId!==i.actorAccountId:current.payerAccountId!==i.actorAccountId)throw new Error("NOT_FOUND");const timeColumn=i.toStatus==="ACCEPTED"?"accepted_at":i.toStatus==="DECLINED"?"declined_at":"cancelled_at";const result=await c.query(`UPDATE payment_requests SET status=$2,version=version+1,updated_at=$3,${timeColumn}=$3,linked_payment_intent_id=$4 WHERE request_id=$1 RETURNING *`,[i.requestId,i.toStatus,i.occurredAt,i.linkedPaymentIntentId??null]);await event(c,i.requestId,i.toStatus,"PENDING",i.toStatus,i.occurredAt);return map(result.rows[0])})}
 async markPaidByPaymentIntent(i:Parameters<PaymentRequestRepository["markPaidByPaymentIntent"]>[0]){const r=await this.pool.query("SELECT * FROM payment_requests WHERE linked_payment_intent_id=$1",[i.paymentIntentId]);if(!r.rows[0])return;const current=map(r.rows[0]);if(current.status==="PAID")return current;return undefined}
 private async tx<T>(f:(c:PoolClient)=>Promise<T>){const c=await this.pool.connect();try{return await observeTransaction(this.pool,async()=>{try{await c.query("BEGIN");const v=await f(c);await c.query("COMMIT");return v}catch(e){await c.query("ROLLBACK");throw e}})}finally{c.release()}}
}
async function event(c:PoolClient,id:string,type:string,from:string|null,to:string,at:string){await c.query(`INSERT INTO payment_request_events(request_id,sequence_number,event_type,from_status,to_status,occurred_at) SELECT $1,COALESCE(max(sequence_number),0)+1,$2,$3,$4,$5 FROM payment_request_events WHERE request_id=$1`,[id,type,from,to,at])}
function map(r:any):PaymentRequestRecord{return Object.freeze({requestId:String(r.request_id),requesterAccountId:String(r.requester_account_id),requesterActorSubject:String(r.requester_actor_subject),payerAccountId:String(r.payer_account_id),requesterSnapshot:r.requester_snapshot as PaymentRequestPartySnapshot,payerSnapshot:r.payer_snapshot as PaymentRequestPartySnapshot,amountRaw:BigInt(r.amount_raw),asset:"USDC",purpose:r.purpose===null?null:String(r.purpose),status:r.status,version:BigInt(r.version),requestHash:Buffer.from(r.request_hash).toString("hex"),idempotencyKey:String(r.idempotency_key),createdAt:new Date(r.created_at).toISOString(),updatedAt:new Date(r.updated_at).toISOString(),...(r.accepted_at?{acceptedAt:new Date(r.accepted_at).toISOString()}:{}),...(r.declined_at?{declinedAt:new Date(r.declined_at).toISOString()}:{}),...(r.cancelled_at?{cancelledAt:new Date(r.cancelled_at).toISOString()}:{}),...(r.expired_at?{expiredAt:new Date(r.expired_at).toISOString()}:{}),...(r.paid_at?{paidAt:new Date(r.paid_at).toISOString()}:{}),...(r.linked_payment_intent_id?{linkedPaymentIntentId:String(r.linked_payment_intent_id)}:{}),...(r.linked_execution_id?{linkedExecutionId:String(r.linked_execution_id)}:{}),...(r.linked_receipt_id?{linkedReceiptId:String(r.linked_receipt_id)}:{})})}
