import type{Pool,PoolClient}from"pg";
import type{DevnetRecoveryCandidate,DevnetRecoveryRepository,DevnetRecoveryTaskKind}from"../../devnet/devnetRecoveryRepository";
import type{PostgresDevnetExecutionStateRepository}from"./postgresDevnetExecutionStateRepository";
import{observeTransaction,runWithReliabilityContext}from"../../observability/reliabilityObservability";

export class PostgresDevnetRecoveryRepository implements DevnetRecoveryRepository{
  constructor(private readonly pool:Pool,private readonly states:PostgresDevnetExecutionStateRepository){}
  claimPreparation(workerId:string,now:string,leaseExpiresAt:string,currentBlockHeight:string){if(!/^(0|[1-9]\d*)$/.test(currentBlockHeight))return Promise.reject(new Error("Current Devnet block height is invalid."));return this.claim("PREPARATION",workerId,now,leaseExpiresAt,currentBlockHeight);}
  claimReconciliation(workerId:string,now:string,leaseExpiresAt:string){return this.claim("RECONCILIATION",workerId,now,leaseExpiresAt);}
  async release(executionId:string,taskKind:DevnetRecoveryTaskKind,workerId:string){await this.pool.query("DELETE FROM devnet_recovery_leases WHERE execution_id=$1 AND task_kind=$2 AND lease_owner=$3",[executionId,taskKind,workerId]);}
  private claim(kind:DevnetRecoveryTaskKind,workerId:string,now:string,leaseExpiresAt:string,currentBlockHeight?:string){return runWithReliabilityContext({dbOperation:"EXECUTION_CLAIM"},()=>this.tx(async client=>{if(!workerId||workerId.trim()!==workerId)throw new Error("Devnet recovery worker ID is invalid.");const result=await client.query(kind==="PREPARATION"?PREPARATION_CLAIM:RECONCILIATION_CLAIM,kind==="PREPARATION"?[kind,now,workerId,leaseExpiresAt,currentBlockHeight]:[kind,now,workerId,leaseExpiresAt]);const row=result.rows[0];if(!row)return undefined;const base={executionId:String(row.execution_id),paymentIntentId:String(row.payment_intent_id),actorSubject:String(row.actor_subject),providerIdempotencyKey:String(row.provider_idempotency_key)};return base;})).then(async(value)=>{if(!value)return undefined;const preparation=await this.states.findPreparation(value.executionId,value.actorSubject);return Object.freeze({...value,...(preparation?{preparation}:{})})as DevnetRecoveryCandidate;});}
  private async tx<T>(fn:(client:PoolClient)=>Promise<T>){const client=await this.pool.connect();try{return await observeTransaction(this.pool,async()=>{try{await client.query("BEGIN");const value=await fn(client);await client.query("COMMIT");return value;}catch(error){await client.query("ROLLBACK");throw error;}});}finally{client.release();}}
}
const BASE=`WITH candidate AS (SELECT e.execution_id,e.payment_intent_id,e.actor_subject,e.provider_idempotency_key FROM payment_executions e LEFT JOIN devnet_execution_preparations p ON p.execution_id=e.execution_id AND p.lifecycle_state<>'ABANDONED_PRE_CONTACT' LEFT JOIN devnet_recovery_leases l ON l.execution_id=e.execution_id AND l.task_kind=$1 WHERE e.execution_mode='devnet_validation' AND e.selected_rail='solana' AND e.settlement_network='solana-devnet' AND e.status NOT IN ('SETTLED','FAILED','CANCELLED') AND (l.execution_id IS NULL OR l.lease_expires_at<=$2)`;
const END=` ORDER BY e.created_at,e.execution_id FOR UPDATE OF e SKIP LOCKED LIMIT 1), leased AS (INSERT INTO devnet_recovery_leases(execution_id,task_kind,lease_owner,claimed_at,lease_expires_at) SELECT execution_id,$1,$3,$2,$4 FROM candidate ON CONFLICT(execution_id,task_kind) DO UPDATE SET lease_owner=EXCLUDED.lease_owner,claimed_at=EXCLUDED.claimed_at,lease_expires_at=EXCLUDED.lease_expires_at WHERE devnet_recovery_leases.lease_expires_at<=EXCLUDED.claimed_at RETURNING execution_id) SELECT candidate.* FROM candidate JOIN leased USING(execution_id)`;
const PREPARATION_CLAIM=`${BASE} AND (p.preparation_id IS NULL OR (p.lifecycle_state='PREPARED_NOT_CONTACTED' AND p.last_valid_block_height<$5::numeric))${END}`;
const RECONCILIATION_CLAIM=`${BASE} AND p.lifecycle_state IN ('SUBMISSION_COMMITTED_RECONCILE_ONLY','ACCEPTED_PENDING','UNKNOWN_RECONCILIATION_REQUIRED') AND EXISTS(SELECT 1 FROM devnet_submission_commitments c WHERE c.execution_id=e.execution_id AND c.preparation_id=p.preparation_id)${END}`;
