import type{Pool}from"pg";
import type{E2eReliabilityRepository}from"../../e2e/e2eRepository";
import type{E2eTestRun,SyntheticTestActor}from"../../e2e/e2eTypes";
export class PostgresE2eReliabilityRepository implements E2eReliabilityRepository{
 constructor(private readonly pool:Pool){}
 async createActor(input:Omit<SyntheticTestActor,"createdAt">&{createdAt?:string}){const r=await this.pool.query(`INSERT INTO synthetic_test_actors(synthetic_actor_id,account_id,actor_class,actor_kind,test_origin,created_at)VALUES($1,$2,$3,$4,$5,COALESCE($6::timestamptz,now())) ON CONFLICT(synthetic_actor_id) DO NOTHING RETURNING *`,[input.syntheticActorId,input.accountId,input.actorClass,input.actorKind,input.testOrigin,input.createdAt??null]);const value=r.rows[0]?mapActor(r.rows[0]):await this.findActor(input.syntheticActorId);if(!value||value.accountId!==input.accountId||value.actorKind!==input.actorKind||value.testOrigin!==input.testOrigin)throw new Error("Synthetic actor classification conflicts with durable truth.");return value;}
 async findActor(id:string){const r=await this.pool.query("SELECT * FROM synthetic_test_actors WHERE synthetic_actor_id=$1",[id]);return r.rows[0]?mapActor(r.rows[0]):undefined;}
 async startRun(input:Omit<E2eTestRun,"result"|"invariantViolations">){const r=await this.pool.query(`INSERT INTO e2e_test_runs(run_id,scenario_name,test_origin,mode,source_actor_id,destination_actor_id,source_actor_kind,destination_actor_kind,started_at)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[input.runId,input.scenarioName,input.testOrigin,input.mode,input.sourceActorId??null,input.destinationActorId??null,input.sourceActorKind,input.destinationActorKind,input.startedAt]);return mapRun(r.rows[0]);}
 async finishRun(id:string,input:Pick<E2eTestRun,"result"|"completedAt"|"paymentIntentId"|"executionId"|"failureStage"|"failureReason"|"invariantViolations"|"finalPaymentStatus"|"finalExecutionStatus"|"receiptCount"|"commitmentCount"|"submissionCount"|"durationMs">){if(input.result==="RUNNING"||!input.completedAt||input.durationMs===undefined)throw new Error("A run must finish with a terminal result, completion time, and duration.");const r=await this.pool.query(`UPDATE e2e_test_runs SET result=$2,completed_at=$3,payment_intent_id=$4,execution_id=$5,failure_stage=$6,failure_reason=$7,invariant_violations=$8::jsonb,final_payment_status=$9,final_execution_status=$10,receipt_count=$11,commitment_count=$12,submission_count=$13,duration_ms=$14 WHERE run_id=$1 AND result='RUNNING' RETURNING *`,[id,input.result,input.completedAt,input.paymentIntentId??null,input.executionId??null,input.failureStage??null,input.failureReason??null,JSON.stringify(input.invariantViolations),input.finalPaymentStatus??null,input.finalExecutionStatus??null,input.receiptCount??null,input.commitmentCount??null,input.submissionCount??null,input.durationMs]);if(!r.rows[0])throw new Error("E2E run is missing or already terminal.");return mapRun(r.rows[0]);}
 async findRun(id:string){const r=await this.pool.query("SELECT * FROM e2e_test_runs WHERE run_id=$1",[id]);return r.rows[0]?mapRun(r.rows[0]):undefined;}
}
function mapActor(r:any):SyntheticTestActor{return Object.freeze({syntheticActorId:String(r.synthetic_actor_id),accountId:String(r.account_id),actorClass:"synthetic_test",actorKind:r.actor_kind,testOrigin:r.test_origin,createdAt:new Date(r.created_at).toISOString()});}
function mapRun(r:any):E2eTestRun{return Object.freeze({runId:String(r.run_id),scenarioName:r.scenario_name,testOrigin:r.test_origin,mode:r.mode,sourceActorKind:r.source_actor_kind,destinationActorKind:r.destination_actor_kind,startedAt:new Date(r.started_at).toISOString(),result:r.result,invariantViolations:Object.freeze(r.invariant_violations as string[]),...(r.source_actor_id?{sourceActorId:String(r.source_actor_id)}:{}),...(r.destination_actor_id?{destinationActorId:String(r.destination_actor_id)}:{}),...(r.completed_at?{completedAt:new Date(r.completed_at).toISOString()}:{}),...(r.payment_intent_id?{paymentIntentId:String(r.payment_intent_id)}:{}),...(r.execution_id?{executionId:String(r.execution_id)}:{}),...(r.failure_stage?{failureStage:String(r.failure_stage)}:{}),...(r.failure_reason?{failureReason:String(r.failure_reason)}:{}),...(r.final_payment_status?{finalPaymentStatus:String(r.final_payment_status)}:{}),...(r.final_execution_status?{finalExecutionStatus:String(r.final_execution_status)}:{}),...(r.receipt_count===null?{}:{receiptCount:Number(r.receipt_count)}),...(r.commitment_count===null?{}:{commitmentCount:Number(r.commitment_count)}),...(r.submission_count===null?{}:{submissionCount:Number(r.submission_count)}),...(r.duration_ms===null?{}:{durationMs:Number(r.duration_ms)})});}
