import type { Pool, PoolClient } from "pg";
import { observeTransaction, runWithReliabilityContext } from "../../observability/reliabilityObservability";
import type { CommitDevnetSubmissionResult, DevnetExecutionStateRepository, PersistDevnetPreparationInput, PersistedDevnetPreparation } from "../../devnet/devnetExecutionState";
import { assertPreparedArtifact, assertReconciliationEvidence, assertSubmissionEvidence, reconciliationLifecycle, submissionLifecycle } from "../../devnet/devnetExecutionState";

export class PostgresDevnetExecutionStateRepository implements DevnetExecutionStateRepository {
  constructor(private readonly pool: Pool) {}

  persistPreparation(input: PersistDevnetPreparationInput) { return runWithReliabilityContext({dbOperation:"EXECUTION_CREATE"},()=>this.tx(async(client)=>{
    assertPreparedArtifact(input); await this.assertExecution(client,input);
    const result=await client.query(`${INSERT_PREPARATION} RETURNING *`,params(input)); return mapPreparation(result.rows[0]);
  })); }

  replaceExpiredPreparation(input:Readonly<{priorPreparationId:string;replacement:PersistDevnetPreparationInput;abandonedAt:string}>){return runWithReliabilityContext({dbOperation:"EXECUTION_COMPLETE"},()=>this.tx(async(client)=>{
    assertPreparedArtifact(input.replacement); await this.assertExecution(client,input.replacement);
    const prior=await client.query("SELECT * FROM devnet_execution_preparations WHERE preparation_id=$1 FOR UPDATE",[input.priorPreparationId]);
    const row=prior.rows[0]; if(!row||String(row.execution_id)!==input.replacement.executionId||String(row.actor_subject)!==input.replacement.actorSubject)throw new Error("Prior preparation was not found for this owner.");
    if(row.lifecycle_state!=="PREPARED_NOT_CONTACTED"||Number(row.generation)+1!==input.replacement.generation)throw new Error("Only the next generation of a never-contacted preparation may replace it.");
    if((await client.query("SELECT 1 FROM devnet_submission_commitments WHERE execution_id=$1",[input.replacement.executionId])).rows[0])throw new Error("Committed Devnet preparation is reconciliation-only and cannot be replaced.");
    await client.query("UPDATE devnet_execution_preparations SET lifecycle_state='ABANDONED_PRE_CONTACT',abandoned_at=$2 WHERE preparation_id=$1",[input.priorPreparationId,input.abandonedAt]);
    const result=await client.query(`${INSERT_PREPARATION} RETURNING *`,params(input.replacement));return mapPreparation(result.rows[0]);
  }));}

  commitSubmission(input:Readonly<{executionId:string;actorSubject:string;preparationId:string;commitmentId:string;committedAt:string}>){return runWithReliabilityContext({dbOperation:"EXECUTION_COMPLETE"},()=>this.tx<CommitDevnetSubmissionResult>(async(client)=>{
    const ownership=await client.query("SELECT actor_subject FROM payment_executions WHERE execution_id=$1 FOR UPDATE",[input.executionId]);if(String(ownership.rows[0]?.actor_subject)!==input.actorSubject)throw new Error("Devnet execution ownership mismatch.");
    const existing=await client.query("SELECT * FROM devnet_submission_commitments WHERE execution_id=$1",[input.executionId]);
    if(existing.rows[0]){const commitmentRow=existing.rows[0];if(String(commitmentRow.preparation_id)!==input.preparationId||String(commitmentRow.commitment_id)!==input.commitmentId)throw new Error("Devnet submission commitment conflict.");const preparationRow=await client.query("SELECT * FROM devnet_execution_preparations WHERE preparation_id=$1",[input.preparationId]);return Object.freeze({preparation:mapPreparation(preparationRow.rows[0]),commitment:mapCommitment(commitmentRow),submissionAuthorized:false});}
    const prepared=await client.query("SELECT * FROM devnet_execution_preparations WHERE preparation_id=$1 AND execution_id=$2 AND actor_subject=$3 FOR UPDATE",[input.preparationId,input.executionId,input.actorSubject]);
    const row=prepared.rows[0];if(!row)throw new Error("Prepared artifact was not found for this owner.");if(row.lifecycle_state!=="PREPARED_NOT_CONTACTED")throw new Error("Only a never-contacted preparation may be committed.");
    const commitment=await client.query(`INSERT INTO devnet_submission_commitments(commitment_id,execution_id,preparation_id,transaction_signature,signed_transaction_digest,committed_at) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[input.commitmentId,input.executionId,input.preparationId,row.transaction_signature,row.signed_transaction_digest,input.committedAt]);
    const updated=await client.query("UPDATE devnet_execution_preparations SET lifecycle_state='SUBMISSION_COMMITTED_RECONCILE_ONLY',committed_at=$2 WHERE preparation_id=$1 RETURNING *",[input.preparationId,input.committedAt]);
    return Object.freeze({preparation:mapPreparation(updated.rows[0]),commitment:mapCommitment(commitment.rows[0]),submissionAuthorized:true});
  }));}

  async findPreparation(executionId:string,actorSubject:string){const result=await this.pool.query("SELECT * FROM devnet_execution_preparations WHERE execution_id=$1 AND actor_subject=$2 AND lifecycle_state<>'ABANDONED_PRE_CONTACT'",[executionId,actorSubject]);return result.rows[0]?mapPreparation(result.rows[0]):undefined;}
  async findCommitment(executionId:string,actorSubject:string){const result=await this.pool.query(`SELECT c.* FROM devnet_submission_commitments c JOIN devnet_execution_preparations p ON p.preparation_id=c.preparation_id WHERE c.execution_id=$1 AND p.actor_subject=$2`,[executionId,actorSubject]);return result.rows[0]?mapCommitment(result.rows[0]):undefined;}
  recordReconciliationObservation(input:Parameters<DevnetExecutionStateRepository["recordReconciliationObservation"]>[0]){return runWithReliabilityContext({dbOperation:"EXECUTION_RECONCILE"},()=>this.tx(async(client)=>{
    assertReconciliationEvidence(input);await this.assertReconciliationFence(client,input.executionId,input.recoveryFence);const found=await client.query("SELECT * FROM devnet_execution_preparations WHERE preparation_id=$1 AND execution_id=$2 AND actor_subject=$3 FOR UPDATE",[input.preparationId,input.executionId,input.actorSubject]);const row=found.rows[0];if(!row)throw new Error("Prepared artifact was not found for this owner.");
    if(String(row.reconciliation_provider_id)!==input.providerId||String(row.transaction_signature)!==input.signature)throw new Error("Reconciliation evidence does not match immutable preparation policy.");const latest=(await client.query("SELECT * FROM devnet_reconciliation_observations WHERE execution_id=$1 ORDER BY sequence_number DESC LIMIT 1",[input.executionId])).rows[0];if(latest&&(sameObservation(mapObservation(latest),input)||["SETTLED","FAILED"].includes(String(row.lifecycle_state))))return Object.freeze({preparation:mapPreparation(row),observation:mapObservation(latest)});const state=reconciliationLifecycle(row.lifecycle_state,input.outcome);
    const sequence=Number((await client.query("SELECT COALESCE(MAX(sequence_number),0)+1 AS sequence FROM devnet_reconciliation_observations WHERE execution_id=$1",[input.executionId])).rows[0].sequence);
    const observed=await client.query("INSERT INTO devnet_reconciliation_observations(observation_id,execution_id,preparation_id,sequence_number,provider_id,transaction_signature,outcome,observed_at,slot,confirmation_status,error_code) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *",[input.observationId,input.executionId,input.preparationId,sequence,input.providerId,input.signature,input.outcome,input.observedAt,input.slot,input.confirmationStatus,input.errorCode]);
    const updated=await client.query("UPDATE devnet_execution_preparations SET lifecycle_state=$2 WHERE preparation_id=$1 RETURNING *",[input.preparationId,state]);return Object.freeze({preparation:mapPreparation(updated.rows[0]),observation:mapObservation(observed.rows[0])});
  }));}
  async listReconciliationObservations(executionId:string,actorSubject:string){const result=await this.pool.query("SELECT o.* FROM devnet_reconciliation_observations o JOIN devnet_execution_preparations p ON p.preparation_id=o.preparation_id WHERE o.execution_id=$1 AND p.actor_subject=$2 ORDER BY o.sequence_number",[executionId,actorSubject]);return result.rows.map(mapObservation);}
  recordSubmissionObservation(input:Parameters<DevnetExecutionStateRepository["recordSubmissionObservation"]>[0]){return runWithReliabilityContext({dbOperation:"EXECUTION_COMPLETE"},()=>this.tx(async client=>{assertSubmissionEvidence(input);const found=await client.query("SELECT p.*,c.commitment_id,c.transaction_signature AS commitment_signature FROM devnet_execution_preparations p JOIN devnet_submission_commitments c ON c.preparation_id=p.preparation_id WHERE p.preparation_id=$1 AND p.execution_id=$2 AND p.actor_subject=$3 FOR UPDATE OF p",[input.preparationId,input.executionId,input.actorSubject]);const row=found.rows[0];if(!row||String(row.commitment_id)!==input.commitmentId)throw new Error("Committed preparation was not found for this owner.");if(String(row.submission_provider_id)!==input.providerId||String(row.commitment_signature)!==input.signature)throw new Error("Submission evidence does not match immutable commitment policy.");const state=submissionLifecycle(row.lifecycle_state,input.outcome);const observed=await client.query("INSERT INTO devnet_submission_observations(observation_id,execution_id,preparation_id,commitment_id,provider_id,transaction_signature,outcome,contact_certainty,observed_at,provider_error_code,slot,confirmation_status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *",[input.observationId,input.executionId,input.preparationId,input.commitmentId,input.providerId,input.signature,input.outcome,input.contactCertainty,input.observedAt,input.providerErrorCode,input.slot,input.confirmationStatus]);const updated=await client.query("UPDATE devnet_execution_preparations SET lifecycle_state=$2 WHERE preparation_id=$1 RETURNING *",[input.preparationId,state]);return Object.freeze({preparation:mapPreparation(updated.rows[0]),observation:mapSubmissionObservation(observed.rows[0])});}));}
  async listSubmissionObservations(executionId:string,actorSubject:string){const result=await this.pool.query("SELECT o.* FROM devnet_submission_observations o JOIN devnet_execution_preparations p ON p.preparation_id=o.preparation_id WHERE o.execution_id=$1 AND p.actor_subject=$2 ORDER BY o.observed_at,o.observation_id",[executionId,actorSubject]);return result.rows.map(mapSubmissionObservation);}
  async listPreparationEligible(){const result=await this.pool.query("SELECT * FROM devnet_execution_preparations WHERE lifecycle_state='PREPARED_NOT_CONTACTED' ORDER BY prepared_at,execution_id");return result.rows.map(mapPreparation);}
  async listReconciliationEligible(){const result=await this.pool.query("SELECT * FROM devnet_execution_preparations WHERE lifecycle_state IN ('SUBMISSION_COMMITTED_RECONCILE_ONLY','ACCEPTED_PENDING','UNKNOWN_RECONCILIATION_REQUIRED') ORDER BY committed_at,execution_id");return result.rows.map(mapPreparation);}

  private async assertExecution(client:PoolClient,input:PersistDevnetPreparationInput){const result=await client.query("SELECT * FROM payment_executions WHERE execution_id=$1 AND payment_intent_id=$2 AND actor_subject=$3 FOR UPDATE",[input.executionId,input.paymentIntentId,input.actorSubject]);const row=result.rows[0];if(!row)throw new Error("Devnet execution ownership mismatch.");if(row.execution_mode!=="devnet_validation"||row.selected_rail!=="solana"||row.settlement_network!=="solana-devnet"||Buffer.from(row.policy_hash??[]).toString("hex")!==input.artifact.policyHash)throw new Error("Devnet execution policy does not match prepared artifact.");}
  private async assertReconciliationFence(client:PoolClient,executionId:string,fence:Parameters<DevnetExecutionStateRepository["recordReconciliationObservation"]>[0]["recoveryFence"]){if(!fence)throw new Error("Devnet reconciliation persistence requires recovery lease authority.");const result=await client.query("SELECT lease_owner,claimed_at=$2::timestamptz AS same_claim,lease_expires_at>clock_timestamp() AS active FROM devnet_recovery_leases WHERE execution_id=$1 AND task_kind='RECONCILIATION' FOR UPDATE",[executionId,fence.leaseClaimedAt]),row=result.rows[0];if(!row||row.active!==true||row.same_claim!==true||String(row.lease_owner)!==fence.leaseOwner)throw new Error("Devnet recovery lease fence is stale or unauthorized.");}
  private tx<T>(fn:(client:PoolClient)=>Promise<T>){return(async()=>{const client=await this.pool.connect();try{return await observeTransaction(this.pool,async()=>{try{await client.query("BEGIN");const value=await fn(client);await client.query("COMMIT");return value}catch(error){await client.query("ROLLBACK");throw error}});}finally{client.release();}})();}
}

const INSERT_PREPARATION=`INSERT INTO devnet_execution_preparations(preparation_id,execution_id,payment_intent_id,actor_subject,generation,encryption_algorithm,encryption_key_version,encryption_iv,encryption_auth_tag,signed_transaction_ciphertext,signed_transaction_digest,transaction_signature,source_token_account,mint_address,destination_address,amount_units,amount_decimals,recent_blockhash,last_valid_block_height,signer_key_id,signer_key_version,signer_public_key,policy_hash,submission_provider_id,reconciliation_provider_id,prepared_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,decode($11,'hex'),$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,decode($23,'hex'),$24,$25,$26)`;
function params(input:PersistDevnetPreparationInput){const e=input.encryptedSignedTransaction,a=input.artifact;return[input.preparationId,input.executionId,input.paymentIntentId,input.actorSubject,input.generation,e.algorithm,e.keyVersion,e.initializationVector,e.authenticationTag,e.ciphertext,a.signedTransactionDigest,a.signature,a.sourceTokenAccount,a.mint,a.destination,a.rawAmount,a.decimals,a.recentBlockhash,a.lastValidBlockHeight,a.signerKeyId,a.signerKeyVersion,a.signerPublicKey,a.policyHash,a.submissionProviderId,a.reconciliationProviderId,input.preparedAt];}
function mapPreparation(row:any):PersistedDevnetPreparation{return Object.freeze({preparationId:String(row.preparation_id),executionId:String(row.execution_id),paymentIntentId:String(row.payment_intent_id),actorSubject:String(row.actor_subject),generation:Number(row.generation),state:row.lifecycle_state,encryptedSignedTransaction:Object.freeze({algorithm:"aes-256-gcm",keyVersion:String(row.encryption_key_version),initializationVector:Buffer.from(row.encryption_iv),authenticationTag:Buffer.from(row.encryption_auth_tag),ciphertext:Buffer.from(row.signed_transaction_ciphertext)}),artifact:Object.freeze({signature:String(row.transaction_signature),signedTransactionDigest:Buffer.from(row.signed_transaction_digest).toString("hex"),cluster:"solana-devnet",mint:String(row.mint_address),rawAmount:String(row.amount_units),destination:String(row.destination_address),sourceTokenAccount:String(row.source_token_account),decimals:Number(row.amount_decimals),recentBlockhash:String(row.recent_blockhash),lastValidBlockHeight:String(row.last_valid_block_height),signerKeyId:String(row.signer_key_id),signerKeyVersion:String(row.signer_key_version),signerPublicKey:String(row.signer_public_key),policyHash:Buffer.from(row.policy_hash).toString("hex"),submissionProviderId:String(row.submission_provider_id),reconciliationProviderId:String(row.reconciliation_provider_id)}),preparedAt:isoRequired(row.prepared_at),abandonedAt:iso(row.abandoned_at),committedAt:iso(row.committed_at)});}
function mapCommitment(row:any){return Object.freeze({commitmentId:String(row.commitment_id),executionId:String(row.execution_id),preparationId:String(row.preparation_id),signature:String(row.transaction_signature),signedTransactionDigest:Buffer.from(row.signed_transaction_digest).toString("hex"),committedAt:isoRequired(row.committed_at)});}
function mapObservation(row:any){return Object.freeze({observationId:String(row.observation_id),executionId:String(row.execution_id),preparationId:String(row.preparation_id),sequence:Number(row.sequence_number),providerId:String(row.provider_id),...(row.transaction_signature===null?{}:{signature:String(row.transaction_signature)}),outcome:row.outcome,observedAt:isoRequired(row.observed_at),...(row.slot===null?{}:{slot:String(row.slot)}),...(row.confirmation_status===null?{}:{confirmationStatus:String(row.confirmation_status)}),...(row.error_code===null?{}:{errorCode:String(row.error_code)})});}
function sameObservation(prior:Readonly<{providerId:string;signature?:string;outcome:string;slot?:string;confirmationStatus?:string;errorCode?:string}>,next:Readonly<{providerId:string;signature:string;outcome:string;slot?:string;confirmationStatus?:string;errorCode?:string}>){return prior.providerId===next.providerId&&prior.signature===next.signature&&prior.outcome===next.outcome&&prior.slot===next.slot&&prior.confirmationStatus===next.confirmationStatus&&prior.errorCode===next.errorCode;}
function mapSubmissionObservation(row:any){return Object.freeze({observationId:String(row.observation_id),executionId:String(row.execution_id),preparationId:String(row.preparation_id),commitmentId:String(row.commitment_id),providerId:String(row.provider_id),signature:String(row.transaction_signature),outcome:row.outcome,contactCertainty:row.contact_certainty,observedAt:isoRequired(row.observed_at),...(row.provider_error_code===null?{}:{providerErrorCode:String(row.provider_error_code)}),...(row.slot===null?{}:{slot:String(row.slot)}),...(row.confirmation_status===null?{}:{confirmationStatus:String(row.confirmation_status)})});}
function iso(value:unknown){return value===null||value===undefined?undefined:new Date(String(value)).toISOString();}
function isoRequired(value:unknown){if(value===null||value===undefined)throw new Error("Required persisted timestamp is missing.");return new Date(String(value)).toISOString();}
