import assert from"node:assert/strict";
import{test}from"node:test";
import{DevnetRecoveryWorker}from"../src/devnet/devnetRecoveryWorker";
import type{DevnetRecoveryRecord}from"../src/devnet/devnetRecoveryRepository";
import type{PersistedDevnetPreparation}from"../src/devnet/devnetExecutionState";
import{InMemoryDevnetRecoveryRepository}from"../src/storage/memory/inMemoryDevnetRecoveryRepository";

const NOW="2026-08-13T12:00:00.000Z",INTENT="11111111-1111-4111-8111-111111111111",ACTOR="account:owner";
function preparation(executionId:string,state:PersistedDevnetPreparation["state"]):PersistedDevnetPreparation{return{preparationId:`prep-${executionId}`,executionId,paymentIntentId:INTENT,actorSubject:ACTOR,generation:1,state,encryptedSignedTransaction:{algorithm:"aes-256-gcm",keyVersion:"v1",initializationVector:Buffer.alloc(12),authenticationTag:Buffer.alloc(16),ciphertext:Buffer.from("x")},artifact:{signature:`sig-${executionId}`,signedTransactionDigest:"a".repeat(64),cluster:"solana-devnet",mint:"mint",rawAmount:"1",destination:"destination",sourceTokenAccount:"source",decimals:6,recentBlockhash:"blockhash",lastValidBlockHeight:"10",signerKeyId:"key",signerKeyVersion:"1",signerPublicKey:"public",policyHash:"b".repeat(64),submissionProviderId:"submit",reconciliationProviderId:"reconcile"},preparedAt:NOW,...(["SUBMISSION_COMMITTED_RECONCILE_ONLY","ACCEPTED_PENDING","UNKNOWN_RECONCILIATION_REQUIRED","SETTLED","FAILED"].includes(state)?{committedAt:NOW}:{})};}
function record(id:string,options:{state?:PersistedDevnetPreparation["state"];mode?:"mock_beta"|"devnet_validation";status?:DevnetRecoveryRecord["executionStatus"]}={}):DevnetRecoveryRecord{return{executionId:id,paymentIntentId:INTENT,actorSubject:ACTOR,providerIdempotencyKey:`key-${id}`,executionMode:options.mode??"devnet_validation",selectedRail:options.mode==="mock_beta"?"mock":"solana",settlementNetwork:options.mode==="mock_beta"?"simulated":"solana-devnet",executionStatus:options.status??"READY",...(options.state?{preparation:preparation(id,options.state)}:{})};}

test("candidate rules isolate initial/expired Devnet preparation and reconciliation without a submission kind",async()=>{const repo=new InMemoryDevnetRecoveryRepository();repo.add(record("01"));repo.add(record("03",{state:"SUBMISSION_COMMITTED_RECONCILE_ONLY"}));repo.add(record("04",{state:"ACCEPTED_PENDING"}));repo.add(record("05",{state:"UNKNOWN_RECONCILIATION_REQUIRED"}));repo.add(record("06",{state:"SETTLED",status:"SETTLED"}));repo.add(record("07",{state:"FAILED",status:"FAILED"}));repo.add(record("08",{mode:"mock_beta"}));assert.equal((await repo.claimPreparation("one",NOW,"2026-08-13T12:01:00.000Z","10"))?.executionId,"01");assert.equal((await repo.claimReconciliation("two",NOW,"2026-08-13T12:01:00.000Z"))?.executionId,"03");const prepared=new InMemoryDevnetRecoveryRepository();prepared.add(record("02",{state:"PREPARED_NOT_CONTACTED"}));assert.equal(await prepared.claimPreparation("valid",NOW,"2026-08-13T12:01:00.000Z","10"),undefined);assert.equal((await prepared.claimPreparation("expired",NOW,"2026-08-13T12:01:00.000Z","11"))?.executionId,"02");assert.deepEqual(Object.getOwnPropertyNames(Object.getPrototypeOf(repo)).filter(name=>/submi/i.test(name)),[]);});

test("lease exclusivity and expiry reclaim only operational work",async()=>{const repo=new InMemoryDevnetRecoveryRepository();repo.add(record("01",{state:"SUBMISSION_COMMITTED_RECONCILE_ONLY"}));assert(await repo.claimReconciliation("one",NOW,"2026-08-13T12:00:01.000Z"));assert.equal(await repo.claimReconciliation("two",NOW,"2026-08-13T12:00:02.000Z"),undefined);const reclaimed=await repo.claimReconciliation("two","2026-08-13T12:00:01.000Z","2026-08-13T12:00:02.000Z");assert.equal(reclaimed?.preparation?.state,"SUBMISSION_COMMITTED_RECONCILE_ONLY");assert.equal(await repo.claimPreparation("three","2026-08-13T12:00:01.000Z","2026-08-13T12:00:02.000Z","999"),undefined);});

test("worker gates phases independently and reconciliation polling backs off",async()=>{const repo=new InMemoryDevnetRecoveryRepository();repo.add(record("01"));repo.add(record("02",{state:"SUBMISSION_COMMITTED_RECONCILE_ONLY"}));let prepared=0,reconciled=0,submitted=0;const handlers={async currentBlockHeight(){return"10";},async prepare(){prepared++;return true;},async reconcile(){reconciled++;return true;}};const off=new DevnetRecoveryWorker(repo,handlers,"off",{},()=>NOW);assert.equal(await off.iterate(),false);const reconciliationOnly=new DevnetRecoveryWorker(repo,handlers,"reconcile",{reconciliationEnabled:true},()=>NOW);assert.equal(await reconciliationOnly.iterate(),false);assert.equal(reconciled,1);assert.equal(prepared,0);assert.equal(submitted,0);assert.deepEqual(Object.getOwnPropertyNames(Object.getPrototypeOf(reconciliationOnly)).filter(name=>/submi/i.test(name)),[]);});

test("concurrent workers cannot process one item and shutdown gates new claims",async()=>{const repo=new InMemoryDevnetRecoveryRepository();repo.add(record("01"));let entered=0,release!:()=>void;const handlers={async currentBlockHeight(){return"10";},prepare:async()=>{entered++;await new Promise<void>(resolve=>{release=resolve;});return true;},reconcile:async()=>false},a=new DevnetRecoveryWorker(repo,handlers,"a",{preparationEnabled:true},()=>NOW),b=new DevnetRecoveryWorker(repo,handlers,"b",{preparationEnabled:true},()=>NOW);const active=a.iterate();await new Promise<void>(resolve=>setImmediate(resolve));assert.equal(await b.iterate(),false);a.stop();release();assert.equal(await active,true);assert.equal(await a.iterate(),false);assert.equal(entered,1);});

test("active preparation drains and shutdown prevents starting reconciliation",async()=>{const repo=new InMemoryDevnetRecoveryRepository();repo.add(record("01"));repo.add(record("02",{state:"SUBMISSION_COMMITTED_RECONCILE_ONLY"}));let release!:()=>void,reconciled=0;const worker=new DevnetRecoveryWorker(repo,{async currentBlockHeight(){return"10";},prepare:()=>new Promise<boolean>(resolve=>{release=()=>resolve(true);}),async reconcile(){reconciled++;return true;}},"worker",{preparationEnabled:true,reconciliationEnabled:true},()=>NOW);const active=worker.iterate();await new Promise<void>(resolve=>setImmediate(resolve));worker.stop();release();assert.equal(await active,true);assert.equal(reconciled,0);});
