import assert from "node:assert/strict";
import { test } from "node:test";
import bs58 from "bs58";
import { Keypair, Transaction } from "@solana/web3.js";
import type { DevnetTransactionSigner, RailExecutionCommand, SolanaChainObservation } from "zephyon-protocol";
import { DevnetOrchestrationService, type DevnetReconciliationProvider } from "../src/devnet/devnetOrchestrationService";
import { Aes256GcmPreparedTransactionCipher } from "../src/devnet/preparedTransactionCipher";
import { InMemoryDevnetExecutionStateRepository } from "../src/storage/memory/inMemoryDevnetExecutionStateRepository";

const EXECUTION="22222222-2222-4222-8222-222222222222",INTENT="11111111-1111-4111-8111-111111111111",ACTOR="account:owner",NOW="2026-08-13T12:00:00.000Z";
const payer=Keypair.fromSeed(Buffer.alloc(32,1)),mint=Keypair.fromSeed(Buffer.alloc(32,2)).publicKey.toBase58(),source=Keypair.fromSeed(Buffer.alloc(32,3)).publicKey.toBase58(),destination=Keypair.fromSeed(Buffer.alloc(32,4)).publicKey.toBase58();
const blockhashes=[Keypair.fromSeed(Buffer.alloc(32,5)).publicKey.toBase58(),Keypair.fromSeed(Buffer.alloc(32,6)).publicKey.toBase58()];
const policy={cluster:"solana-devnet" as const,asset:"USDC",mint,decimals:6,sourceTokenAccount:source,policyHash:"a".repeat(64),submissionProviderId:"submission-rpc",reconciliationProviderId:"reconciliation-rpc"};
const signer:DevnetTransactionSigner={keyId:"test-signer",keyVersion:"1",publicKey:payer.publicKey.toBase58(),async signTransaction(bytes){const transaction=Transaction.from(bytes);transaction.partialSign(payer);return{signature:bs58.encode(transaction.signature!),signedTransactionBase64:transaction.serialize().toString("base64")};}};
const cipher=new Aes256GcmPreparedTransactionCipher(Buffer.alloc(32,7),"test-kms-v1",()=>Buffer.alloc(12,8));
const command={schemaVersion:1,requestId:"request:e2",correlationId:"payment:e2",executionId:EXECUTION,paymentIntentId:INTENT,transactionId:EXECUTION,requestedAt:NOW,actorId:"actor:owner",recipientId:"recipient:owner",amount:{asset:"USDC",units:"1000000",decimals:6},destination:{type:"wallet",network:"solana-devnet",address:destination},rail:"solana",providerIdempotencyKey:"provider:e2"} as RailExecutionCommand;
const identity=(generation=1)=>({preparationId:`33333333-3333-4333-8333-${String(generation).padStart(12,"0")}`,executionId:EXECUTION,paymentIntentId:INTENT,actorSubject:ACTOR,generation});

class FakeReconciliation implements DevnetReconciliationProvider{readonly identity={providerId:"reconciliation-rpc",network:"devnet" as const,role:"reconciliation" as const};signatures:string[]=[];constructor(public observation:SolanaChainObservation={status:"pending",observedAt:NOW,slot:"10",confirmationStatus:"processed"}){}async observeSignature(signature:string){this.signatures.push(signature);return this.observation;}}
function setup(options:{height?:string;enabled?:boolean;provider?:FakeReconciliation}={}){let block=0,id=0;const repo=new InMemoryDevnetExecutionStateRepository(),provider=options.provider??new FakeReconciliation(),service=new DevnetOrchestrationService(repo,cipher,policy,{async getLatestDevnetBlockhash(){const index=Math.min(block++,1);return{recentBlockhash:blockhashes[index],lastValidBlockHeight:"10"};}},signer,{async getCurrentDevnetBlockHeight(){return options.height??"5";}},provider,{reconciliationEnabled:options.enabled===true},()=>NOW,()=>`44444444-4444-4444-8444-${String(++id).padStart(12,"0")}`);return{repo,provider,service};}
async function committed(value=setup({enabled:true})){const prepared=await value.service.prepare(identity(),command);const commitment=await value.repo.commitSubmission({executionId:EXECUTION,actorSubject:ACTOR,preparationId:prepared.preparationId,commitmentId:"55555555-5555-4555-8555-555555555555",committedAt:NOW});return{...value,prepared,commitment};}

test("Runtime preparation persists and reconstructs exact authenticated signed bytes",async()=>{const{repo,service}=setup();const stored=await service.prepare(identity(),command),runtime=await service.loadRuntimePreparation(EXECUTION,ACTOR);assert(runtime);assert.equal(runtime.signedTransactionDigest,stored.artifact.signedTransactionDigest);assert.equal(runtime.signature,stored.artifact.signature);assert.equal(runtime.submissionProviderId,"submission-rpc");assert.equal(runtime.reconciliationProviderId,"reconciliation-rpc");assert.equal(cipher.decrypt(stored.encryptedSignedTransaction,{executionId:EXECUTION,preparationId:stored.preparationId,keyVersion:"test-kms-v1"}),runtime.signedTransactionBase64);assert.equal(await service.loadRuntimePreparation(EXECUTION,"account:other"),undefined);assert.equal((await repo.listPreparationEligible()).length,1);});

test("authenticated reconstruction fails closed for ciphertext or identity tampering",async()=>{const{repo,service}=setup();const stored=await service.prepare(identity(),command),original=repo.findPreparation.bind(repo);repo.findPreparation=async(...args)=>{const value=await original(...args);if(!value)return value;const ciphertext=Buffer.from(value.encryptedSignedTransaction.ciphertext);ciphertext[0]^=1;return{...value,encryptedSignedTransaction:{...value.encryptedSignedTransaction,ciphertext}};};await assert.rejects(()=>service.loadRuntimePreparation(EXECUTION,ACTOR));assert.throws(()=>cipher.decrypt(stored.encryptedSignedTransaction,{executionId:EXECUTION,preparationId:"other",keyVersion:"test-kms-v1"}));});

test("only an expired never-contacted preparation is atomically replaced",async()=>{const value=setup({height:"11"}),first=await value.service.prepare(identity(),command),second=await value.service.refreshExpiredPreContact(EXECUTION,ACTOR,identity(2).preparationId,command);assert.equal(second.generation,2);assert.notEqual(second.artifact.signature,first.artifact.signature);assert.equal(first.artifact.rawAmount,"1000000");await value.repo.commitSubmission({executionId:EXECUTION,actorSubject:ACTOR,preparationId:second.preparationId,commitmentId:"55555555-5555-4555-8555-555555555555",committedAt:NOW});await assert.rejects(()=>value.service.refreshExpiredPreContact(EXECUTION,ACTOR,identity(3).preparationId,command),/reconciliation-only/);});

test("reconciliation uses only persisted signature and records bounded monotonic provenance",async()=>{const value=await committed();const result=await value.service.reconcile(EXECUTION,ACTOR);assert.equal(result.attempted,true);assert.deepEqual(value.provider.signatures,[value.prepared.artifact.signature]);assert.equal(result.preparation.state,"ACCEPTED_PENDING");assert.equal(result.observation.providerId,"reconciliation-rpc");value.provider.observation={status:"missing",observedAt:NOW};assert.equal((await value.service.reconcile(EXECUTION,ACTOR)).preparation.state,"ACCEPTED_PENDING");value.provider.observation={status:"settled",observedAt:NOW,settledAt:NOW,slot:"11",confirmationStatus:"finalized"};const settled=await value.service.reconcile(EXECUTION,ACTOR);assert.equal(settled.preparation.state,"SETTLED");value.provider.observation={status:"pending",observedAt:NOW};await assert.rejects(()=>value.service.reconcile(EXECUTION,ACTOR),/Terminal/);assert.equal((await value.repo.listReconciliationObservations(EXECUTION,ACTOR)).length,3);assert.deepEqual(await value.repo.listReconciliationObservations(EXECUTION,"account:other"),[]);});

test("submission remains off by default while reconciliation is independently enabled or disabled",async()=>{const disabled=await committed(setup());assert.deepEqual(disabled.service.capabilities(),{submissionEnabled:false,reconciliationEnabled:false});assert.deepEqual(await disabled.service.reconcile(EXECUTION,ACTOR),{attempted:false,reason:"RECONCILIATION_DISABLED"});assert.equal(disabled.provider.signatures.length,0);assert.equal((await disabled.repo.findPreparation(EXECUTION,ACTOR))?.state,"SUBMISSION_COMMITTED_RECONCILE_ONLY");const enabled=await committed(setup({enabled:true}));assert.equal((await enabled.service.reconcile(EXECUTION,ACTOR)).attempted,true);assert.equal((await enabled.repo.commitSubmission({executionId:EXECUTION,actorSubject:ACTOR,preparationId:enabled.prepared.preparationId,commitmentId:"55555555-5555-4555-8555-555555555555",committedAt:NOW})).submissionAuthorized,false);});

test("provider failure becomes bounded unknown provenance without restoring submission authority",async()=>{const provider=new FakeReconciliation();provider.observeSignature=async(signature)=>{provider.signatures.push(signature);throw new Error("uncontrolled provider detail");};const value=await committed(setup({enabled:true,provider})),result=await value.service.reconcile(EXECUTION,ACTOR);assert.equal(result.preparation.state,"UNKNOWN_RECONCILIATION_REQUIRED");assert.equal(result.observation.outcome,"UNKNOWN");assert.equal("errorCode" in result.observation,false);assert.equal((await value.repo.commitSubmission({executionId:EXECUTION,actorSubject:ACTOR,preparationId:value.prepared.preparationId,commitmentId:"55555555-5555-4555-8555-555555555555",committedAt:NOW})).submissionAuthorized,false);});
