import assert from "node:assert/strict";
import { test } from "node:test";
import bs58 from "bs58";
import { Keypair, Transaction } from "@solana/web3.js";
import type { DevnetTransactionSigner, RailExecutionCommand, SolanaChainObservation, SolanaSubmissionRpc } from "zephyon-protocol";
import { DevnetOrchestrationService, type DevnetReconciliationProvider } from "../src/devnet/devnetOrchestrationService";
import { Aes256GcmPreparedTransactionCipher } from "../src/devnet/preparedTransactionCipher";
import { InMemoryDevnetExecutionStateRepository } from "../src/storage/memory/inMemoryDevnetExecutionStateRepository";

const EXECUTION="22222222-2222-4222-8222-222222222222",INTENT="11111111-1111-4111-8111-111111111111",ACTOR="account:owner",NOW="2026-08-13T12:00:00.000Z";
const payer=Keypair.fromSeed(Buffer.alloc(32,1)),mint=Keypair.fromSeed(Buffer.alloc(32,2)).publicKey.toBase58(),source=Keypair.fromSeed(Buffer.alloc(32,3)).publicKey.toBase58(),destination=Keypair.fromSeed(Buffer.alloc(32,4)).publicKey.toBase58();
const blockhashes=[Keypair.fromSeed(Buffer.alloc(32,5)).publicKey.toBase58(),Keypair.fromSeed(Buffer.alloc(32,6)).publicKey.toBase58()];
const policy={cluster:"solana-devnet" as const,asset:"USDC",mint,decimals:6,sourceTokenAccount:source,policyHash:"a".repeat(64),submissionProviderId:"submission-rpc",reconciliationProviderId:"reconciliation-rpc"};
const signer:DevnetTransactionSigner={keyId:"test-signer",keyVersion:"1",publicKey:payer.publicKey.toBase58(),async signTransaction(bytes){const transaction=Transaction.from(bytes);transaction.partialSign(payer);return{signature:bs58.encode(transaction.signature!),signedTransactionBase64:transaction.serialize().toString("base64")};}};
const cipher=new Aes256GcmPreparedTransactionCipher(Buffer.alloc(32,7),"test-kms-v1",()=>Buffer.alloc(12,8));
const command={schemaVersion:1,requestId:"request:e2",correlationId:"payment:e2",executionId:EXECUTION,paymentIntentId:INTENT,transactionId:EXECUTION,requestedAt:NOW,actorId:"actor:owner",recipientId:"recipient:owner",amount:{asset:"USDC",units:"1000000",decimals:6},destination:{type:"wallet",network:"solana-devnet",address:destination},rail:"solana",providerIdempotencyKey:"provider:e2"} as RailExecutionCommand;
const identity=(generation=1)=>({preparationId:`33333333-3333-4333-8333-${String(generation).padStart(12,"0")}`,executionId:EXECUTION,paymentIntentId:INTENT,actorSubject:ACTOR,generation});

class FakeReconciliation implements DevnetReconciliationProvider{readonly identity={providerId:"reconciliation-rpc",network:"devnet" as const,role:"reconciliation" as const};signatures:string[]=[];constructor(public observation:SolanaChainObservation={status:"pending",observedAt:NOW,slot:"10",confirmationStatus:"processed"}){}async observeSignature(signature:string){this.signatures.push(signature);return this.observation;}}
const unusedSubmission:SolanaSubmissionRpc={identity:{providerId:"submission-rpc",network:"devnet",role:"submission"},async submitExactSignedTransaction(){throw new Error("E2 must not submit");}};
function setup(options:{height?:string;enabled?:boolean;provider?:FakeReconciliation;submission?:SolanaSubmissionRpc;submissionEnabled?:boolean}={}){let block=0,id=0;const repo=new InMemoryDevnetExecutionStateRepository(),provider=options.provider??new FakeReconciliation(),submission=options.submission??unusedSubmission,service=new DevnetOrchestrationService(repo,cipher,policy,{async getLatestDevnetBlockhash(){const index=Math.min(block++,1);return{recentBlockhash:blockhashes[index],lastValidBlockHeight:"10"};}},signer,{async getCurrentDevnetBlockHeight(){return options.height??"5";}},provider,submission,{submissionEnabled:options.submissionEnabled===true,reconciliationEnabled:options.enabled===true},()=>NOW,()=>`44444444-4444-4444-8444-${String(++id).padStart(12,"0")}`);return{repo,provider,submission,service};}
async function committed(value=setup({enabled:true})){const prepared=await value.service.prepare(identity(),command);const commitment=await value.repo.commitSubmission({executionId:EXECUTION,actorSubject:ACTOR,preparationId:prepared.preparationId,commitmentId:"55555555-5555-4555-8555-555555555555",committedAt:NOW});return{...value,prepared,commitment};}

test("Runtime preparation persists and reconstructs exact authenticated signed bytes",async()=>{const{repo,service}=setup();const stored=await service.prepare(identity(),command),runtime=await service.loadRuntimePreparation(EXECUTION,ACTOR);assert(runtime);assert.equal(runtime.signedTransactionDigest,stored.artifact.signedTransactionDigest);assert.equal(runtime.signature,stored.artifact.signature);assert.equal(runtime.submissionProviderId,"submission-rpc");assert.equal(runtime.reconciliationProviderId,"reconciliation-rpc");assert.equal(cipher.decrypt(stored.encryptedSignedTransaction,{executionId:EXECUTION,preparationId:stored.preparationId,keyVersion:"test-kms-v1"}),runtime.signedTransactionBase64);assert.equal(await service.loadRuntimePreparation(EXECUTION,"account:other"),undefined);assert.equal((await repo.listPreparationEligible()).length,1);});

test("authenticated reconstruction fails closed for ciphertext or identity tampering",async()=>{const{repo,service}=setup();const stored=await service.prepare(identity(),command),original=repo.findPreparation.bind(repo);repo.findPreparation=async(...args)=>{const value=await original(...args);if(!value)return value;const ciphertext=Buffer.from(value.encryptedSignedTransaction.ciphertext);ciphertext[0]^=1;return{...value,encryptedSignedTransaction:{...value.encryptedSignedTransaction,ciphertext}};};await assert.rejects(()=>service.loadRuntimePreparation(EXECUTION,ACTOR));assert.throws(()=>cipher.decrypt(stored.encryptedSignedTransaction,{executionId:EXECUTION,preparationId:"other",keyVersion:"test-kms-v1"}));});

test("only an expired never-contacted preparation is atomically replaced",async()=>{const value=setup({height:"11"}),first=await value.service.prepare(identity(),command),second=await value.service.refreshExpiredPreContact(EXECUTION,ACTOR,identity(2).preparationId,command);assert.equal(second.generation,2);assert.notEqual(second.artifact.signature,first.artifact.signature);assert.equal(first.artifact.rawAmount,"1000000");await value.repo.commitSubmission({executionId:EXECUTION,actorSubject:ACTOR,preparationId:second.preparationId,commitmentId:"55555555-5555-4555-8555-555555555555",committedAt:NOW});await assert.rejects(()=>value.service.refreshExpiredPreContact(EXECUTION,ACTOR,identity(3).preparationId,command),/reconciliation-only/);});

test("reconciliation uses only persisted signature and records bounded monotonic provenance",async()=>{const value=await committed();const result=await value.service.reconcile(EXECUTION,ACTOR);assert.equal(result.attempted,true);assert.deepEqual(value.provider.signatures,[value.prepared.artifact.signature]);assert.equal(result.preparation.state,"ACCEPTED_PENDING");assert.equal(result.observation.providerId,"reconciliation-rpc");value.provider.observation={status:"missing",observedAt:NOW};assert.equal((await value.service.reconcile(EXECUTION,ACTOR)).preparation.state,"ACCEPTED_PENDING");value.provider.observation={status:"settled",observedAt:NOW,settledAt:NOW,slot:"11",confirmationStatus:"finalized"};const settled=await value.service.reconcile(EXECUTION,ACTOR);assert.equal(settled.preparation.state,"SETTLED");value.provider.observation={status:"pending",observedAt:NOW};await assert.rejects(()=>value.service.reconcile(EXECUTION,ACTOR),/Terminal/);assert.equal((await value.repo.listReconciliationObservations(EXECUTION,ACTOR)).length,3);assert.deepEqual(await value.repo.listReconciliationObservations(EXECUTION,"account:other"),[]);});

test("identical transient reconciliation evidence is not persisted repeatedly",async()=>{const value=await committed();const first=await value.service.reconcile(EXECUTION,ACTOR),second=await value.service.reconcile(EXECUTION,ACTOR);assert.equal(first.persisted,true);assert.equal(second.persisted,false);assert.equal(second.observation.observationId,first.observation.observationId);assert.equal((await value.repo.listReconciliationObservations(EXECUTION,ACTOR)).length,1);assert.equal(value.provider.signatures.length,2);});

test("submission remains off by default while reconciliation is independently enabled or disabled",async()=>{const disabled=await committed(setup());assert.deepEqual(disabled.service.capabilities(),{submissionEnabled:false,reconciliationEnabled:false});assert.deepEqual(await disabled.service.reconcile(EXECUTION,ACTOR),{attempted:false,reason:"RECONCILIATION_DISABLED"});assert.equal(disabled.provider.signatures.length,0);assert.equal((await disabled.repo.findPreparation(EXECUTION,ACTOR))?.state,"SUBMISSION_COMMITTED_RECONCILE_ONLY");const enabled=await committed(setup({enabled:true}));assert.equal((await enabled.service.reconcile(EXECUTION,ACTOR)).attempted,true);assert.equal((await enabled.repo.commitSubmission({executionId:EXECUTION,actorSubject:ACTOR,preparationId:enabled.prepared.preparationId,commitmentId:"55555555-5555-4555-8555-555555555555",committedAt:NOW})).submissionAuthorized,false);});

test("provider failure becomes categorized deduplicated unknown provenance without restoring submission authority",async()=>{const provider=new FakeReconciliation();provider.observeSignature=async(signature)=>{provider.signatures.push(signature);throw Object.assign(new Error("uncontrolled provider detail"),{code:"HTTP"});};const value=await committed(setup({enabled:true,provider})),result=await value.service.reconcile(EXECUTION,ACTOR),duplicate=await value.service.reconcile(EXECUTION,ACTOR);assert.equal(result.preparation.state,"UNKNOWN_RECONCILIATION_REQUIRED");assert.equal(result.observation.outcome,"UNKNOWN");assert.equal(result.observation.errorCode,"RPC_HTTP");assert.equal(duplicate.persisted,false);assert.equal((await value.repo.listReconciliationObservations(EXECUTION,ACTOR)).length,1);assert.equal((await value.repo.commitSubmission({executionId:EXECUTION,actorSubject:ACTOR,preparationId:value.prepared.preparationId,commitmentId:"55555555-5555-4555-8555-555555555555",committedAt:NOW})).submissionAuthorized,false);});

class FakeSubmission implements SolanaSubmissionRpc{readonly identity={providerId:"submission-rpc",network:"devnet" as const,role:"submission" as const};calls:Buffer[]=[];constructor(private readonly fail=false){}async submitExactSignedTransaction(bytes:Uint8Array){this.calls.push(Buffer.from(bytes));if(this.fail)throw new Error("response lost after provider boundary");const transaction=Transaction.from(bytes);return{signature:bs58.encode(transaction.signature!),acceptedAt:NOW};}}
const submitCommand={executionId:EXECUTION,actorSubject:ACTOR,commitmentId:"55555555-5555-4555-8555-555555555555",providerIdempotencyKey:"provider:e2"};

test("submission switch off stops before commitment and provider contact",async()=>{const submission=new FakeSubmission(),value=setup({submission});const prepared=await value.service.prepare(identity(),command);const result=await value.service.submitPrepared(submitCommand);assert.deepEqual({attempted:result.attempted,reason:result.reason},{attempted:false,reason:"SUBMISSION_DISABLED"});assert.equal(await value.repo.findCommitment(EXECUTION,ACTOR),undefined);assert.equal(submission.calls.length,0);assert.equal((await value.repo.commitSubmission({executionId:EXECUTION,actorSubject:ACTOR,preparationId:prepared.preparationId,commitmentId:submitCommand.commitmentId,committedAt:NOW})).submissionAuthorized,true);});

test("enabled submit durably commits then sends exact persisted bytes once",async()=>{const submission=new FakeSubmission(),value=setup({submission,submissionEnabled:true}),stored=await value.service.prepare(identity(),command),runtime=await value.service.loadRuntimePreparation(EXECUTION,ACTOR);assert(runtime);const result=await value.service.submitPrepared(submitCommand);assert.equal(result.attempted,true);assert.equal(result.preparation.state,"ACCEPTED_PENDING");assert.equal(submission.calls.length,1);assert.equal(value.provider.signatures.length,0);assert.deepEqual(submission.calls[0],Buffer.from(runtime.signedTransactionBase64,"base64"));assert.equal((await value.repo.findCommitment(EXECUTION,ACTOR))?.signature,stored.artifact.signature);assert.equal((await value.repo.listSubmissionObservations(EXECUTION,ACTOR))[0].outcome,"ACCEPTED");assert.equal("submissionAuthorized" in result,false);});

test("bounded conclusive rejection evidence is terminal and cannot restore eligibility",async()=>{const value=setup(),prepared=await value.service.prepare(identity(),command),commitmentId=submitCommand.commitmentId;await value.repo.commitSubmission({executionId:EXECUTION,actorSubject:ACTOR,preparationId:prepared.preparationId,commitmentId,committedAt:NOW});const rejected=await value.repo.recordSubmissionObservation({observationId:"66666666-6666-4666-8666-666666666666",executionId:EXECUTION,actorSubject:ACTOR,preparationId:prepared.preparationId,commitmentId,providerId:"submission-rpc",signature:prepared.artifact.signature,outcome:"REJECTED",contactCertainty:"MAY_HAVE_OCCURRED",observedAt:NOW,providerErrorCode:"CONCLUSIVE_REJECTION"});assert.equal(rejected.preparation.state,"FAILED");await assert.rejects(()=>value.repo.recordSubmissionObservation({observationId:"77777777-7777-4777-8777-777777777777",executionId:EXECUTION,actorSubject:ACTOR,preparationId:prepared.preparationId,commitmentId,providerId:"submission-rpc",signature:prepared.artifact.signature,outcome:"UNKNOWN",contactCertainty:"MAY_HAVE_OCCURRED",observedAt:NOW}),/Terminal/);assert.deepEqual(await value.repo.listPreparationEligible(),[]);});

test("concurrent, repeated, and restarted submits invoke provider at most once",async()=>{const submission=new FakeSubmission(),value=setup({submission,submissionEnabled:true});await value.service.prepare(identity(),command);const[a,b]=await Promise.all([value.service.submitPrepared(submitCommand),value.service.submitPrepared(submitCommand)]);assert.equal([a,b].filter(result=>result.attempted).length,1);assert.equal(submission.calls.length,1);assert.equal((await value.service.submitPrepared(submitCommand)).attempted,false);const restarted=value.service;assert.equal((await restarted.submitPrepared(submitCommand)).attempted,false);assert.equal(submission.calls.length,1);});

test("commit without an observation is independently sufficient to suppress restart submission",async()=>{const submission=new FakeSubmission(),value=setup({submission,submissionEnabled:true}),prepared=await value.service.prepare(identity(),command);assert.equal((await value.repo.commitSubmission({executionId:EXECUTION,actorSubject:ACTOR,preparationId:prepared.preparationId,commitmentId:submitCommand.commitmentId,committedAt:NOW})).submissionAuthorized,true);assert.deepEqual(await value.repo.listSubmissionObservations(EXECUTION,ACTOR),[]);assert.equal((await value.service.submitPrepared(submitCommand)).attempted,false);assert.equal(submission.calls.length,0);await assert.rejects(()=>value.service.refreshExpiredPreContact(EXECUTION,ACTOR,identity(2).preparationId,command),/reconciliation-only/);});

test("ambiguous provider boundary persists bounded evidence and can never resubmit",async()=>{const submission=new FakeSubmission(true),value=setup({submission,submissionEnabled:true});await value.service.prepare(identity(),command);const result=await value.service.submitPrepared(submitCommand);assert.equal(result.attempted,true);assert.equal(result.preparation.state,"UNKNOWN_RECONCILIATION_REQUIRED");assert.equal(result.observation.contactCertainty,"MAY_HAVE_OCCURRED");assert.equal(result.observation.providerErrorCode,"SUBMISSION_RESPONSE_UNAVAILABLE");assert.equal(submission.calls.length,1);assert.equal((await value.service.submitPrepared(submitCommand)).attempted,false);assert.equal(submission.calls.length,1);assert.deepEqual(await value.repo.listSubmissionObservations(EXECUTION,"account:other"),[]);});

test("post-commit validation failure records not-contacted evidence without reauthorization",async()=>{const submission=new FakeSubmission(),value=setup({submission,submissionEnabled:true});await value.service.prepare(identity(),command);const original=value.repo.commitSubmission.bind(value.repo);value.repo.commitSubmission=async(...args)=>{const result=await original(...args);if(!result.submissionAuthorized)return result;const ciphertext=Buffer.from(result.preparation.encryptedSignedTransaction.ciphertext);ciphertext[0]^=1;return{...result,preparation:{...result.preparation,encryptedSignedTransaction:{...result.preparation.encryptedSignedTransaction,ciphertext}}};};const result=await value.service.submitPrepared(submitCommand);assert.equal(result.attempted,false);assert.equal(result.reason,"VALIDATION_FAILED");assert.equal(result.observation.contactCertainty,"NOT_STARTED");assert.equal(submission.calls.length,0);assert.equal((await value.service.submitPrepared(submitCommand)).reason,"RECONCILIATION_ONLY");});

test("crash after provider invocation before evidence persistence cannot resubmit",async()=>{const submission=new FakeSubmission(),value=setup({submission,submissionEnabled:true});await value.service.prepare(identity(),command);value.repo.recordSubmissionObservation=async()=>{throw new Error("simulated process loss before evidence commit");};await assert.rejects(()=>value.service.submitPrepared(submitCommand),/simulated process loss/);assert.equal(submission.calls.length,1);assert.deepEqual(await value.repo.listSubmissionObservations(EXECUTION,ACTOR),[]);assert.equal((await value.service.submitPrepared(submitCommand)).attempted,false);assert.equal(submission.calls.length,1);});

test("another actor cannot commit, decrypt, submit, or read evidence",async()=>{const submission=new FakeSubmission(),value=setup({submission,submissionEnabled:true});await value.service.prepare(identity(),command);await assert.rejects(()=>value.service.submitPrepared({...submitCommand,actorSubject:"account:other"}),/not found/);assert.equal(await value.service.loadRuntimePreparation(EXECUTION,"account:other"),undefined);assert.deepEqual(await value.repo.listSubmissionObservations(EXECUTION,"account:other"),[]);assert.equal(submission.calls.length,0);});
