import assert from "node:assert/strict";
import { test } from "node:test";
import { Aes256GcmPreparedTransactionCipher } from "../src/devnet/preparedTransactionCipher";
import type { PersistDevnetPreparationInput } from "../src/devnet/devnetExecutionState";
import { InMemoryDevnetExecutionStateRepository } from "../src/storage/memory/inMemoryDevnetExecutionStateRepository";

const NOW="2026-08-13T12:00:00.000Z",EXECUTION="22222222-2222-4222-8222-222222222222",INTENT="11111111-1111-4111-8111-111111111111",ACTOR="account:owner";
const cipher=new Aes256GcmPreparedTransactionCipher(Buffer.alloc(32,7),"kms-v1",()=>Buffer.alloc(12,3));
function input(generation=1,overrides:Record<string,unknown>={}):PersistDevnetPreparationInput{const preparationId=`33333333-3333-4333-8333-${String(generation).padStart(12,"0")}`,base64=Buffer.from(`signed-${generation}`).toString("base64");return{preparationId,executionId:EXECUTION,paymentIntentId:INTENT,actorSubject:ACTOR,generation,encryptedSignedTransaction:cipher.encrypt(base64,{executionId:EXECUTION,preparationId,keyVersion:"kms-v1"}),artifact:{signature:`signature-${generation}`,signedTransactionDigest:String(generation).repeat(64).slice(0,64),cluster:"solana-devnet",mint:"mint",rawAmount:"1000000",destination:"destination",sourceTokenAccount:"source",decimals:6,recentBlockhash:`blockhash-${generation}`,lastValidBlockHeight:"100",signerKeyId:"signer",signerKeyVersion:"1",signerPublicKey:"public-key",policyHash:"a".repeat(64),submissionProviderId:"submit-rpc",reconciliationProviderId:"reconcile-rpc"},preparedAt:NOW,...overrides} as PersistDevnetPreparationInput;}

test("AES-256-GCM requires an injected key and binds ciphertext to immutable identity AAD",()=>{assert.throws(()=>new Aes256GcmPreparedTransactionCipher(Buffer.alloc(31),"v1"));const value=input();assert.equal(cipher.decrypt(value.encryptedSignedTransaction,{executionId:EXECUTION,preparationId:value.preparationId,keyVersion:"kms-v1"}),Buffer.from("signed-1").toString("base64"));assert.throws(()=>cipher.decrypt(value.encryptedSignedTransaction,{executionId:EXECUTION,preparationId:"other",keyVersion:"kms-v1"}));});

test("persists a complete immutable preparation with distinct provider evidence and owner isolation",async()=>{const repo=new InMemoryDevnetExecutionStateRepository(),original=input();const stored=await repo.persistPreparation(original);assert.equal(stored.artifact.rawAmount,"1000000");assert.equal(stored.state,"PREPARED_NOT_CONTACTED");(original.artifact as any).rawAmount="2";original.encryptedSignedTransaction.ciphertext[0]^=1;assert.equal((await repo.findPreparation(EXECUTION,ACTOR))?.artifact.rawAmount,"1000000");assert.equal(await repo.findPreparation(EXECUTION,"account:other"),undefined);for(const ids of [["","reconcile-rpc"],[" submit","reconcile-rpc"],["same","same"]])await assert.rejects(()=>repo.persistPreparation(input(2,{artifact:{...input(2).artifact,submissionProviderId:ids[0],reconciliationProviderId:ids[1]}})));});

test("durable commitment grants ephemeral submission ownership exactly once under concurrency",async()=>{const repo=new InMemoryDevnetExecutionStateRepository(),prepared=await repo.persistPreparation(input());const command={executionId:EXECUTION,actorSubject:ACTOR,preparationId:prepared.preparationId,commitmentId:"44444444-4444-4444-8444-444444444444",committedAt:NOW};const [a,b]=await Promise.all([repo.commitSubmission(command),repo.commitSubmission(command)]);assert.equal([a,b].filter(value=>value.submissionAuthorized).length,1);assert.equal(a.preparation.state,"SUBMISSION_COMMITTED_RECONCILE_ONLY");const replay=await repo.commitSubmission(command);assert.equal(replay.submissionAuthorized,false);assert.equal((await repo.listPreparationEligible()).length,0);assert.equal((await repo.listReconciliationEligible()).length,1);});

test("crash after durable commitment and ambiguous provider boundary remains reconciliation-only",async()=>{const durable=new InMemoryDevnetExecutionStateRepository(),prepared=await durable.persistPreparation(input());const command={executionId:EXECUTION,actorSubject:ACTOR,preparationId:prepared.preparationId,commitmentId:"44444444-4444-4444-8444-444444444444",committedAt:NOW};assert.equal((await durable.commitSubmission(command)).submissionAuthorized,true);const afterRestart=durable;assert.equal((await afterRestart.findPreparation(EXECUTION,ACTOR))?.state,"SUBMISSION_COMMITTED_RECONCILE_ONLY");assert.equal((await afterRestart.commitSubmission(command)).submissionAuthorized,false);assert.deepEqual(await afterRestart.listPreparationEligible(),[]);assert.equal((await afterRestart.listReconciliationEligible())[0].artifact.signature,"signature-1");const afterAmbiguousRestart=durable;assert.equal((await afterAmbiguousRestart.commitSubmission(command)).submissionAuthorized,false);});

test("only pre-contact expiry permits a next-generation replacement",async()=>{const repo=new InMemoryDevnetExecutionStateRepository(),first=await repo.persistPreparation(input());const second=await repo.replaceExpiredPreparation({priorPreparationId:first.preparationId,replacement:input(2),abandonedAt:NOW});assert.equal(second.generation,2);assert.equal((await repo.listPreparationEligible()).length,1);await repo.commitSubmission({executionId:EXECUTION,actorSubject:ACTOR,preparationId:second.preparationId,commitmentId:"44444444-4444-4444-8444-444444444444",committedAt:NOW});await assert.rejects(()=>repo.replaceExpiredPreparation({priorPreparationId:second.preparationId,replacement:input(3),abandonedAt:NOW}),/reconciliation-only/);});

test("duplicate signatures, digests, generations, and conflicting commitments fail closed",async()=>{const repo=new InMemoryDevnetExecutionStateRepository(),first=await repo.persistPreparation(input());await assert.rejects(()=>repo.persistPreparation(input(2,{artifact:{...input(2).artifact,signature:first.artifact.signature}})));await repo.commitSubmission({executionId:EXECUTION,actorSubject:ACTOR,preparationId:first.preparationId,commitmentId:"44444444-4444-4444-8444-444444444444",committedAt:NOW});await assert.rejects(()=>repo.commitSubmission({executionId:EXECUTION,actorSubject:ACTOR,preparationId:first.preparationId,commitmentId:"55555555-5555-4555-8555-555555555555",committedAt:NOW}),/conflict/);});
