import assert from"node:assert/strict";import{readFile}from"node:fs/promises";import{spawnSync}from"node:child_process";import test from"node:test";import{Keypair}from"@solana/web3.js";import type{JsonRpcFetch}from"../src/adapters/solana/devnetJsonRpc";import{CIRCLE_SOLANA_DEVNET_USDC_MINT}from"../src/devnet/canonicalDevnetAsset";import{deriveDevnetAssociatedSourceTokenAccount}from"../src/devnet/devnetPreparationPolicy";import{runE6aReadOnlyValidation}from"../src/devnet/e6aReadOnlyValidation";
const signer=Keypair.fromSeed(Buffer.alloc(32,8)),publicKey=signer.publicKey.toBase58(),secret="test-only-helius-secret";
const env=()=>({DEVNET_INTEGRATION_ENABLED:"true",DEVNET_PREPARATION_ENABLED:"false",DEVNET_SUBMISSION_ENABLED:"false",DEVNET_RECONCILIATION_ENABLED:"true",DEVNET_SUBMISSION_PROVIDER_ID:"helius-devnet-read",DEVNET_SUBMISSION_RPC_URL:"https://devnet.helius-rpc.com/",DEVNET_SUBMISSION_API_KEY:secret,DEVNET_RECONCILIATION_PROVIDER_ID:"solana-public-devnet-read",DEVNET_RECONCILIATION_RPC_URL:"https://api.devnet.solana.com/",DEVNET_RPC_TIMEOUT_MS:"500",DEVNET_SIGNER_SECRET_KEY_BASE64:Buffer.from(signer.secretKey).toString("base64"),DEVNET_SIGNER_KEY_ID:"controlled-e6a",DEVNET_SIGNER_KEY_VERSION:"1",DEVNET_SIGNER_PUBLIC_KEY:publicKey,DEVNET_USDC_MINT:CIRCLE_SOLANA_DEVNET_USDC_MINT,DEVNET_MINT_DECIMALS:"6",DEVNET_SOURCE_TOKEN_ACCOUNT:deriveDevnetAssociatedSourceTokenAccount(CIRCLE_SOLANA_DEVNET_USDC_MINT,publicKey)});
const ok=(result:unknown)=>({ok:true,async text(){return JSON.stringify({jsonrpc:"2.0",result});}});
function fake(methods:string[]):JsonRpcFetch{return async(url,init)=>{const body=JSON.parse(init.body),method=String(body.method);methods.push(`${new URL(url).hostname}:${method}`);assert(["getVersion","getLatestBlockhash","getBlockHeight"].includes(method));if(method==="getVersion")return ok({"solana-core":new URL(url).hostname.includes("helius")?"helius-test":"public-test"});if(method==="getLatestBlockhash")return ok({value:{blockhash:CIRCLE_SOLANA_DEVNET_USDC_MINT,lastValidBlockHeight:120}});return ok(100);};}
test("E6A performs exactly four allowlisted reads and passes offline signer validation",async()=>{const methods:string[]=[],result=await runE6aReadOnlyValidation(env(),fake(methods));assert.equal(result.verdict,"PASS");assert.deepEqual(result.methods,["getVersion","getVersion","getLatestBlockhash","getBlockHeight"]);assert.deepEqual(methods,["devnet.helius-rpc.com:getVersion","api.devnet.solana.com:getVersion","api.devnet.solana.com:getLatestBlockhash","api.devnet.solana.com:getBlockHeight"]);assert.equal(result.sendTransactionCalls,0);assert.equal(result.currentBlockHeight,"100");assert.equal(result.lastValidBlockHeight,"120");assert.notEqual(result.submissionProviderId,result.reconciliationProviderId);assert.equal(JSON.stringify(result).includes(secret),false);});
test("missing signer is BLOCKED and mismatched signer fails before network",async()=>{let calls=0;const request:JsonRpcFetch=async()=>{calls++;throw new Error("must not call")},missing={...env(),DEVNET_SIGNER_SECRET_KEY_BASE64:undefined},mismatch={...env(),DEVNET_SIGNER_PUBLIC_KEY:Keypair.fromSeed(Buffer.alloc(32,9)).publicKey.toBase58()};assert.equal((await runE6aReadOnlyValidation(missing,request)).verdict,"BLOCKED");assert.equal((await runE6aReadOnlyValidation(mismatch,request)).verdict,"FAIL");assert.equal(calls,0);});
test("provider failures are sanitized and Mainnet configuration is rejected",async()=>{const failing:JsonRpcFetch=async()=>{throw new Error(`provider leaked ${secret}`)},failed=await runE6aReadOnlyValidation(env(),failing);assert.equal(failed.verdict,"FAIL");assert.equal(failed.errorCategory,"TIMEOUT_OR_NETWORK");assert.equal(JSON.stringify(failed).includes(secret),false);let calls=0;const mainnet=await runE6aReadOnlyValidation({...env(),DEVNET_RECONCILIATION_RPC_URL:"https://api.mainnet-beta.solana.com/"},async()=>{calls++;return ok({})});assert.equal(mainnet.verdict,"FAIL");assert.equal(calls,0);});
test("harness source has no submission construction or sendTransaction invocation",async()=>{const source=await readFile(new URL("../src/devnet/e6aReadOnlyValidation.ts",import.meta.url),"utf8");assert.equal(source.includes("DevnetOrchestrationService"),false);assert.equal(source.includes("HeliusDevnetSubmissionRpc"),false);assert.equal(/\.call\(["']sendTransaction["']/.test(source),false);assert.equal(source.includes("commitSubmission"),false);assert.equal(source.includes("submitPrepared"),false);});
test("E6A CommonJS CLI entrypoint executes and blocks offline",()=>{const cli=new URL("../node_modules/tsx/dist/cli.mjs",import.meta.url),script=new URL("../scripts/validate-e6a-read-only.ts",import.meta.url),result=spawnSync(process.execPath,[cli.pathname,script.pathname],{cwd:new URL("..",import.meta.url),encoding:"utf8",env:{PATH:process.env.PATH??"",DOTENV_CONFIG_PATH:"/tmp/zephipay-e6a-regression-intentionally-absent",DEVNET_INTEGRATION_ENABLED:"false",DEVNET_PREPARATION_ENABLED:"false",DEVNET_SUBMISSION_ENABLED:"false",DEVNET_RECONCILIATION_ENABLED:"false"}});assert.equal(result.status,1);assert.match(result.stdout,/"verdict": "BLOCKED"/);assert.match(result.stdout,/operator-only/);assert.equal(result.stderr.includes("Top-level await"),false);});
