import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { Keypair } from "@solana/web3.js";
import { CIRCLE_SOLANA_DEVNET_USDC_MINT } from "../src/devnet/canonicalDevnetAsset";
import { runE6bPreparationOnly, type E6bPreparationRequest } from "../src/devnet/e6bPreparationOnly";
import { parseE6bRefreshRequest, runE6bPreparationRefresh, type E6bRefreshRequest } from "../src/devnet/e6bPreparationRefresh";
import { parseDevnetLiveConfiguration } from "../src/devnet/devnetLiveConfiguration";
import { deriveDevnetAssociatedSourceTokenAccount, devnetPreparationPolicy, hashDevnetPolicy } from "../src/devnet/devnetPreparationPolicy";
import { InMemoryDevnetExecutionStateRepository } from "../src/storage/memory/inMemoryDevnetExecutionStateRepository";
import type { JsonRpcFetch } from "../src/adapters/solana/devnetJsonRpc";

const signer=Keypair.fromSeed(Buffer.alloc(32,41)),destination=Keypair.fromSeed(Buffer.alloc(32,42)).publicKey.toBase58(),oldBlockhash=Keypair.fromSeed(Buffer.alloc(32,43)).publicKey.toBase58(),newBlockhash=Keypair.fromSeed(Buffer.alloc(32,44)).publicKey.toBase58(),source=deriveDevnetAssociatedSourceTokenAccount(CIRCLE_SOLANA_DEVNET_USDC_MINT,signer.publicKey.toBase58()),key=Buffer.alloc(32,45),executionId="22222222-2222-4222-8222-222222222222",paymentId="11111111-1111-4111-8111-111111111111",priorId="33333333-3333-4333-8333-333333333333",replacementId="44444444-4444-4444-8444-444444444444",actor="account:e6b-refresh",providerKey="e6b-refresh-provider-key";
const policy=devnetPreparationPolicy({mint:CIRCLE_SOLANA_DEVNET_USDC_MINT,decimals:6,sourceTokenAccount:source,signerKeyId:"zephipay-devnet-execution",signerKeyVersion:"1",signerPublicKey:signer.publicKey.toBase58(),submissionProviderId:"helius-devnet-submit",reconciliationProviderId:"solana-public-devnet-reconcile"}),policyHash=hashDevnetPolicy(policy);
const env=()=>({DEVNET_INTEGRATION_ENABLED:"true",DEVNET_RECONCILIATION_ENABLED:"true",DEVNET_PREPARATION_ENABLED:"true",DEVNET_SUBMISSION_ENABLED:"false",DEVNET_SUBMISSION_PROVIDER_ID:"helius-devnet-submit",DEVNET_RECONCILIATION_PROVIDER_ID:"solana-public-devnet-reconcile",DEVNET_RECONCILIATION_RPC_URL:"https://api.devnet.solana.com/",DEVNET_PREPARATION_ENCRYPTION_KEY_BASE64:key.toString("base64"),DEVNET_PREPARATION_ENCRYPTION_KEY_VERSION:"refresh-test-v1",DEVNET_SIGNER_SECRET_KEY_BASE64:Buffer.from(signer.secretKey).toString("base64"),DEVNET_SIGNER_KEY_ID:"zephipay-devnet-execution",DEVNET_SIGNER_KEY_VERSION:"1",DEVNET_SIGNER_PUBLIC_KEY:signer.publicKey.toBase58(),DEVNET_USDC_MINT:CIRCLE_SOLANA_DEVNET_USDC_MINT,DEVNET_MINT_DECIMALS:"6",DEVNET_SOURCE_TOKEN_ACCOUNT:source});
function response(result:unknown){return{ok:true,async text(){return JSON.stringify({jsonrpc:"2.0",id:1,result});}};}
async function fixture(height=101){const repository=new InMemoryDevnetExecutionStateRepository(),config=parseDevnetLiveConfiguration(env()),prepare:E6bPreparationRequest={config,executionId,paymentIntentId:paymentId,actorSubject:actor,preparationId:priorId,destination,rawAmount:"1000",expectedPolicyHash:policyHash},prior=await runE6bPreparationOnly(prepare,repository,async()=>response({value:{blockhash:oldBlockhash,lastValidBlockHeight:100}})),methods:string[]=[],fetch:JsonRpcFetch=async(_url,init)=>{const method=JSON.parse(init.body).method;methods.push(method);if(method==="getBlockHeight")return response(height);if(method==="getLatestBlockhash")return response({value:{blockhash:newBlockhash,lastValidBlockHeight:250}});throw new Error("unexpected RPC");},request:E6bRefreshRequest={config,databaseUrl:"postgresql://local@127.0.0.1:55432/test",actorSubject:actor,paymentIntentId:paymentId,executionId,existingPreparationId:priorId,existingGeneration:1,replacementPreparationId:replacementId,expectedPolicyHash:policyHash,destination,rawAmount:"1000"},loadExecution=async()=>({paymentIntentId:paymentId,actorSubject:actor,executionMode:"devnet_validation",rail:"solana",network:"solana-devnet",policyHash,providerIdempotencyKey:providerKey});return{repository,prior,request,fetch,methods,loadExecution};}

test("expired pre-contact preparation refreshes atomically to generation 2 with identical economics",async()=>{const f=await fixture(),result=await runE6bPreparationRefresh(f.request,{repository:f.repository,loadExecution:f.loadExecution,fetch:f.fetch}),active=await f.repository.findPreparation(executionId,actor);assert.equal(result.replacementGeneration,2);assert.equal(active?.preparationId,replacementId);assert.deepEqual(f.methods,["getBlockHeight","getLatestBlockhash"]);assert.deepEqual({mint:result.mint,source:result.sourceTokenAccount,destination:result.destination,amount:result.rawAmount,decimals:result.decimals,policy:result.canonicalPolicyHash,signer:result.signerPublicKey},{mint:CIRCLE_SOLANA_DEVNET_USDC_MINT,source,destination,amount:"1000",decimals:6,policy:policyHash,signer:signer.publicKey.toBase58()});assert.notEqual(result.recentBlockhash,oldBlockhash);assert.notEqual(result.signedTransactionDigest,f.prior.signedTransactionDigest);assert.notEqual(result.transactionSignature,f.prior.transactionSignature);assert.equal(await f.repository.findCommitment(executionId,actor),undefined);assert.equal(result.sendTransactionCalls,0);});
test("old generation cannot be submitted as current after replacement",async()=>{const f=await fixture();await runE6bPreparationRefresh(f.request,{repository:f.repository,loadExecution:f.loadExecution,fetch:f.fetch});await assert.rejects(()=>f.repository.commitSubmission({executionId,actorSubject:actor,preparationId:priorId,commitmentId:"55555555-5555-4555-8555-555555555555",committedAt:"2026-08-14T12:00:00.000Z"}),/never-contacted/);assert.equal(await f.repository.findCommitment(executionId,actor),undefined);});
test("concurrent refresh cannot create conflicting active preparations",async()=>{const f=await fixture(),other={...f.request,replacementPreparationId:"66666666-6666-4666-8666-666666666666"},results=await Promise.allSettled([runE6bPreparationRefresh(f.request,{repository:f.repository,loadExecution:f.loadExecution,fetch:f.fetch}),runE6bPreparationRefresh(other,{repository:f.repository,loadExecution:f.loadExecution,fetch:f.fetch})]);assert.equal(results.filter(x=>x.status==="fulfilled").length,1);assert.equal((await f.repository.listPreparationEligible()).length,1);assert.equal((await f.repository.findPreparation(executionId,actor))?.generation,2);assert.equal(await f.repository.findCommitment(executionId,actor),undefined);});
test("committed or still-valid preparation cannot refresh",async()=>{const committed=await fixture();await committed.repository.commitSubmission({executionId,actorSubject:actor,preparationId:priorId,commitmentId:"55555555-5555-4555-8555-555555555555",committedAt:"2026-08-14T12:00:00.000Z"});await assert.rejects(()=>runE6bPreparationRefresh(committed.request,{repository:committed.repository,loadExecution:committed.loadExecution,fetch:committed.fetch}),/submission boundary/);assert.deepEqual(committed.methods,[]);const valid=await fixture(100);await assert.rejects(()=>runE6bPreparationRefresh(valid.request,{repository:valid.repository,loadExecution:valid.loadExecution,fetch:valid.fetch}),/remains valid/);assert.deepEqual(valid.methods,["getBlockHeight"]);});
test("ownership, policy, economics, and encrypted-artifact mismatch fail before RPC",async()=>{for(const change of [{actorSubject:"account:other"},{expectedPolicyHash:"f".repeat(64)},{destination:signer.publicKey.toBase58()},{rawAmount:"999"}]){const f=await fixture();await assert.rejects(()=>runE6bPreparationRefresh({...f.request,...change},{repository:f.repository,loadExecution:f.loadExecution,fetch:f.fetch}));assert.deepEqual(f.methods,[]);assert.equal((await f.repository.findPreparation(executionId,actor))?.generation,1);}const tampered=await fixture(),stored=await tampered.repository.findPreparation(executionId,actor);assert(stored);const bytes=Buffer.from(stored.encryptedSignedTransaction.ciphertext);bytes[0]^=1;(tampered.repository as any).preparations.set(priorId,{...stored,encryptedSignedTransaction:{...stored.encryptedSignedTransaction,ciphertext:bytes}});await assert.rejects(()=>runE6bPreparationRefresh(tampered.request,{repository:tampered.repository,loadExecution:tampered.loadExecution,fetch:tampered.fetch}));assert.deepEqual(tampered.methods,[]);});
test("refresh parser is operator-only, submission-off, canonical, and loopback-only",()=>{const values={...env(),E6B_REFRESH_OPERATOR_CONFIRMATION:"REFRESH_EXPIRED_E6B_PREPARATION_PRE_CONTACT",E6B_REFRESH_DATABASE_URL:"postgresql://local@127.0.0.1:55432/test",E6B_REFRESH_ACTOR_SUBJECT:actor,E6B_REFRESH_PAYMENT_ID:paymentId,E6B_REFRESH_EXECUTION_ID:executionId,E6B_REFRESH_EXISTING_PREPARATION_ID:priorId,E6B_REFRESH_EXISTING_GENERATION:"1",E6B_REFRESH_REPLACEMENT_PREPARATION_ID:replacementId,E6B_REFRESH_EXPECTED_POLICY_HASH:policyHash,E6B_REFRESH_EXPECTED_DESTINATION:destination,E6B_REFRESH_EXPECTED_RAW_AMOUNT:"1000"};assert.equal(parseE6bRefreshRequest(values).replacementPreparationId,replacementId);for(const change of [{DEVNET_SUBMISSION_ENABLED:"true"},{E6B_REFRESH_OPERATOR_CONFIRMATION:"no"},{E6B_REFRESH_DATABASE_URL:"postgresql://remote.invalid/test"},{E6B_REFRESH_EXPECTED_RAW_AMOUNT:"1001"}])assert.throws(()=>parseE6bRefreshRequest({...values,...change}));});
test("refresh harness contains no submission, server, worker, retry, or Mainnet wiring",async()=>{const core=await readFile(new URL("../src/devnet/e6bPreparationRefresh.ts",import.meta.url),"utf8"),cli=await readFile(new URL("../scripts/refresh-e6b-preparation-only.ts",import.meta.url),"utf8"),combined=core+cli;for(const forbidden of ["submitPrepared(","commitSubmission(","HeliusDevnetSubmissionRpc","createLiveDevnetComposition","DevnetRecoveryWorker","Mainnet","server.ts"])assert.equal(combined.includes(forbidden),false);assert.equal(/\.call\(["']sendTransaction["']/.test(combined),false);assert.equal(/retry|while\s*\(|for\s*\(;;/.test(combined),false);});
