import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { Keypair } from "@solana/web3.js";
import { CIRCLE_SOLANA_DEVNET_USDC_MINT } from "../src/devnet/canonicalDevnetAsset";
import { parseE6cRequest, runE6cOperatorSubmission, type E6cRequest } from "../src/devnet/e6cOperatorSubmission";
import { runE6bPreparationOnly, type E6bPreparationRequest } from "../src/devnet/e6bPreparationOnly";
import { parseDevnetLiveConfiguration } from "../src/devnet/devnetLiveConfiguration";
import { deriveDevnetAssociatedSourceTokenAccount, devnetPreparationPolicy, hashDevnetPolicy } from "../src/devnet/devnetPreparationPolicy";
import { InMemoryDevnetExecutionStateRepository } from "../src/storage/memory/inMemoryDevnetExecutionStateRepository";
import type { JsonRpcFetch } from "../src/adapters/solana/devnetJsonRpc";

const signer=Keypair.fromSeed(Buffer.alloc(32,31)),destination=Keypair.fromSeed(Buffer.alloc(32,32)).publicKey.toBase58(),blockhash=Keypair.fromSeed(Buffer.alloc(32,33)).publicKey.toBase58(),source=deriveDevnetAssociatedSourceTokenAccount(CIRCLE_SOLANA_DEVNET_USDC_MINT,signer.publicKey.toBase58()),key=Buffer.alloc(32,34),executionId="22222222-2222-4222-8222-222222222222",paymentId="11111111-1111-4111-8111-111111111111",preparationId="33333333-3333-4333-8333-333333333333",actor="account:e6c-owner",commitmentId="44444444-4444-4444-8444-444444444444",providerKey="e6c:22222222-2222-4222-8222-222222222222";
const policy=devnetPreparationPolicy({mint:CIRCLE_SOLANA_DEVNET_USDC_MINT,decimals:6,sourceTokenAccount:source,signerKeyId:"zephipay-devnet-execution",signerKeyVersion:"1",signerPublicKey:signer.publicKey.toBase58(),submissionProviderId:"helius-devnet-submit",reconciliationProviderId:"solana-public-devnet-reconcile"}),policyHash=hashDevnetPolicy(policy);
const baseEnv=(submission:boolean)=>({DEVNET_INTEGRATION_ENABLED:"true",DEVNET_RECONCILIATION_ENABLED:"true",DEVNET_PREPARATION_ENABLED:"true",DEVNET_SUBMISSION_ENABLED:String(submission),DEVNET_SUBMISSION_PROVIDER_ID:"helius-devnet-submit",DEVNET_RECONCILIATION_PROVIDER_ID:"solana-public-devnet-reconcile",DEVNET_SUBMISSION_RPC_URL:"https://devnet.helius-rpc.com/",DEVNET_SUBMISSION_API_KEY:"test-secret-never-output",DEVNET_RECONCILIATION_RPC_URL:"https://api.devnet.solana.com/",DEVNET_PREPARATION_ENCRYPTION_KEY_BASE64:key.toString("base64"),DEVNET_PREPARATION_ENCRYPTION_KEY_VERSION:"e6c-test-v1",DEVNET_SIGNER_KEY_ID:"zephipay-devnet-execution",DEVNET_SIGNER_KEY_VERSION:"1",DEVNET_SIGNER_PUBLIC_KEY:signer.publicKey.toBase58(),DEVNET_USDC_MINT:CIRCLE_SOLANA_DEVNET_USDC_MINT,DEVNET_MINT_DECIMALS:"6",DEVNET_SOURCE_TOKEN_ACCOUNT:source});
function response(result:unknown){return{ok:true,async text(){return JSON.stringify({jsonrpc:"2.0",id:1,result});}};}
async function fixture(mode:"accepted"|"rejected"|"lost"="accepted",height=99){const repo=new InMemoryDevnetExecutionStateRepository(),prepFetch:JsonRpcFetch=async()=>response({value:{blockhash,lastValidBlockHeight:100}}),e6b:E6bPreparationRequest={config:{...parseDevnetLiveConfiguration(baseEnv(false)),signerSecretKey:Buffer.from(signer.secretKey)},executionId,paymentIntentId:paymentId,actorSubject:actor,preparationId,destination,rawAmount:"1000",expectedPolicyHash:policyHash},prepared=await runE6bPreparationOnly(e6b,repo,prepFetch),methods:string[]=[],submitted:string[]=[];
  const fetch:JsonRpcFetch=async(_url,init)=>{const body=JSON.parse(init.body),method=body.method;methods.push(method);if(method==="getBlockHeight")return response(height);if(method!=="sendTransaction")throw new Error("unexpected method");submitted.push(body.params[0]);if(mode==="lost")throw new Error("lost response");if(mode==="rejected")return{ok:true,async text(){return JSON.stringify({jsonrpc:"2.0",id:1,error:{code:-32002,message:"simulation failed",data:"secret must not escape"}});}};return response(prepared.transactionSignature);};
  const request:E6cRequest={config:parseDevnetLiveConfiguration(baseEnv(true)),databaseUrl:"postgresql://local@127.0.0.1:55432/test",actorSubject:actor,paymentIntentId:paymentId,executionId,preparationId,generation:1,policyHash,signedTransactionDigest:prepared.signedTransactionDigest,transactionSignature:prepared.transactionSignature,mint:CIRCLE_SOLANA_DEVNET_USDC_MINT,decimals:6,sourceTokenAccount:source,destination,rawAmount:"1000",commitmentId,providerIdempotencyKey:providerKey},loadExecutionContract=async()=>({paymentIntentId:paymentId,actorSubject:actor,executionMode:"devnet_validation",rail:"solana",network:"solana-devnet",policyHash,providerIdempotencyKey:providerKey});return{repo,request,fetch,methods,submitted,loadExecutionContract,prepared};}

test("E6C accepted path commits before one provider call and submits exact authenticated bytes",async()=>{const f=await fixture(),original=f.repo.commitSubmission.bind(f.repo),events:string[]=[];f.repo.commitSubmission=async input=>{const value=await original(input);events.push("commit");return value;};const fetch:JsonRpcFetch=async(a,b)=>{const method=JSON.parse(b.body).method;if(method==="sendTransaction")events.push("submit");return f.fetch(a,b);};const result=await runE6cOperatorSubmission(f.request,{repository:f.repo,loadExecutionContract:f.loadExecutionContract,fetch});assert.deepEqual(events,["commit","submit"]);assert.equal(result.typedSubmissionOutcome,"ACCEPTED");assert.equal(result.resultingDurableState,"ACCEPTED_PENDING");assert.equal(result.sendTransactionCalls,1);const runtime=await new (await import("../src/devnet/preparedTransactionCipher")).Aes256GcmPreparedTransactionCipher(key,"e6c-test-v1").decrypt((await f.repo.findPreparation(executionId,actor))!.encryptedSignedTransaction,{executionId,preparationId,keyVersion:"e6c-test-v1"});assert.equal(f.submitted[0],runtime);});
test("E6C conclusive JSON-RPC rejection is terminal with no retry",async()=>{const f=await fixture("rejected"),result=await runE6cOperatorSubmission(f.request,{repository:f.repo,loadExecutionContract:f.loadExecutionContract,fetch:f.fetch});assert.equal(result.typedSubmissionOutcome,"REJECTED");assert.equal(result.resultingDurableState,"FAILED");assert.equal(result.sendTransactionCalls,1);assert.deepEqual(f.methods,["getBlockHeight","sendTransaction"]);});
test("E6C lost response is unknown and reconciliation-only with no retry",async()=>{const f=await fixture("lost"),result=await runE6cOperatorSubmission(f.request,{repository:f.repo,loadExecutionContract:f.loadExecutionContract,fetch:f.fetch});assert.equal(result.typedSubmissionOutcome,"UNKNOWN_RECONCILIATION_REQUIRED");assert.equal(result.resultingDurableState,"UNKNOWN_RECONCILIATION_REQUIRED");assert.equal(result.sendTransactionCalls,1);assert.equal((await runE6cOperatorSubmission(f.request,{repository:f.repo,loadExecutionContract:f.loadExecutionContract,fetch:f.fetch})).sendTransactionCalls,0);});
test("E6C concurrent callers authorize and contact exactly once",async()=>{const f=await fixture(),results=await Promise.all([runE6cOperatorSubmission(f.request,{repository:f.repo,loadExecutionContract:f.loadExecutionContract,fetch:f.fetch}),runE6cOperatorSubmission(f.request,{repository:f.repo,loadExecutionContract:f.loadExecutionContract,fetch:f.fetch})]);assert.equal(results.filter(x=>x.verdict==="SUBMISSION_ATTEMPTED").length,1);assert.equal(f.methods.filter(x=>x==="sendTransaction").length,1);});
test("E6C existing/crash-window commitment never contacts provider",async()=>{const f=await fixture();await f.repo.commitSubmission({executionId,actorSubject:actor,preparationId,commitmentId,committedAt:"2026-08-14T12:00:00.000Z"});const result=await runE6cOperatorSubmission(f.request,{repository:f.repo,loadExecutionContract:f.loadExecutionContract,fetch:f.fetch});assert.equal(result.verdict,"RECONCILIATION_ONLY");assert.equal(result.sendTransactionCalls,0);assert.deepEqual(f.methods,[]);});
test("E6C expired preparation requires replacement before commitment",async()=>{const f=await fixture("accepted",101),result=await runE6cOperatorSubmission(f.request,{repository:f.repo,loadExecutionContract:f.loadExecutionContract,fetch:f.fetch});assert.equal(result.verdict,"PREPARATION_EXPIRED");assert.equal(result.sendTransactionCalls,0);assert.equal(await f.repo.findCommitment(executionId,actor),undefined);assert.deepEqual(f.methods,["getBlockHeight"]);});
test("E6C submission kill switch fails closed before commitment and contact",async()=>{const f=await fixture(),result=await runE6cOperatorSubmission({...f.request,config:{...f.request.config,submissionEnabled:false}},{repository:f.repo,loadExecutionContract:f.loadExecutionContract,fetch:f.fetch});assert.equal(result.providerStatus,"SUBMISSION_DISABLED");assert.equal(result.sendTransactionCalls,0);assert.equal(await f.repo.findCommitment(executionId,actor),undefined);assert.deepEqual(f.methods,[]);});
test("E6C expectation mismatches fail before commitment or provider contact",async()=>{for(const changed of [{generation:2},{policyHash:"f".repeat(64)},{signedTransactionDigest:"f".repeat(64)},{transactionSignature:"different"},{rawAmount:"999"},{destination:signer.publicKey.toBase58()}]){const f=await fixture();await assert.rejects(()=>runE6cOperatorSubmission({...f.request,...changed},{repository:f.repo,loadExecutionContract:f.loadExecutionContract,fetch:f.fetch}),/does not exactly match/);assert.equal(await f.repo.findCommitment(executionId,actor),undefined);assert.deepEqual(f.methods,[]);}});
test("E6C parser requires independent kill switches, exact confirmation, and loopback database",()=>{const env={...baseEnv(true),E6C_OPERATOR_CONFIRMATION:"SUBMIT_EXACT_E6C_DEVNET_TRANSACTION_ONCE",E6C_DATABASE_URL:"postgresql://local@127.0.0.1:55432/test",E6C_ACTOR_SUBJECT:actor,E6C_PAYMENT_ID:paymentId,E6C_EXECUTION_ID:executionId,E6C_PREPARATION_ID:preparationId,E6C_EXPECTED_PREPARATION_GENERATION:"1",E6C_EXPECTED_POLICY_HASH:policyHash,E6C_EXPECTED_SIGNED_TRANSACTION_DIGEST:"a".repeat(64),E6C_EXPECTED_TRANSACTION_SIGNATURE:"signature",E6C_EXPECTED_MINT:CIRCLE_SOLANA_DEVNET_USDC_MINT,E6C_EXPECTED_DECIMALS:"6",E6C_EXPECTED_SOURCE_ATA:source,E6C_EXPECTED_DESTINATION:destination,E6C_EXPECTED_RAW_AMOUNT:"1000",E6C_COMMITMENT_ID:commitmentId,E6C_PROVIDER_IDEMPOTENCY_KEY:providerKey};assert.equal(parseE6cRequest(env).executionId,executionId);for(const changed of [{DEVNET_SUBMISSION_ENABLED:"false"},{E6C_OPERATOR_CONFIRMATION:"no"},{E6C_DATABASE_URL:"postgresql://remote.example/test"}])assert.throws(()=>parseE6cRequest({...env,...changed}));});
test("E6C CLI is isolated from server, API, worker, recovery, signing, and retries",async()=>{const core=await readFile(new URL("../src/devnet/e6cOperatorSubmission.ts",import.meta.url),"utf8"),cli=await readFile(new URL("../scripts/submit-e6c-operator-only.ts",import.meta.url),"utf8"),combined=core+cli;for(const forbidden of ["server.ts","createLiveDevnetComposition","DevnetRecoveryWorker","refreshExpiredPreContact(","signTransactionBase64","Mainnet"])assert.equal(combined.includes(forbidden),false);assert.equal((combined.match(/\.submitPrepared\(/g)??[]).length,1);assert.equal(/retry|while\s*\(|for\s*\(;;/.test(combined),false);});
