import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { Keypair } from "@solana/web3.js";
import { CIRCLE_SOLANA_DEVNET_USDC_MINT } from "../src/devnet/canonicalDevnetAsset";
import { runE6bPreparationOnly, type E6bPreparationRequest } from "../src/devnet/e6bPreparationOnly";
import { parseE6FinalRequest, runE6FinalRefreshAndSubmit, type E6FinalRequest } from "../src/devnet/e6FinalRefreshAndSubmit";
import { parseDevnetLiveConfiguration } from "../src/devnet/devnetLiveConfiguration";
import { deriveDevnetAssociatedSourceTokenAccount, devnetPreparationPolicy, hashDevnetPolicy } from "../src/devnet/devnetPreparationPolicy";
import { Aes256GcmPreparedTransactionCipher } from "../src/devnet/preparedTransactionCipher";
import { InMemoryDevnetExecutionStateRepository } from "../src/storage/memory/inMemoryDevnetExecutionStateRepository";
import type { JsonRpcFetch } from "../src/adapters/solana/devnetJsonRpc";

const signer=Keypair.fromSeed(Buffer.alloc(32,51)),destination=Keypair.fromSeed(Buffer.alloc(32,52)).publicKey.toBase58(),oldBlockhash=Keypair.fromSeed(Buffer.alloc(32,53)).publicKey.toBase58(),newBlockhash=Keypair.fromSeed(Buffer.alloc(32,54)).publicKey.toBase58(),source=deriveDevnetAssociatedSourceTokenAccount(CIRCLE_SOLANA_DEVNET_USDC_MINT,signer.publicKey.toBase58()),key=Buffer.alloc(32,55),executionId="22222222-2222-4222-8222-222222222222",paymentId="11111111-1111-4111-8111-111111111111",priorId="33333333-3333-4333-8333-333333333333",replacementId="44444444-4444-4444-8444-444444444444",commitmentId="55555555-5555-4555-8555-555555555555",actor="account:e6-final",providerKey="e6-final-provider-key";
const policy=devnetPreparationPolicy({mint:CIRCLE_SOLANA_DEVNET_USDC_MINT,decimals:6,sourceTokenAccount:source,signerKeyId:"zephipay-devnet-execution",signerKeyVersion:"1",signerPublicKey:signer.publicKey.toBase58(),submissionProviderId:"helius-devnet-submit",reconciliationProviderId:"solana-public-devnet-reconcile"}),policyHash=hashDevnetPolicy(policy);
const env=(submission=true)=>({DEVNET_INTEGRATION_ENABLED:"true",DEVNET_RECONCILIATION_ENABLED:"true",DEVNET_PREPARATION_ENABLED:"true",DEVNET_SUBMISSION_ENABLED:String(submission),DEVNET_SUBMISSION_PROVIDER_ID:"helius-devnet-submit",DEVNET_RECONCILIATION_PROVIDER_ID:"solana-public-devnet-reconcile",DEVNET_SUBMISSION_RPC_URL:"https://devnet.helius-rpc.com/",DEVNET_SUBMISSION_API_KEY:"offline-test-value",DEVNET_RECONCILIATION_RPC_URL:"https://api.devnet.solana.com/",DEVNET_PREPARATION_ENCRYPTION_KEY_BASE64:key.toString("base64"),DEVNET_PREPARATION_ENCRYPTION_KEY_VERSION:"final-test-v1",DEVNET_SIGNER_SECRET_KEY_BASE64:Buffer.from(signer.secretKey).toString("base64"),DEVNET_SIGNER_KEY_ID:"zephipay-devnet-execution",DEVNET_SIGNER_KEY_VERSION:"1",DEVNET_SIGNER_PUBLIC_KEY:signer.publicKey.toBase58(),DEVNET_USDC_MINT:CIRCLE_SOLANA_DEVNET_USDC_MINT,DEVNET_MINT_DECIMALS:"6",DEVNET_SOURCE_TOKEN_ACCOUNT:source});
function response(result:unknown){return{ok:true,async text(){return JSON.stringify({jsonrpc:"2.0",id:1,result});}};}
async function fixture(mode:"accepted"|"rejected"|"lost"="accepted",height=101){const repository=new InMemoryDevnetExecutionStateRepository(),config=parseDevnetLiveConfiguration(env(false)),prepared=await runE6bPreparationOnly({config,executionId,paymentIntentId:paymentId,actorSubject:actor,preparationId:priorId,destination,rawAmount:"1000",expectedPolicyHash:policyHash}as E6bPreparationRequest,repository,async()=>response({value:{blockhash:oldBlockhash,lastValidBlockHeight:100}})),methods:string[]=[],submitted:string[]=[];const fetch:JsonRpcFetch=async(_url,init)=>{const body=JSON.parse(init.body),method=body.method;methods.push(method);if(method==="getBlockHeight")return response(height);if(method==="getLatestBlockhash")return response({value:{blockhash:newBlockhash,lastValidBlockHeight:250}});if(method!=="sendTransaction")throw new Error("unexpected RPC");submitted.push(body.params[0]);if(mode==="lost")throw new Error("lost response");if(mode==="rejected")return{ok:true,async text(){return JSON.stringify({jsonrpc:"2.0",id:1,error:{code:-32002,message:"rejected",data:"bounded"}});}};const active=await repository.findPreparation(executionId,actor);return response(active!.artifact.signature);},request:E6FinalRequest={config:parseDevnetLiveConfiguration(env(true)),databaseUrl:"postgresql://local@127.0.0.1:55432/test",actorSubject:actor,paymentIntentId:paymentId,executionId,currentPreparationId:priorId,currentGeneration:1,currentDigest:prepared.signedTransactionDigest,currentSignature:prepared.transactionSignature,replacementPreparationId:replacementId,commitmentId,expectedPolicyHash:policyHash,destination,rawAmount:"1000",expectedSignerPublicKey:signer.publicKey.toBase58(),expectedSignerKeyId:"zephipay-devnet-execution",expectedSignerKeyVersion:"1",expectedSourceTokenAccount:source,expectedMint:CIRCLE_SOLANA_DEVNET_USDC_MINT,expectedDecimals:6},loadExecution=async()=>({paymentIntentId:paymentId,actorSubject:actor,executionMode:"devnet_validation",rail:"solana",network:"solana-devnet",policyHash,providerIdempotencyKey:providerKey});return{repository,request,fetch,methods,submitted,loadExecution};}

test("expired preparation refreshes, commits, and submits exact persisted bytes once",async()=>{const f=await fixture(),events:string[]=[],original=f.repository.commitSubmission.bind(f.repository);f.repository.commitSubmission=async input=>{const value=await original(input);events.push("commit");return value;};const fetch:JsonRpcFetch=async(a,b)=>{if(JSON.parse(b.body).method==="sendTransaction")events.push("submit");return f.fetch(a,b);},result=await runE6FinalRefreshAndSubmit(f.request,{repository:f.repository,loadExecution:f.loadExecution,fetch});assert.equal(result.refreshed,true);assert.equal(result.newGeneration,2);assert.equal(result.typedSubmissionOutcome,"ACCEPTED");assert.equal(result.resultingDurableState,"ACCEPTED_PENDING");assert.equal(result.providerCallCount,1);assert.deepEqual(result.rpcMethods,["getBlockHeight","getLatestBlockhash","sendTransaction"]);assert.deepEqual(events,["commit","submit"]);const active=await f.repository.findPreparation(executionId,actor),base64=new Aes256GcmPreparedTransactionCipher(key,"final-test-v1").decrypt(active!.encryptedSignedTransaction,{executionId,preparationId:replacementId,keyVersion:"final-test-v1"});assert.equal(f.submitted[0],base64);});
test("accepted, conclusive rejection, and lost response have typed durable outcomes without retry",async()=>{for(const [mode,state,outcome]of [["accepted","ACCEPTED_PENDING","ACCEPTED"],["rejected","FAILED","REJECTED"],["lost","UNKNOWN_RECONCILIATION_REQUIRED","UNKNOWN_RECONCILIATION_REQUIRED"]]as const){const f=await fixture(mode),result=await runE6FinalRefreshAndSubmit(f.request,{repository:f.repository,loadExecution:f.loadExecution,fetch:f.fetch});assert.equal(result.resultingDurableState,state);assert.equal(result.typedSubmissionOutcome,outcome);assert.equal(result.providerCallCount,1);assert.equal(f.methods.filter(x=>x==="sendTransaction").length,1);}});
test("concurrent combined invocations produce one refresh winner and one provider call",async()=>{const f=await fixture(),other={...f.request,replacementPreparationId:"66666666-6666-4666-8666-666666666666",commitmentId:"77777777-7777-4777-8777-777777777777"},results=await Promise.allSettled([runE6FinalRefreshAndSubmit(f.request,{repository:f.repository,loadExecution:f.loadExecution,fetch:f.fetch}),runE6FinalRefreshAndSubmit(other,{repository:f.repository,loadExecution:f.loadExecution,fetch:f.fetch})]);assert.equal(results.filter(x=>x.status==="fulfilled"&&x.value.verdict==="SUBMISSION_ATTEMPTED").length,1);assert.equal(f.methods.filter(x=>x==="sendTransaction").length,1);assert.equal((await f.repository.findPreparation(executionId,actor))?.generation,2);});
test("crash after refresh leaves fresh preparation resumable",async()=>{const f=await fixture();await assert.rejects(()=>runE6FinalRefreshAndSubmit(f.request,{repository:f.repository,loadExecution:f.loadExecution,fetch:f.fetch,async afterRefresh(){throw new Error("simulated crash");}}),/simulated crash/);const active=await f.repository.findPreparation(executionId,actor);assert.equal(active?.generation,2);assert.equal(active?.state,"PREPARED_NOT_CONTACTED");assert.equal(await f.repository.findCommitment(executionId,actor),undefined);assert.equal(f.methods.includes("sendTransaction"),false);});
test("crash after commitment before provider and later invocation never resubmit",async()=>{const f=await fixture(),original=f.repository.commitSubmission.bind(f.repository);f.repository.commitSubmission=async input=>{await original(input);throw new Error("simulated crash after commit");};await assert.rejects(()=>runE6FinalRefreshAndSubmit(f.request,{repository:f.repository,loadExecution:f.loadExecution,fetch:f.fetch}),/simulated crash/);assert.equal(f.methods.includes("sendTransaction"),false);f.repository.commitSubmission=original;const active=await f.repository.findPreparation(executionId,actor),resumed={...f.request,currentPreparationId:active!.preparationId,currentGeneration:active!.generation,currentDigest:active!.artifact.signedTransactionDigest,currentSignature:active!.artifact.signature};const result=await runE6FinalRefreshAndSubmit(resumed,{repository:f.repository,loadExecution:f.loadExecution,fetch:f.fetch});assert.equal(result.verdict,"RECONCILIATION_ONLY");assert.equal(f.methods.includes("sendTransaction"),false);});
test("existing commitment short-circuits and valid preparation submits without refresh",async()=>{const committed=await fixture();await committed.repository.commitSubmission({executionId,actorSubject:actor,preparationId:priorId,commitmentId,committedAt:"2026-08-14T12:00:00.000Z"});assert.equal((await runE6FinalRefreshAndSubmit(committed.request,{repository:committed.repository,loadExecution:committed.loadExecution,fetch:committed.fetch})).verdict,"RECONCILIATION_ONLY");assert.deepEqual(committed.methods,[]);const valid=await fixture("accepted",100),result=await runE6FinalRefreshAndSubmit(valid.request,{repository:valid.repository,loadExecution:valid.loadExecution,fetch:valid.fetch});assert.equal(result.refreshed,false);assert.equal(result.newPreparationId,priorId);assert.deepEqual(result.rpcMethods,["getBlockHeight","sendTransaction"]);assert.equal(result.providerCallCount,1);});
test("mismatch or disabled submission fails before commitment and provider contact",async()=>{for(const change of [{actorSubject:"account:other"},{expectedPolicyHash:"f".repeat(64)},{currentDigest:"f".repeat(64)},{currentSignature:"different"},{rawAmount:"999"},{destination:signer.publicKey.toBase58()}]){const f=await fixture();await assert.rejects(()=>runE6FinalRefreshAndSubmit({...f.request,...change},{repository:f.repository,loadExecution:f.loadExecution,fetch:f.fetch}));assert.equal(await f.repository.findCommitment(executionId,actor),undefined);assert.deepEqual(f.methods,[]);}const disabled=await fixture();await assert.rejects(()=>runE6FinalRefreshAndSubmit({...disabled.request,config:{...disabled.request.config,submissionEnabled:false}},{repository:disabled.repository,loadExecution:disabled.loadExecution,fetch:disabled.fetch}),/disabled/);assert.equal(await disabled.repository.findCommitment(executionId,actor),undefined);assert.deepEqual(disabled.methods,[]);});
test("parser requires exact confirmation, explicit canonical values, new UUID, and loopback DB",()=>{const values={...env(true),E6_FINAL_OPERATOR_CONFIRMATION:"REFRESH_AND_SUBMIT_EXACT_DEVNET_TRANSACTION_ONCE",E6_FINAL_DATABASE_URL:"postgresql://local@127.0.0.1:55432/test",E6_FINAL_ACTOR_SUBJECT:actor,E6_FINAL_PAYMENT_ID:paymentId,E6_FINAL_EXECUTION_ID:executionId,E6_FINAL_CURRENT_PREPARATION_ID:priorId,E6_FINAL_CURRENT_GENERATION:"1",E6_FINAL_CURRENT_SIGNED_TRANSACTION_DIGEST:"a".repeat(64),E6_FINAL_CURRENT_TRANSACTION_SIGNATURE:"signature",E6_FINAL_REPLACEMENT_PREPARATION_ID:replacementId,E6_FINAL_COMMITMENT_ID:commitmentId,E6_FINAL_EXPECTED_POLICY_HASH:policyHash,E6_FINAL_EXPECTED_DESTINATION:destination,E6_FINAL_EXPECTED_RAW_AMOUNT:"1000",E6_FINAL_EXPECTED_SIGNER_PUBLIC_KEY:signer.publicKey.toBase58(),E6_FINAL_EXPECTED_SIGNER_KEY_ID:"zephipay-devnet-execution",E6_FINAL_EXPECTED_SIGNER_KEY_VERSION:"1",E6_FINAL_EXPECTED_SOURCE_ATA:source,E6_FINAL_EXPECTED_MINT:CIRCLE_SOLANA_DEVNET_USDC_MINT,E6_FINAL_EXPECTED_DECIMALS:"6"};assert.equal(parseE6FinalRequest(values).executionId,executionId);for(const change of [{E6_FINAL_OPERATOR_CONFIRMATION:"no"},{DEVNET_SUBMISSION_ENABLED:"false"},{E6_FINAL_REPLACEMENT_PREPARATION_ID:priorId},{E6_FINAL_DATABASE_URL:"postgresql://remote.invalid/test"}])assert.throws(()=>parseE6FinalRequest({...values,...change}));});
test("combined CLI remains isolated and has one submitPrepared call with no retry or reconciliation",async()=>{const core=await readFile(new URL("../src/devnet/e6FinalRefreshAndSubmit.ts",import.meta.url),"utf8"),cli=await readFile(new URL("../scripts/run-e6-final-refresh-and-submit.ts",import.meta.url),"utf8"),combined=core+cli;assert.equal((combined.match(/\.submitPrepared\(/g)??[]).length,1);for(const forbidden of ["createLiveDevnetComposition","DevnetRecoveryWorker","server.ts","Mainnet",".reconcile("])assert.equal(combined.includes(forbidden),false);assert.equal(/retry|while\s*\(|for\s*\(;;/.test(combined),false);});
