import assert from"node:assert/strict";import test from"node:test";import{Keypair}from"@solana/web3.js";
import{parseDevnetLiveConfiguration}from"../src/devnet/devnetLiveConfiguration";
import{DevnetRpcError,SingleAttemptDevnetJsonRpc,type JsonRpcFetch}from"../src/adapters/solana/devnetJsonRpc";
import{HeliusDevnetSubmissionRpc,IndependentDevnetReconciliationRpc,ReconciliationDevnetBlockDataSource}from"../src/adapters/solana/liveDevnetProviders";
import{createLiveDevnetComposition}from"../src/devnet/liveDevnetComposition";
import{InMemoryDevnetExecutionStateRepository}from"../src/storage/memory/inMemoryDevnetExecutionStateRepository";
import{InMemoryDevnetRecoveryRepository}from"../src/storage/memory/inMemoryDevnetRecoveryRepository";

const publicKey=Keypair.generate().publicKey.toBase58(),secret="super-secret-api-key",key=Buffer.alloc(32,7).toString("base64");
const base=()=>({DEVNET_INTEGRATION_ENABLED:"true",DEVNET_PREPARATION_ENABLED:"false",DEVNET_SUBMISSION_ENABLED:"false",DEVNET_RECONCILIATION_ENABLED:"true",DEVNET_SUBMISSION_PROVIDER_ID:"helius-devnet-submit",DEVNET_SUBMISSION_RPC_URL:"https://devnet.helius-rpc.com/",DEVNET_SUBMISSION_API_KEY:secret,DEVNET_RECONCILIATION_PROVIDER_ID:"solana-public-devnet-reconcile",DEVNET_RECONCILIATION_RPC_URL:"https://api.devnet.solana.com/",DEVNET_PREPARATION_ENCRYPTION_KEY_BASE64:key,DEVNET_PREPARATION_ENCRYPTION_KEY_VERSION:"v1",DEVNET_SIGNER_KEY_ID:"managed-signer",DEVNET_SIGNER_KEY_VERSION:"1",DEVNET_SIGNER_PUBLIC_KEY:publicKey,DEVNET_USDC_MINT:publicKey,DEVNET_MINT_DECIMALS:"6",DEVNET_SOURCE_TOKEN_ACCOUNT:publicKey,DEVNET_POLICY_HASH:"a".repeat(64),DEVNET_RPC_TIMEOUT_MS:"500"});
const response=(result:unknown)=>({ok:true,async text(){return JSON.stringify({jsonrpc:"2.0",result});}});

test("Devnet configuration defaults off and enabled configuration is fail-closed and secret-safe",()=>{assert.deepEqual(parseDevnetLiveConfiguration({}),{enabled:false,preparationEnabled:false,submissionEnabled:false,reconciliationEnabled:false});const valid=parseDevnetLiveConfiguration(base());assert.equal(valid.reconciliationEnabled,true);assert.equal(valid.submissionEnabled,false);assert.equal(parseDevnetLiveConfiguration({...base(),DEVNET_SUBMISSION_ENABLED:"true"}).submissionEnabled,true);for(const change of [{DEVNET_SUBMISSION_PROVIDER_ID:" "},{DEVNET_SUBMISSION_PROVIDER_ID:" padded "},{DEVNET_RECONCILIATION_PROVIDER_ID:"helius-devnet-submit"},{DEVNET_RECONCILIATION_RPC_URL:"https://devnet.helius-rpc.com/"},{DEVNET_RECONCILIATION_RPC_URL:"https://api.mainnet-beta.solana.com/?key="+secret},{DEVNET_SUBMISSION_RPC_URL:"https://user:"+secret+"@devnet.helius-rpc.com/"},{DEVNET_POLICY_HASH:secret}]){const env={...base(),...change};assert.throws(()=>parseDevnetLiveConfiguration(env),(error:unknown)=>error instanceof Error&&!error.message.includes(secret)&&!error.message.includes(key));}});

test("submission adapter sends exact bytes once with no retry and sanitizes ambiguous errors",async()=>{const bytes=Buffer.from([0,1,2,255]);let calls=0,body="",seenUrl="";const fetch:JsonRpcFetch=async(url,init)=>{calls++;seenUrl=url;body=init.body;return response("signature")};const provider=new HeliusDevnetSubmissionRpc("helius",new SingleAttemptDevnetJsonRpc("https://devnet.helius-rpc.com/",500,fetch,secret),()=>"2026-08-13T00:00:00.000Z");assert.equal((await provider.submitExactSignedTransaction(bytes)).signature,"signature");assert.equal(calls,1);assert.equal(JSON.parse(body).params[0],bytes.toString("base64"));assert.equal(JSON.parse(body).params[1].maxRetries,0);assert(seenUrl.includes(secret));let failures=0;const failing:JsonRpcFetch=async()=>{failures++;throw new Error(`leak ${secret} ${bytes.toString("base64")}`)};await assert.rejects(()=>new HeliusDevnetSubmissionRpc("helius",new SingleAttemptDevnetJsonRpc("https://devnet.helius-rpc.com/",500,failing,secret)).submitExactSignedTransaction(bytes),(error:unknown)=>error instanceof DevnetRpcError&&error.contactMayHaveOccurred&&!error.message.includes(secret)&&!error.message.includes(bytes.toString("base64")));assert.equal(failures,1);});

test("reconciliation uses signature only and exposes no submission method",async()=>{let requestBody="";const fetch:JsonRpcFetch=async(_url,init)=>{requestBody=init.body;return response({value:[{slot:9,confirmationStatus:"finalized",err:null}]})};const provider=new IndependentDevnetReconciliationRpc("public-devnet",new SingleAttemptDevnetJsonRpc("https://api.devnet.solana.com/",500,fetch),()=>"2026-08-13T00:00:00.000Z");assert.equal((await provider.observeSignature("persisted-signature")).status,"settled");assert.deepEqual(JSON.parse(requestBody).params,[["persisted-signature"],{searchTransactionHistory:true}]);assert.equal("submitExactSignedTransaction"in provider,false);});

test("block data is read-only and bound exclusively to reconciliation transport",async()=>{const submissionMethods:string[]=[],reconciliationMethods:string[]=[];const submitFetch:JsonRpcFetch=async(_url,init)=>{submissionMethods.push(JSON.parse(init.body).method);return response("unused")};const reconcileFetch:JsonRpcFetch=async(_url,init)=>{const method=JSON.parse(init.body).method;reconciliationMethods.push(method);return response(method==="getLatestBlockhash"?{value:{blockhash:"recent",lastValidBlockHeight:12}}:11)};const source=new ReconciliationDevnetBlockDataSource(new SingleAttemptDevnetJsonRpc("https://api.devnet.solana.com/",500,reconcileFetch));new HeliusDevnetSubmissionRpc("helius",new SingleAttemptDevnetJsonRpc("https://devnet.helius-rpc.com/",500,submitFetch));assert.equal((await source.getLatestDevnetBlockhash()).recentBlockhash,"recent");assert.equal(await source.getCurrentDevnetBlockHeight(),"11");assert.deepEqual(reconciliationMethods,["getLatestBlockhash","getBlockHeight"]);assert.deepEqual(submissionMethods,[]);});

test("composition is isolated, inert, supports reconciliation-only, and fails closed for signer preparation",()=>{const config=parseDevnetLiveConfiguration(base()),neverFetch:JsonRpcFetch=async()=>{throw new Error("construction must not contact network")},deps={executionState:new InMemoryDevnetExecutionStateRepository(),recoveryRepository:new InMemoryDevnetRecoveryRepository(),recoveryHandlers:{async currentBlockHeight(){return"1"},async prepare(){return false},async reconcile(){return false}},fetch:neverFetch,workerId:"e5-worker"};const composition=createLiveDevnetComposition(config,deps);assert.deepEqual(composition.orchestration.capabilities(),{submissionEnabled:false,reconciliationEnabled:true});assert.equal((composition.workerLoop as unknown as{stopped:boolean}).stopped,true);assert.equal("submitExactSignedTransaction"in composition.reconciliationProvider,false);assert.throws(()=>createLiveDevnetComposition({...config,preparationEnabled:true},deps),/injected server-side/);});
