import assert from "node:assert/strict";
import test from "node:test";
import type { MockRailScenario } from "zephyon-protocol";
import { InMemoryExecutionRepository } from "../src/storage/memory/inMemoryExecutionRepository";
import { PaymentExecutionWorker } from "../src/executions/executionWorker";
import { PaymentExecutionService } from "../src/executions/executionService";
import type { PaymentRecord } from "../src/payments/paymentTypes";
import { toPublicExecution } from "../src/executions/executionTypes";

const NOW="2026-08-07T12:00:00.000Z";
function payment(actor="auth0|owner"):PaymentRecord{return Object.freeze({id:"11111111-1111-4111-8111-111111111111",actorSubject:actor,idempotencyKey:"intent-key-123456",requestHash:"a".repeat(64),status:"PROCESSING",version:1n,network:"solana-devnet",rail:"solana",asset:"USDC",mintAddress:"mint",recipientAddress:"persisted-wallet",amountRaw:1250000n,purpose:"test",recipientType:"PAYMENT_IDENTITY",recipientAccountId:"account-recipient",recipientSnapshot:{accountId:"account-recipient",username:"recipient",displayName:"Recipient",accountType:"PERSONAL",verificationState:"VERIFIED",payabilityState:"AVAILABLE",capturedAt:NOW,schemaVersion:1,resolutionSource:"RECIPIENT_DIRECTORY",trustOutcome:"NOT_REQUIRED"},recipientSnapshotVersion:1,trustConfirmationOutcome:"NOT_REQUIRED",userConfirmedAt:NOW,executionStartedAt:NOW,createdAt:NOW,updatedAt:NOW});}
function payments(p=payment()){return{findPayment:async(id:string)=>id===p.id?p:undefined,findAllowlistEntry:async(s:string)=>s===p.actorSubject?{actorSubject:s,enabled:true,addedAt:NOW}:undefined} as any;}
async function created(repo:InMemoryExecutionRepository,p=payment()){return(await repo.createOrGet({executionId:"22222222-2222-4222-8222-222222222222",paymentIntentId:p.id,actorSubject:p.actorSubject,providerIdempotencyKey:"b".repeat(64),now:NOW})).execution;}

test("execution creation is database-style idempotent under concurrency",async()=>{const repo=new InMemoryExecutionRepository();const input={executionId:"22222222-2222-4222-8222-222222222222",paymentIntentId:payment().id,actorSubject:payment().actorSubject,providerIdempotencyKey:"b".repeat(64),now:NOW};const [a,b]=await Promise.all([repo.createOrGet(input),repo.createOrGet({...input,executionId:"33333333-3333-4333-8333-333333333333"})]);assert.equal(a.execution.executionId,b.execution.executionId);assert.equal([a.created,b.created].filter(Boolean).length,1);});

test("execution service rejects client authority fields and cross-account reads",async()=>{const repo=new InMemoryExecutionRepository();const account={resolve:async(p:any)=>({account:{actorSubject:p.subject,accountId:"account-owner"}})} as any;const service=new PaymentExecutionService(account,payments(),repo,()=>NOW,()=>"22222222-2222-4222-8222-222222222222");const principal={subject:"auth0|owner"} as any;await assert.rejects(()=>service.execute(principal,payment().id,{requestHash:"a".repeat(64),expectedVersion:"1",rail:"solana"}),/unsupported/);const first=await service.execute(principal,payment().id,{requestHash:"a".repeat(64),expectedVersion:"1"});const replay=await service.execute(principal,payment().id,{requestHash:"a".repeat(64),expectedVersion:"1"});assert.equal(first.execution.executionId,replay.execution.executionId);await assert.rejects(()=>service.find({subject:"auth0|other"} as any,payment().id),/not found/i);});

for(const [scenario,afterSubmit,afterReconcile] of [["immediate_settled","PROCESSING","SETTLED"],["accepted_then_settled","PROCESSING","PROCESSING"],["rejected_pre_submission","FAILED","FAILED"],["unknown_then_settled","UNKNOWN","PROCESSING"],["unknown_then_failed","UNKNOWN","FAILED"],["persistent_pending","PROCESSING","PROCESSING"]] as const){test(`worker maps Mock ${scenario} conservatively`,async()=>{const repo=new InMemoryExecutionRepository();await created(repo);const worker=new PaymentExecutionWorker(payments(),repo,"worker-1",scenario as MockRailScenario,()=>NOW);const submitted=await worker.processNext();assert.equal(submitted?.status,afterSubmit);if(!["FAILED","SETTLED"].includes(afterSubmit)){const reconciled=await worker.reconcileNext();assert.equal(reconciled?.status,afterReconcile);assert.equal(reconciled?.observationSequence,1);}const value=await repo.findByPaymentIntent(payment().id);assert.equal(value?.providerIdempotencyKey,"b".repeat(64));});}

test("repeated reconciliation progresses from unknown to settled without resubmission",async()=>{const repo=new InMemoryExecutionRepository();await created(repo);const worker=new PaymentExecutionWorker(payments(),repo,"worker-1","unknown_then_settled",()=>NOW);await worker.processNext();assert.equal((await worker.reconcileNext())?.status,"PROCESSING");assert.equal((await worker.reconcileNext())?.status,"SETTLED");assert.equal((await repo.listAttempts("22222222-2222-4222-8222-222222222222")).filter(a=>a.operation==="SUBMIT").length,1);});

test("settlement creates one immutable Runtime receipt with exact amount and versioned Mock evidence",async()=>{const repo=new InMemoryExecutionRepository();await created(repo);const worker=new PaymentExecutionWorker(payments(),repo,"worker-1","immediate_settled",()=>NOW);await worker.processNext();await worker.reconcileNext();const receipt=await repo.findReceiptByPaymentIntent(payment().id);assert.ok(receipt);assert.equal(receipt.amountUnits,"1250000");assert.equal(receipt.amountDecimals,6);assert.equal(receipt.evidenceType,"mock.execution");assert.equal(receipt.evidenceVersion,1);assert.equal(receipt.recipientSnapshot?.username,"recipient");assert.doesNotThrow(()=>JSON.stringify(receipt));const second=await repo.findReceiptByPaymentIntent(payment().id);assert.equal(second?.receiptId,receipt.receiptId);assert.notEqual(second,receipt);});

test("receipt and activity projections are owner-private, snapshot-based, and evidence-safe",async()=>{const repo=new InMemoryExecutionRepository();await created(repo);const worker=new PaymentExecutionWorker(payments(),repo,"worker-1","immediate_settled",()=>NOW);await worker.processNext();await worker.reconcileNext();const account={resolve:async(p:any)=>({account:{actorSubject:p.subject,accountId:"account-owner"}})} as any;const persistence={...payments(),listPaymentsByActor:async(actor:string)=>actor===payment().actorSubject?[payment()]:[]} as any;const service=new PaymentExecutionService(account,persistence,repo,()=>NOW);const receipt=await service.receipt({subject:"auth0|owner"} as any,payment().id);assert.equal(receipt.recipient.type,"payment_identity");assert.equal(receipt.recipient.displayName,"Recipient");assert.equal("evidence" in receipt,false);assert.equal("actorSubject" in receipt,false);assert.equal(receipt.amountRaw,"1250000");const [item]=await service.activity({subject:"auth0|owner"} as any,20);assert.equal(item.status,"completed");assert.equal(item.receiptAvailable,true);assert.equal(item.recipient.username,"recipient");assert.deepEqual(await service.activity({subject:"auth0|other"} as any,20),[]);await assert.rejects(()=>service.receipt({subject:"auth0|other"} as any,payment().id),/not found/i);});

test("public execution mapping is stable and omits internal authority fields",()=>{const base={...(payment() as any),executionId:"e",paymentIntentId:"p",actorSubject:"secret",version:1n,selectedRail:"mock",runtimeContractVersion:1,adapterVersion:1,providerIdempotencyKey:"hidden",attemptCount:7,observationSequence:2,createdAt:NOW,updatedAt:NOW};const expected={READY:"ready",SUBMITTING:"processing",PROCESSING:"processing",UNKNOWN:"pending",SETTLED:"settled",FAILED:"failed",CANCELLED:"cancelled"} as const;for(const [internal,status] of Object.entries(expected)){const projection=toPublicExecution({...base,status:internal,settledAt:internal==="SETTLED"?NOW:undefined,failedAt:internal==="FAILED"?NOW:undefined,failureCode:internal==="FAILED"?"provider-secret":undefined} as any,internal==="SETTLED"?"receipt:e":undefined);assert.equal(projection.status,status);assert.equal("providerIdempotencyKey" in projection,false);assert.equal("leaseOwner" in projection,false);assert.equal("attemptCount" in projection,false);assert.equal(projection.receiptAvailable,internal==="SETTLED");if(internal==="UNKNOWN"){assert.equal(projection.reconciliationPending,true);assert.equal(projection.stillProcessing,true);}if(internal==="FAILED"){assert.equal(projection.failure?.code,"EXECUTION_FAILED");assert.equal(JSON.stringify(projection).includes("provider-secret"),false);}}});

test("abandoned lease is recoverable but active lease is exclusive",async()=>{const repo=new InMemoryExecutionRepository();await created(repo);const first=await repo.claim(["READY"],"one",NOW,"2026-08-07T12:01:00.000Z");assert.ok(first);assert.equal(await repo.claim(["SUBMITTING"],"two",NOW,"2026-08-07T12:02:00.000Z"),undefined);assert.ok(await repo.claim(["SUBMITTING"],"two","2026-08-07T12:01:01.000Z","2026-08-07T12:02:00.000Z"));});
