import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { after, beforeEach, test } from "node:test";
import { Pool } from "pg";
import { actorSubjectForAccount } from "../src/identity/identityTypes";
import { Aes256GcmPreparedTransactionCipher } from "../src/devnet/preparedTransactionCipher";
import type { PersistDevnetPreparationInput } from "../src/devnet/devnetExecutionState";
import { PostgresIdentityPersistence } from "../src/storage/postgres/postgresIdentityPersistence";
import { PostgresDevnetExecutionStateRepository } from "../src/storage/postgres/postgresDevnetExecutionStateRepository";
import { PostgresDevnetRecoveryRepository } from "../src/storage/postgres/postgresDevnetRecoveryRepository";

const url=process.env.TEST_DATABASE_URL?.trim();if(!url)throw new Error("TEST_DATABASE_URL is required.");
const pool=new Pool({connectionString:url,max:4}),repo=new PostgresDevnetExecutionStateRepository(pool),identities=new PostgresIdentityPersistence(pool),NOW="2026-08-13T12:00:00.000Z",ACCOUNT_ID="20000000-0000-4000-8000-000000000001",ACTOR=actorSubjectForAccount(ACCOUNT_ID),POLICY="a".repeat(64),cipher=new Aes256GcmPreparedTransactionCipher(Buffer.alloc(32,9),"test-v1",()=>Buffer.alloc(12,4));
const recovery=new PostgresDevnetRecoveryRepository(pool,repo);
let executionId:string,paymentIntentId:string;
beforeEach(async()=>{await pool.query("TRUNCATE devnet_submission_commitments,devnet_execution_preparations,payment_execution_receipts,payment_execution_events,payment_execution_attempts,payment_executions,payment_events,payment_receipts,payments,beta_allowlist,accounts RESTART IDENTITY CASCADE");await identities.createAccount({accountId:ACCOUNT_ID,createdAt:NOW});await pool.query("INSERT INTO beta_allowlist(actor_subject) VALUES($1)",[ACTOR]);paymentIntentId=randomUUID();executionId=randomUUID();await pool.query(`INSERT INTO payments(id,actor_subject,idempotency_key,request_hash,status,network,rail,asset,mint_address,recipient_address,amount_raw,purpose,user_confirmed_at,execution_started_at) VALUES($1,$2,$3,decode($4,'hex'),'PROCESSING','solana-devnet','solana','USDC','mint','destination',1000000,'test',$5,$5)`,[paymentIntentId,ACTOR,`key-${randomUUID()}`,"b".repeat(64),NOW]);await pool.query(`INSERT INTO payment_executions(execution_id,payment_intent_id,actor_subject,status,selected_rail,execution_mode,settlement_network,policy_hash,provider_idempotency_key,created_at,updated_at) VALUES($1,$2,$3,'READY','solana','devnet_validation','solana-devnet',decode($4,'hex'),$5,$6,$6)`,[executionId,paymentIntentId,ACTOR,POLICY,"c".repeat(64),NOW]);});after(async()=>pool.end());
function prepared(generation=1):PersistDevnetPreparationInput{const preparationId=randomUUID(),base64=Buffer.from(`signed-${generation}`).toString("base64");return{preparationId,executionId,paymentIntentId,actorSubject:ACTOR,generation,encryptedSignedTransaction:cipher.encrypt(base64,{executionId,preparationId,keyVersion:"test-v1"}),artifact:{signature:`signature-${generation}-${executionId}`,signedTransactionDigest:generation.toString(16).repeat(64).slice(0,64),cluster:"solana-devnet",mint:"mint",rawAmount:"1000000",destination:"destination",sourceTokenAccount:"source",decimals:6,recentBlockhash:`blockhash-${generation}`,lastValidBlockHeight:"100",signerKeyId:"signer",signerKeyVersion:"1",signerPublicKey:"public",policyHash:POLICY,submissionProviderId:"submit-rpc",reconciliationProviderId:"reconcile-rpc"},preparedAt:NOW};}
async function claimFence(owner=`pg-state-${randomUUID()}`){const claimedAt=new Date().toISOString(),expiresAt=new Date(Date.parse(claimedAt)+10_000).toISOString(),candidate=await recovery.claimReconciliationExecution(executionId,owner,claimedAt,expiresAt);assert(candidate?.recoveryLease);return{leaseOwner:owner,leaseClaimedAt:candidate.recoveryLease.claimedAt};}

test("PostgreSQL persists immutable complete artifact and enforces owner and economic uniqueness",async()=>{const value=await repo.persistPreparation(prepared());assert.equal(value.artifact.sourceTokenAccount,"source");assert.equal(await repo.findPreparation(executionId,"other"),undefined);await assert.rejects(()=>pool.query("UPDATE devnet_execution_preparations SET amount_units=2 WHERE preparation_id=$1",[value.preparationId]));await assert.rejects(()=>repo.persistPreparation({...prepared(2),artifact:{...prepared(2).artifact,signature:value.artifact.signature}}));});

test("PostgreSQL commitment concurrency grants one ephemeral authorization and restart is reconciliation-only",async()=>{const value=await repo.persistPreparation(prepared()),command={executionId,actorSubject:ACTOR,preparationId:value.preparationId,commitmentId:randomUUID(),committedAt:NOW};const[a,b]=await Promise.all([repo.commitSubmission(command),repo.commitSubmission(command)]);assert.equal([a,b].filter(x=>x.submissionAuthorized).length,1);const restarted=new PostgresDevnetExecutionStateRepository(pool);assert.equal((await restarted.commitSubmission(command)).submissionAuthorized,false);assert.deepEqual(await restarted.listPreparationEligible(),[]);assert.equal((await restarted.listReconciliationEligible())[0].state,"SUBMISSION_COMMITTED_RECONCILE_ONLY");await assert.rejects(()=>pool.query("UPDATE devnet_submission_commitments SET committed_at=now() WHERE execution_id=$1",[executionId]));});

test("PostgreSQL permits replacement before commitment and forbids it afterward",async()=>{const first=await repo.persistPreparation(prepared()),secondInput=prepared(2),second=await repo.replaceExpiredPreparation({priorPreparationId:first.preparationId,replacement:secondInput,abandonedAt:NOW});assert.equal(second.generation,2);await repo.commitSubmission({executionId,actorSubject:ACTOR,preparationId:second.preparationId,commitmentId:randomUUID(),committedAt:NOW});await assert.rejects(()=>repo.replaceExpiredPreparation({priorPreparationId:second.preparationId,replacement:prepared(3),abandonedAt:NOW}),/reconciliation-only|never-contacted/);});

test("PostgreSQL concurrent replacement creates exactly one active next generation",async()=>{const first=await repo.persistPreparation(prepared()),[a,b]=await Promise.allSettled([repo.replaceExpiredPreparation({priorPreparationId:first.preparationId,replacement:prepared(2),abandonedAt:NOW}),repo.replaceExpiredPreparation({priorPreparationId:first.preparationId,replacement:prepared(2),abandonedAt:NOW})]);assert.equal([a,b].filter(value=>value.status==="fulfilled").length,1);const active=await repo.findPreparation(executionId,ACTOR);assert.equal(active?.generation,2);assert.equal((await repo.listPreparationEligible()).length,1);assert.equal(await repo.findCommitment(executionId,ACTOR),undefined);});

test("PostgreSQL reconciliation provenance is owner-scoped, append-only, terminal-monotonic, and replay-idempotent",async()=>{const value=await repo.persistPreparation(prepared()),signature=value.artifact.signature;await repo.commitSubmission({executionId,actorSubject:ACTOR,preparationId:value.preparationId,commitmentId:randomUUID(),committedAt:NOW});const recoveryFence=await claimFence(),pending=await repo.recordReconciliationObservation({observationId:randomUUID(),executionId,actorSubject:ACTOR,preparationId:value.preparationId,providerId:"reconcile-rpc",signature,outcome:"PENDING",observedAt:NOW,slot:"10",confirmationStatus:"processed",recoveryFence});assert.equal(pending.preparation.state,"ACCEPTED_PENDING");const unknown=await repo.recordReconciliationObservation({observationId:randomUUID(),executionId,actorSubject:ACTOR,preparationId:value.preparationId,providerId:"reconcile-rpc",signature,outcome:"UNKNOWN",observedAt:NOW,errorCode:"SIGNATURE_STATUS_MISSING",recoveryFence});assert.equal(unknown.preparation.state,"UNKNOWN_RECONCILIATION_REQUIRED");const settled=await repo.recordReconciliationObservation({observationId:randomUUID(),executionId,actorSubject:ACTOR,preparationId:value.preparationId,providerId:"reconcile-rpc",signature,outcome:"SETTLED",observedAt:NOW,slot:"11",confirmationStatus:"finalized",recoveryFence});assert.equal(settled.preparation.state,"SETTLED");const replay=await repo.recordReconciliationObservation({observationId:randomUUID(),executionId,actorSubject:ACTOR,preparationId:value.preparationId,providerId:"reconcile-rpc",signature,outcome:"PENDING",observedAt:NOW,recoveryFence});assert.equal(replay.preparation.state,"SETTLED");assert.equal(replay.observation.observationId,settled.observation.observationId);assert.equal((await repo.listReconciliationObservations(executionId,ACTOR)).length,3);assert.deepEqual(await repo.listReconciliationObservations(executionId,"other"),[]);await assert.rejects(()=>pool.query("UPDATE devnet_reconciliation_observations SET outcome='UNKNOWN' WHERE execution_id=$1",[executionId]));});

test("PostgreSQL concurrent finalized failure replay converges on one exact-signature terminal observation",async()=>{const value=await repo.persistPreparation(prepared()),command={executionId,actorSubject:ACTOR,preparationId:value.preparationId,commitmentId:randomUUID(),committedAt:NOW};await repo.commitSubmission(command);const recoveryFence=await claimFence(),input={executionId,actorSubject:ACTOR,preparationId:value.preparationId,providerId:"reconcile-rpc",signature:value.artifact.signature,outcome:"FAILED"as const,observedAt:NOW,slot:"201",confirmationStatus:"finalized",errorCode:"PROVIDER_REPORTED_FAILURE",recoveryFence};const[a,b]=await Promise.all([repo.recordReconciliationObservation({...input,observationId:randomUUID()}),repo.recordReconciliationObservation({...input,observationId:randomUUID()})]);assert.equal(a.preparation.state,"FAILED");assert.equal(b.preparation.state,"FAILED");const observations=await repo.listReconciliationObservations(executionId,ACTOR);assert.equal(observations.length,1);assert.equal(observations[0].signature,value.artifact.signature);assert.equal(observations[0].confirmationStatus,"finalized");assert.equal((await repo.commitSubmission(command)).submissionAuthorized,false);});

test("PostgreSQL rejects weak, mismatched, or non-finalized reconciliation failure while preserving UNKNOWN",async()=>{const value=await repo.persistPreparation(prepared()),signature=value.artifact.signature;await repo.commitSubmission({executionId,actorSubject:ACTOR,preparationId:value.preparationId,commitmentId:randomUUID(),committedAt:NOW});const recoveryFence=await claimFence(),base={executionId,actorSubject:ACTOR,preparationId:value.preparationId,providerId:"reconcile-rpc",signature,observedAt:NOW,recoveryFence};await repo.recordReconciliationObservation({...base,observationId:randomUUID(),outcome:"UNKNOWN",errorCode:"RPC_HTTP"});for(const invalid of[{confirmationStatus:"confirmed",slot:"201",errorCode:"PROVIDER_REPORTED_FAILURE"},{confirmationStatus:"finalized",errorCode:"PROVIDER_REPORTED_FAILURE"},{confirmationStatus:"finalized",slot:"201",errorCode:"OTHER_FAILURE"}])await assert.rejects(()=>repo.recordReconciliationObservation({...base,...invalid,observationId:randomUUID(),outcome:"FAILED"}),/finalized|terminal|evidence/);await assert.rejects(()=>repo.recordReconciliationObservation({...base,observationId:randomUUID(),signature:"wrong-signature",outcome:"FAILED",slot:"201",confirmationStatus:"finalized",errorCode:"PROVIDER_REPORTED_FAILURE"}),/does not match/);await assert.rejects(()=>repo.recordReconciliationObservation({...base,observationId:randomUUID(),providerId:"other-provider",outcome:"FAILED",slot:"201",confirmationStatus:"finalized",errorCode:"PROVIDER_REPORTED_FAILURE"}),/does not match/);await assert.rejects(()=>pool.query("UPDATE devnet_execution_preparations SET lifecycle_state='FAILED' WHERE preparation_id=$1",[value.preparationId]),/durable terminal evidence/);assert.equal((await repo.findPreparation(executionId,ACTOR))?.state,"UNKNOWN_RECONCILIATION_REQUIRED");});

test("migration 022 database guard requires exact finalized failed-chain relationships",async()=>{const value=await repo.persistPreparation(prepared()),signature=value.artifact.signature;await repo.commitSubmission({executionId,actorSubject:ACTOR,preparationId:value.preparationId,commitmentId:randomUUID(),committedAt:NOW});const insert=(change:Record<string,unknown>={})=>{const v={execution:executionId,preparation:value.preparationId,provider:"reconcile-rpc",signature,outcome:"FAILED",observed:NOW,confirmation:"finalized",slot:"201",error:"PROVIDER_REPORTED_FAILURE",...change};return pool.query("INSERT INTO devnet_reconciliation_observations(observation_id,execution_id,preparation_id,sequence_number,provider_id,transaction_signature,outcome,observed_at,slot,confirmation_status,error_code) VALUES($1,$2,$3,1,$4,$5,$6,$7,$8,$9,$10)",[randomUUID(),v.execution,v.preparation,v.provider,v.signature,v.outcome,v.observed,v.slot,v.confirmation,v.error]);};for(const change of[{signature:null},{slot:null},{confirmation:"processed"},{confirmation:"confirmed"},{confirmation:null},{provider:"other-provider"},{signature:"wrong-signature"},{preparation:randomUUID()},{execution:randomUUID()},{error:null},{error:""},{error:"OTHER_FAILURE"},{error:"X".repeat(65)},{observed:"2026-08-13T11:59:59.000Z"}])await assert.rejects(()=>insert(change));await assert.rejects(()=>pool.query("UPDATE devnet_execution_preparations SET submission_provider_id=reconciliation_provider_id WHERE preparation_id=$1",[value.preparationId]));const nullable=(await pool.query("SELECT is_nullable FROM information_schema.columns WHERE table_schema='public' AND table_name='devnet_reconciliation_observations' AND column_name='transaction_signature'")).rows[0];assert.equal(nullable.is_nullable,"YES");await insert();assert.equal((await pool.query("SELECT outcome FROM devnet_reconciliation_observations WHERE execution_id=$1",[executionId])).rows[0].outcome,"FAILED");});

test("historical NULL reconciliation signature maps to absent provenance",async()=>{const value=await repo.persistPreparation(prepared());await repo.commitSubmission({executionId,actorSubject:ACTOR,preparationId:value.preparationId,commitmentId:randomUUID(),committedAt:NOW});const client=await pool.connect();try{await client.query("BEGIN");await client.query("SET LOCAL session_replication_role = replica");await client.query("INSERT INTO devnet_reconciliation_observations(observation_id,execution_id,preparation_id,sequence_number,provider_id,transaction_signature,outcome,observed_at,slot,confirmation_status,error_code) VALUES($1,$2,$3,1,$4,NULL,'PENDING',$5,$6,'processed',NULL)",[randomUUID(),executionId,value.preparationId,"reconcile-rpc",NOW,"10"]);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error}finally{client.release();}const observations=await new PostgresDevnetExecutionStateRepository(pool).listReconciliationObservations(executionId,ACTOR);assert.equal(observations.length,1);assert.equal(observations[0].signature,undefined);assert.equal(Object.hasOwn(observations[0],"signature"),false);assert.equal(JSON.stringify(observations[0]).includes('"signature":"null"'),false);});

test("PostgreSQL submission evidence is append-only, owner-scoped, monotonic, and never authorizes submission",async()=>{const value=await repo.persistPreparation(prepared()),commitmentId=randomUUID(),command={executionId,actorSubject:ACTOR,preparationId:value.preparationId,commitmentId,committedAt:NOW};assert.equal((await repo.commitSubmission(command)).submissionAuthorized,true);assert.deepEqual(await repo.listSubmissionObservations(executionId,ACTOR),[]);assert.equal((await new PostgresDevnetExecutionStateRepository(pool).commitSubmission(command)).submissionAuthorized,false);const accepted=await repo.recordSubmissionObservation({observationId:randomUUID(),executionId,actorSubject:ACTOR,preparationId:value.preparationId,commitmentId,providerId:"submit-rpc",signature:value.artifact.signature,outcome:"ACCEPTED",contactCertainty:"ACCEPTED",observedAt:NOW});assert.equal(accepted.preparation.state,"ACCEPTED_PENDING");const stale=await repo.recordSubmissionObservation({observationId:randomUUID(),executionId,actorSubject:ACTOR,preparationId:value.preparationId,commitmentId,providerId:"submit-rpc",signature:value.artifact.signature,outcome:"UNKNOWN",contactCertainty:"MAY_HAVE_OCCURRED",observedAt:NOW});assert.equal(stale.preparation.state,"ACCEPTED_PENDING");assert.equal((await repo.commitSubmission(command)).submissionAuthorized,false);assert.deepEqual(await repo.listSubmissionObservations(executionId,"other"),[]);await assert.rejects(()=>pool.query("UPDATE devnet_submission_observations SET outcome='UNKNOWN' WHERE execution_id=$1",[executionId]));});

test("historical submission-side REJECTED compatibility remains readable and reconciliation-only",async()=>{const value=await repo.persistPreparation(prepared()),commitmentId=randomUUID(),command={executionId,actorSubject:ACTOR,preparationId:value.preparationId,commitmentId,committedAt:NOW};await repo.commitSubmission(command);const rejected=await repo.recordSubmissionObservation({observationId:randomUUID(),executionId,actorSubject:ACTOR,preparationId:value.preparationId,commitmentId,providerId:"submit-rpc",signature:value.artifact.signature,outcome:"REJECTED",contactCertainty:"MAY_HAVE_OCCURRED",observedAt:NOW,providerErrorCode:"CONCLUSIVE_REJECTION"}),read=await new PostgresDevnetExecutionStateRepository(pool).listSubmissionObservations(executionId,ACTOR);assert.equal(rejected.preparation.state,"FAILED");assert.equal(read.length,1);assert.equal(read[0].outcome,"REJECTED");assert.equal(read[0].providerErrorCode,"CONCLUSIVE_REJECTION");assert.equal((await repo.commitSubmission(command)).submissionAuthorized,false);});

test("PostgreSQL recovery leases select bounded exclusive phase work without economic mutation",async()=>{const before=(await pool.query("SELECT status,version FROM payment_executions WHERE execution_id=$1",[executionId])).rows[0],first=await recovery.claimPreparation("worker-a",NOW,"2026-08-13T12:00:01.000Z","10");assert.equal(first?.executionId,executionId);assert.equal(await recovery.claimPreparation("worker-b",NOW,"2026-08-13T12:00:02.000Z","10"),undefined);const reclaimed=await recovery.claimPreparation("worker-b","2026-08-13T12:00:01.000Z","2026-08-13T12:00:02.000Z","10");assert.equal(reclaimed?.executionId,executionId);const after=(await pool.query("SELECT status,version FROM payment_executions WHERE execution_id=$1",[executionId])).rows[0];assert.deepEqual(after,before);assert.equal(await repo.findCommitment(executionId,ACTOR),undefined);});

test("PostgreSQL preparation claim skips valid artifacts and selects them only after expiry",async()=>{const value=await repo.persistPreparation(prepared());assert.equal(await recovery.claimPreparation("valid",NOW,"2026-08-13T12:01:00.000Z","100"),undefined);const expired=await recovery.claimPreparation("expired",NOW,"2026-08-13T12:01:00.000Z","101");assert.equal(expired?.preparation?.preparationId,value.preparationId);assert.equal(expired?.actorSubject,ACTOR);});

test("PostgreSQL committed restart and lease expiry expose reconciliation only",async()=>{const value=await repo.persistPreparation(prepared()),command={executionId,actorSubject:ACTOR,preparationId:value.preparationId,commitmentId:randomUUID(),committedAt:NOW};await repo.commitSubmission(command);assert.equal(await recovery.claimPreparation("prepare",NOW,"2026-08-13T12:01:00.000Z","999"),undefined);assert.equal((await recovery.claimReconciliation("one",NOW,"2026-08-13T12:00:01.000Z"))?.preparation?.state,"SUBMISSION_COMMITTED_RECONCILE_ONLY");assert.equal(await recovery.claimReconciliation("two",NOW,"2026-08-13T12:00:02.000Z"),undefined);assert.equal((await recovery.claimReconciliation("two","2026-08-13T12:00:01.000Z","2026-08-13T12:00:02.000Z"))?.preparation?.state,"SUBMISSION_COMMITTED_RECONCILE_ONLY");assert.equal((await repo.commitSubmission(command)).submissionAuthorized,false);});

test("PostgreSQL lease renewal and reconciliation persistence require the current fence",async()=>{const value=await repo.persistPreparation(prepared()),command={executionId,actorSubject:ACTOR,preparationId:value.preparationId,commitmentId:randomUUID(),committedAt:NOW};await repo.commitSubmission(command);const claimedAt=new Date().toISOString(),expiresAt=new Date(Date.parse(claimedAt)+5_000).toISOString(),claim=await recovery.claimReconciliation("worker-a",claimedAt,expiresAt);assert(claim?.recoveryLease);const renewedAt=new Date().toISOString(),renewedUntil=new Date(Date.parse(renewedAt)+5_000).toISOString();assert.equal(await recovery.renew(executionId,"RECONCILIATION","worker-a",claim.recoveryLease.claimedAt,renewedAt,renewedUntil),true);assert.equal(await recovery.renew(executionId,"RECONCILIATION","worker-b",claim.recoveryLease.claimedAt,renewedAt,renewedUntil),false);const observation={observationId:randomUUID(),executionId,actorSubject:ACTOR,preparationId:value.preparationId,providerId:"reconcile-rpc",signature:value.artifact.signature,outcome:"PENDING"as const,observedAt:NOW,slot:"101",confirmationStatus:"processed"};await assert.rejects(()=>repo.recordReconciliationObservation({...observation,recoveryFence:{leaseOwner:"worker-b",leaseClaimedAt:claim.recoveryLease!.claimedAt}}),/stale or unauthorized/);await assert.rejects(()=>repo.recordReconciliationObservation({...observation,recoveryFence:{leaseOwner:"worker-a",leaseClaimedAt:"2026-08-13T11:59:59.000Z"}}),/stale or unauthorized/);await assert.rejects(()=>repo.recordReconciliationObservation(observation),/requires fenced/);const persisted=await repo.recordReconciliationObservation({...observation,recoveryFence:{leaseOwner:"worker-a",leaseClaimedAt:claim.recoveryLease.claimedAt}});assert.equal(persisted.preparation.state,"ACCEPTED_PENDING");assert.equal((await repo.commitSubmission(command)).submissionAuthorized,false);});

test("PostgreSQL rejects fabricated missing-row fences and exact-execution claims are exclusive",async()=>{const value=await repo.persistPreparation(prepared());await repo.commitSubmission({executionId,actorSubject:ACTOR,preparationId:value.preparationId,commitmentId:randomUUID(),committedAt:NOW});await assert.rejects(()=>repo.recordReconciliationObservation({observationId:randomUUID(),executionId,actorSubject:ACTOR,preparationId:value.preparationId,providerId:"reconcile-rpc",signature:value.artifact.signature,outcome:"PENDING",observedAt:NOW,recoveryFence:{leaseOwner:"fabricated",leaseClaimedAt:new Date().toISOString()}}),/stale or unauthorized/);const claimedAt=new Date().toISOString(),expiresAt=new Date(Date.parse(claimedAt)+5_000).toISOString(),claims=await Promise.all([recovery.claimReconciliationExecution(executionId,"exact-a",claimedAt,expiresAt),recovery.claimReconciliationExecution(executionId,"exact-b",claimedAt,expiresAt)]);assert.equal(claims.filter(Boolean).length,1);assert.equal(claims.find(Boolean)?.executionId,executionId);assert.equal(await recovery.claimReconciliationExecution(randomUUID(),"wrong-execution",claimedAt,expiresAt),undefined);});

test("PostgreSQL reclaimed lease rejects stale chain evidence and preserves newer settled evidence",async()=>{const value=await repo.persistPreparation(prepared()),signature=value.artifact.signature,command={executionId,actorSubject:ACTOR,preparationId:value.preparationId,commitmentId:randomUUID(),committedAt:NOW};await repo.commitSubmission(command);const claimedAt=new Date().toISOString(),shortExpiry=new Date(Date.parse(claimedAt)+40).toISOString(),first=await recovery.claimReconciliation("worker-a",claimedAt,shortExpiry);assert(first?.recoveryLease);await new Promise(resolve=>setTimeout(resolve,70));const reclaimedAt=new Date().toISOString(),reclaimedUntil=new Date(Date.parse(reclaimedAt)+5_000).toISOString(),expiredFence={leaseOwner:"worker-a",leaseClaimedAt:first.recoveryLease.claimedAt};assert.equal(await recovery.renew(executionId,"RECONCILIATION","worker-a",first.recoveryLease.claimedAt,reclaimedAt,reclaimedUntil),false);const stale={observationId:randomUUID(),executionId,actorSubject:ACTOR,preparationId:value.preparationId,providerId:"reconcile-rpc",signature,outcome:"FAILED"as const,observedAt:reclaimedAt,slot:"201",confirmationStatus:"finalized",errorCode:"PROVIDER_REPORTED_FAILURE",recoveryFence:expiredFence};await assert.rejects(()=>repo.recordReconciliationObservation(stale),/stale or unauthorized/);const second=await recovery.claimReconciliation("worker-b",reclaimedAt,reclaimedUntil);assert(second?.recoveryLease);assert.equal(await recovery.renew(executionId,"RECONCILIATION","worker-a",first.recoveryLease.claimedAt,reclaimedAt,reclaimedUntil),false);await recovery.release(executionId,"RECONCILIATION","worker-a",first.recoveryLease.claimedAt);const afterStaleRelease=new Date().toISOString();assert.equal(await recovery.renew(executionId,"RECONCILIATION","worker-b",second.recoveryLease.claimedAt,afterStaleRelease,new Date(Date.parse(afterStaleRelease)+5_000).toISOString()),true);const settled=await repo.recordReconciliationObservation({observationId:randomUUID(),executionId,actorSubject:ACTOR,preparationId:value.preparationId,providerId:"reconcile-rpc",signature,outcome:"SETTLED",observedAt:reclaimedAt,slot:"202",confirmationStatus:"finalized",recoveryFence:{leaseOwner:"worker-b",leaseClaimedAt:second.recoveryLease.claimedAt}});assert.equal(settled.preparation.state,"SETTLED");await assert.rejects(()=>repo.recordReconciliationObservation({...stale,observationId:randomUUID()}),/stale or unauthorized/);assert.equal((await repo.findPreparation(executionId,ACTOR))?.state,"SETTLED");assert.equal((await repo.listReconciliationObservations(executionId,ACTOR)).length,1);assert.equal((await repo.commitSubmission(command)).submissionAuthorized,false);});

test("PostgreSQL backlog aggregate exposes age only and terminal executions disappear",async()=>{const value=await repo.persistPreparation(prepared());await repo.commitSubmission({executionId,actorSubject:ACTOR,preparationId:value.preparationId,commitmentId:randomUUID(),committedAt:NOW});const backlog=await recovery.inspectUnresolvedBacklog("2026-08-13T12:10:00.000Z");assert.deepEqual(backlog,{unresolvedCount:1,oldestCommittedAt:NOW,oldestUnresolvedAgeMs:600_000});assert.equal(JSON.stringify(backlog).includes(executionId),false);await pool.query("UPDATE payment_executions SET status='SUBMITTING',version=version+1,updated_at=$2 WHERE execution_id=$1",[executionId,NOW]);await pool.query("UPDATE payment_executions SET status='FAILED',version=version+1,failed_at=$2,failure_code='TEST_TERMINAL',failure_category='TEST',failure_retryable=false,updated_at=$2 WHERE execution_id=$1",[executionId,NOW]);assert.deepEqual(await recovery.inspectUnresolvedBacklog("2026-08-13T12:10:00.000Z"),{unresolvedCount:0});});
