import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { after, beforeEach, test } from "node:test";
import { Pool } from "pg";
import { actorSubjectForAccount } from "../src/identity/identityTypes";
import { PostgresIdentityPersistence } from "../src/storage/postgres/postgresIdentityPersistence";
import { PostgresActivityRepository } from "../src/storage/postgres/postgresActivityRepository";

const url=process.env.TEST_DATABASE_URL?.trim();if(!url)throw new Error("TEST_DATABASE_URL is required.");
const pool=new Pool({connectionString:url}),identities=new PostgresIdentityPersistence(pool);const OWNER_ID="30000000-0000-4000-8000-000000000001",OTHER_ID="30000000-0000-4000-8000-000000000002",OWNER=actorSubjectForAccount(OWNER_ID),OTHER=actorSubjectForAccount(OTHER_ID),NOW="2026-08-07T12:00:00.000Z";
beforeEach(async()=>{await pool.query("TRUNCATE payment_execution_receipts,payment_execution_events,payment_execution_attempts,payment_executions,payment_events,payment_receipts,payments,beta_allowlist,account_security_events,account_sessions,accounts RESTART IDENTITY CASCADE");for(const[id,actor]of[[OWNER_ID,OWNER],[OTHER_ID,OTHER]]){await identities.createAccount({accountId:id,createdAt:NOW});await pool.query("INSERT INTO beta_allowlist(actor_subject)VALUES($1)",[actor]);}});after(async()=>pool.end());
async function payment(actor:string,createdAt:string,purpose:string|null){const id=randomUUID();await pool.query(`INSERT INTO payments(id,actor_subject,idempotency_key,request_hash,status,mint_address,recipient_address,amount_raw,purpose,created_at,updated_at)VALUES($1,$2,$3,decode($4,'hex'),'AWAITING_CONFIRMATION','mint','wallet',1250000,$5,$6,$6)`,[id,actor,`activity-${randomUUID()}`,"a".repeat(64),purpose,createdAt]);return id;}
async function settled(paymentIntentId:string){const executionId=randomUUID(),settledAt="2026-08-07T12:00:04.000Z";await pool.query(`INSERT INTO payment_executions(execution_id,payment_intent_id,actor_subject,status,provider_idempotency_key,settled_at,settlement_evidence,created_at,updated_at)VALUES($1,$2,$3,'SETTLED',$4,$5,'{}',$5,$5)`,[executionId,paymentIntentId,OWNER,`provider-${randomUUID()}`,settledAt]);await pool.query(`INSERT INTO payment_execution_receipts(receipt_id,execution_id,payment_intent_id,actor_subject,runtime_transaction_id,rail,asset,amount_units,amount_decimals,sender_id,recipient_id,memo,settled_at,evidence_type,evidence_version,evidence,schema_version,request_hash,created_at)VALUES($1,$2,$3,$4,$8,'mock','USDC',1250000,6,'sender','recipient',$5,$6,'mock.execution',1,'{}',1,decode($7,'hex'),$6)`,[`receipt:${executionId}`,executionId,paymentIntentId,OWNER,null,settledAt,"a".repeat(64),executionId]);return executionId;}

test("PostgreSQL activity query preserves owner ordering, limit, nullable purpose, and optional joined truth",async()=>{const oldest=await payment(OWNER,"2026-08-07T12:00:01.000Z","old"),middle=await payment(OWNER,"2026-08-07T12:00:02.000Z",null),newest=await payment(OWNER,"2026-08-07T12:00:03.000Z","new");await payment(OTHER,"2026-08-07T12:00:05.000Z","private");const executionId=await settled(middle);let queryCount=0;const counted={query:(...args:any[])=>{queryCount++;return(pool.query as any)(...args);}} as any;const items=await new PostgresActivityRepository(counted).listByActor(OWNER,2);assert.equal(queryCount,1);assert.deepEqual(items.map(x=>x.paymentIntentId),[newest,middle]);assert.equal(items.some(x=>x.paymentIntentId===oldest),false);assert.equal(items[0].executionId,undefined);assert.equal(items[0].receiptId,undefined);assert.equal(items[1].executionId,executionId);assert.match(items[1].receiptId??"",/^receipt:/);assert.equal(items[1].memo,null);assert.equal(items.every(x=>x.amountUnits==="1250000"),true);assert.equal(items.some(x=>x.memo==="private"),false);});
