import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { after, beforeEach, test } from "node:test";
import { Pool } from "pg";
import { PostgresExecutionRepository } from "../src/storage/postgres/postgresExecutionRepository";

const url=process.env.TEST_DATABASE_URL?.trim();if(!url)throw new Error("TEST_DATABASE_URL is required.");
const pool=new Pool({connectionString:url,max:4});const repo=new PostgresExecutionRepository(pool);const NOW="2026-08-07T12:00:00.000Z";
beforeEach(async()=>{await pool.query("TRUNCATE payment_execution_events,payment_execution_attempts,payment_executions,payment_events,payment_receipts,payments,beta_allowlist RESTART IDENTITY CASCADE");await pool.query("INSERT INTO beta_allowlist(actor_subject) VALUES('execution-integration')");});after(async()=>pool.end());
async function intent(){const id=randomUUID();await pool.query(`INSERT INTO payments(id,actor_subject,idempotency_key,request_hash,status,network,rail,asset,mint_address,recipient_address,amount_raw,purpose,user_confirmed_at,execution_started_at) VALUES($1,'execution-integration',$2,decode($3,'hex'),'PROCESSING','solana-devnet','solana','USDC','mint','wallet',1000000,'test',$4,$4)`,[id,`key-${randomUUID()}`,"a".repeat(64),NOW]);return id;}
test("PostgreSQL execution uniqueness, lease, attempts, and terminal immutability",async()=>{const paymentIntentId=await intent();const input={executionId:randomUUID(),paymentIntentId,actorSubject:"execution-integration",providerIdempotencyKey:"b".repeat(64),now:NOW};const [a,b]=await Promise.all([repo.createOrGet(input),repo.createOrGet({...input,executionId:randomUUID()})]);assert.equal(a.execution.executionId,b.execution.executionId);const claim=await repo.claim(["READY"],"worker",NOW,"2026-08-07T12:01:00.000Z");assert.ok(claim);assert.equal(await repo.claim(["SUBMITTING"],"other",NOW,"2026-08-07T12:01:00.000Z"),undefined);const failed=await repo.complete({executionId:claim.execution.executionId,expectedVersion:claim.execution.version,leaseOwner:"worker",attemptId:claim.attempt.attemptId,operation:"SUBMIT",toStatus:"FAILED",completedAt:NOW,failedAt:NOW,failureCode:"REJECTED",failureCategory:"provider",failureRetryable:false,sideEffect:"impossible"});assert.equal(failed.status,"FAILED");assert.equal((await repo.listAttempts(failed.executionId)).length,1);await assert.rejects(()=>pool.query("UPDATE payment_executions SET review_reason='changed',version=version+1 WHERE execution_id=$1",[failed.executionId]));await assert.rejects(()=>pool.query("DELETE FROM payment_execution_attempts WHERE execution_id=$1",[failed.executionId]));});
