import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { after, beforeEach, test } from "node:test";
import { Pool } from "pg";
import { actorSubjectForAccount } from "../src/identity/identityTypes";
import { PostgresIdentityPersistence } from "../src/storage/postgres/postgresIdentityPersistence";
import { PostgresExecutionRepository } from "../src/storage/postgres/postgresExecutionRepository";

const url=process.env.TEST_DATABASE_URL?.trim();if(!url)throw new Error("TEST_DATABASE_URL is required.");
const pool=new Pool({connectionString:url,max:4});const repo=new PostgresExecutionRepository(pool),identities=new PostgresIdentityPersistence(pool);const NOW="2026-08-07T12:00:00.000Z",ACCOUNT_ID="20000000-0000-4000-8000-000000000001",ACTOR=actorSubjectForAccount(ACCOUNT_ID);
beforeEach(async()=>{await pool.query("TRUNCATE payment_execution_receipts,payment_execution_events,payment_execution_attempts,payment_executions,payment_events,payment_receipts,payments,beta_allowlist,accounts RESTART IDENTITY CASCADE");await identities.createAccount({accountId:ACCOUNT_ID,createdAt:NOW});await pool.query("INSERT INTO beta_allowlist(actor_subject) VALUES($1)",[ACTOR]);});after(async()=>pool.end());
async function intent(){const id=randomUUID();await pool.query(`INSERT INTO payments(id,actor_subject,idempotency_key,request_hash,status,network,rail,asset,mint_address,recipient_address,amount_raw,purpose,user_confirmed_at,execution_started_at) VALUES($1,$2,$3,decode($4,'hex'),'PROCESSING','solana-devnet','solana','USDC','mint','wallet',1000000,'test',$5,$5)`,[id,ACTOR,`key-${randomUUID()}`,"a".repeat(64),NOW]);return id;}
test("PostgreSQL accepts and preserves a canonical null receipt memo",async()=>{const paymentIntentId=await intent();const executionId=randomUUID();await repo.createOrGet({executionId,paymentIntentId,actorSubject:ACTOR,providerIdempotencyKey:"d".repeat(64),now:NOW});const submit=await repo.claim(["READY"],"worker",NOW,"2026-08-07T12:01:00.000Z");assert.ok(submit);await repo.complete({executionId,expectedVersion:submit.execution.version,leaseOwner:"worker",attemptId:submit.attempt.attemptId,operation:"SUBMIT",toStatus:"PROCESSING",completedAt:NOW,submittedAt:NOW,sideEffect:"occurred"});const reconcile=await repo.claim(["PROCESSING"],"worker",NOW,"2026-08-07T12:01:00.000Z");assert.ok(reconcile);await repo.completeSettlement({completion:{executionId,expectedVersion:reconcile.execution.version,leaseOwner:"worker",attemptId:reconcile.attempt.attemptId,operation:"RECONCILE",toStatus:"SETTLED",completedAt:NOW,settledAt:NOW,evidence:{truth:true},sideEffect:"occurred"},receipt:{receiptId:`receipt:${executionId}`,paymentIntentId,executionId,actorSubject:ACTOR,runtimeTransactionId:executionId,rail:"mock",asset:"USDC",amountUnits:"1000000",amountDecimals:6,senderId:"actor:test",recipientId:"recipient:test",memo:null,settledAt:NOW,evidenceType:"mock.execution",evidenceVersion:1,evidence:{truth:true},schemaVersion:1,requestHash:"a".repeat(64),createdAt:NOW}});assert.equal((await repo.findReceiptByPaymentIntent(paymentIntentId))?.memo,null);});
test("PostgreSQL execution uniqueness, lease, attempts, and terminal immutability",async()=>{const paymentIntentId=await intent();const input={executionId:randomUUID(),paymentIntentId,actorSubject:ACTOR,providerIdempotencyKey:"b".repeat(64),now:NOW};const [a,b]=await Promise.all([repo.createOrGet(input),repo.createOrGet({...input,executionId:randomUUID()})]);assert.equal(a.execution.executionId,b.execution.executionId);const claim=await repo.claim(["READY"],"worker",NOW,"2026-08-07T12:01:00.000Z");assert.ok(claim);assert.equal(await repo.claim(["SUBMITTING"],"other",NOW,"2026-08-07T12:01:00.000Z"),undefined);const failed=await repo.complete({executionId:claim.execution.executionId,expectedVersion:claim.execution.version,leaseOwner:"worker",attemptId:claim.attempt.attemptId,operation:"SUBMIT",toStatus:"FAILED",completedAt:NOW,failedAt:NOW,failureCode:"REJECTED",failureCategory:"provider",failureRetryable:false,sideEffect:"impossible"});assert.equal(failed.status,"FAILED");assert.equal((await repo.listAttempts(failed.executionId)).length,1);await assert.rejects(()=>pool.query("UPDATE payment_executions SET review_reason='changed',version=version+1 WHERE execution_id=$1",[failed.executionId]));await assert.rejects(()=>pool.query("DELETE FROM payment_execution_attempts WHERE execution_id=$1",[failed.executionId]));});

test("PostgreSQL commits settled execution, canonical receipt, attempts, and events atomically",async()=>{const paymentIntentId=await intent();const executionId=randomUUID();await repo.createOrGet({executionId,paymentIntentId,actorSubject:ACTOR,providerIdempotencyKey:"b".repeat(64),now:NOW});const submit=await repo.claim(["READY"],"worker",NOW,"2026-08-07T12:01:00.000Z");assert.ok(submit);await repo.complete({executionId,expectedVersion:submit.execution.version,leaseOwner:"worker",attemptId:submit.attempt.attemptId,operation:"SUBMIT",toStatus:"PROCESSING",completedAt:NOW,providerReference:"mock-provider",reconciliationReference:"mock-reconcile",submittedAt:NOW,nextAttemptAt:NOW,sideEffect:"occurred"});const reconcile=await repo.claim(["PROCESSING"],"worker",NOW,"2026-08-07T12:01:00.000Z");assert.ok(reconcile);const receipt={receiptId:`receipt:${executionId}`,paymentIntentId,executionId,actorSubject:ACTOR,runtimeTransactionId:executionId,rail:"mock" as const,asset:"USDC" as const,amountUnits:"900719925474099312345",amountDecimals:6,senderId:"actor:test",recipientId:"recipient:test",memo:"test",providerReference:"mock-provider",settledAt:NOW,evidenceType:"mock.execution",evidenceVersion:1,evidence:{scenario:"immediate_settled"},schemaVersion:1 as const,requestHash:"a".repeat(64),createdAt:NOW};const completion={executionId,expectedVersion:reconcile.execution.version,leaseOwner:"worker",attemptId:reconcile.attempt.attemptId,operation:"RECONCILE" as const,toStatus:"SETTLED" as const,completedAt:NOW,providerReference:"mock-provider",reconciliationReference:"mock-reconcile",settledAt:NOW,evidence:{scenario:"immediate_settled"},sideEffect:"occurred" as const};const result=await repo.completeSettlement({completion,receipt});assert.equal(result.execution.status,"SETTLED");assert.equal(result.receipt.amountUnits,"900719925474099312345");const replay=await repo.completeSettlement({completion,receipt});assert.equal(replay.receipt.receiptId,result.receipt.receiptId);assert.equal((await pool.query("SELECT count(*)::int AS count FROM payment_execution_receipts WHERE execution_id=$1",[executionId])).rows[0].count,1);const eventTypes=(await pool.query("SELECT event_type FROM payment_execution_events WHERE execution_id=$1 ORDER BY sequence_number",[executionId])).rows.map(row=>row.event_type);assert.equal(eventTypes.filter(type=>type==="execution_settled").length,1);assert.equal(eventTypes.filter(type=>type==="receipt_created").length,1);await assert.rejects(()=>pool.query("UPDATE payment_execution_receipts SET memo='changed' WHERE execution_id=$1",[executionId]));await assert.rejects(()=>pool.query("DELETE FROM payment_execution_events WHERE execution_id=$1",[executionId]));});

test("receipt constraint failure rolls back false terminal settlement",async()=>{const paymentIntentId=await intent();const executionId=randomUUID();await repo.createOrGet({executionId,paymentIntentId,actorSubject:ACTOR,providerIdempotencyKey:"c".repeat(64),now:NOW});const submit=await repo.claim(["READY"],"worker",NOW,"2026-08-07T12:01:00.000Z");assert.ok(submit);await repo.complete({executionId,expectedVersion:submit.execution.version,leaseOwner:"worker",attemptId:submit.attempt.attemptId,operation:"SUBMIT",toStatus:"PROCESSING",completedAt:NOW,nextAttemptAt:NOW,sideEffect:"occurred"});const reconcile=await repo.claim(["PROCESSING"],"worker",NOW,"2026-08-07T12:01:00.000Z");assert.ok(reconcile);const completion={executionId,expectedVersion:reconcile.execution.version,leaseOwner:"worker",attemptId:reconcile.attempt.attemptId,operation:"RECONCILE" as const,toStatus:"SETTLED" as const,completedAt:NOW,providerReference:"mock-provider",settledAt:NOW,evidence:{truth:true},sideEffect:"occurred" as const};const invalid={receiptId:`receipt:${executionId}`,paymentIntentId,executionId,actorSubject:ACTOR,runtimeTransactionId:executionId,rail:"mock" as const,asset:"USDC" as const,amountUnits:"1",amountDecimals:6,senderId:"actor:test",recipientId:"recipient:test",memo:"test",providerReference:"mock-provider",settledAt:NOW,evidenceType:"mock.execution",evidenceVersion:0,evidence:{truth:true},schemaVersion:1 as const,requestHash:"a".repeat(64),createdAt:NOW};await assert.rejects(()=>repo.completeSettlement({completion,receipt:invalid}));const execution=await repo.findByPaymentIntent(paymentIntentId);assert.equal(execution?.status,"PROCESSING");assert.equal(execution?.leaseOwner,"worker");assert.equal(await repo.findReceiptByPaymentIntent(paymentIntentId),undefined);});
