import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { after, beforeEach, test } from "node:test";
import { Pool } from "pg";
import { actorSubjectForAccount } from "../src/identity/identityTypes";
import { Aes256GcmPreparedTransactionCipher } from "../src/devnet/preparedTransactionCipher";
import type { PersistDevnetPreparationInput } from "../src/devnet/devnetExecutionState";
import { PostgresIdentityPersistence } from "../src/storage/postgres/postgresIdentityPersistence";
import { PostgresDevnetExecutionStateRepository } from "../src/storage/postgres/postgresDevnetExecutionStateRepository";

const url=process.env.TEST_DATABASE_URL?.trim();if(!url)throw new Error("TEST_DATABASE_URL is required.");
const pool=new Pool({connectionString:url,max:4}),repo=new PostgresDevnetExecutionStateRepository(pool),identities=new PostgresIdentityPersistence(pool),NOW="2026-08-13T12:00:00.000Z",ACCOUNT_ID="20000000-0000-4000-8000-000000000001",ACTOR=actorSubjectForAccount(ACCOUNT_ID),POLICY="a".repeat(64),cipher=new Aes256GcmPreparedTransactionCipher(Buffer.alloc(32,9),"test-v1",()=>Buffer.alloc(12,4));
let executionId:string,paymentIntentId:string;
beforeEach(async()=>{await pool.query("TRUNCATE devnet_submission_commitments,devnet_execution_preparations,payment_execution_receipts,payment_execution_events,payment_execution_attempts,payment_executions,payment_events,payment_receipts,payments,beta_allowlist,accounts RESTART IDENTITY CASCADE");await identities.createAccount({accountId:ACCOUNT_ID,createdAt:NOW});await pool.query("INSERT INTO beta_allowlist(actor_subject) VALUES($1)",[ACTOR]);paymentIntentId=randomUUID();executionId=randomUUID();await pool.query(`INSERT INTO payments(id,actor_subject,idempotency_key,request_hash,status,network,rail,asset,mint_address,recipient_address,amount_raw,purpose,user_confirmed_at,execution_started_at) VALUES($1,$2,$3,decode($4,'hex'),'PROCESSING','solana-devnet','solana','USDC','mint','destination',1000000,'test',$5,$5)`,[paymentIntentId,ACTOR,`key-${randomUUID()}`,"b".repeat(64),NOW]);await pool.query(`INSERT INTO payment_executions(execution_id,payment_intent_id,actor_subject,status,selected_rail,execution_mode,settlement_network,policy_hash,provider_idempotency_key,created_at,updated_at) VALUES($1,$2,$3,'READY','solana','devnet_validation','solana-devnet',decode($4,'hex'),$5,$6,$6)`,[executionId,paymentIntentId,ACTOR,POLICY,"c".repeat(64),NOW]);});after(async()=>pool.end());
function prepared(generation=1):PersistDevnetPreparationInput{const preparationId=randomUUID(),base64=Buffer.from(`signed-${generation}`).toString("base64");return{preparationId,executionId,paymentIntentId,actorSubject:ACTOR,generation,encryptedSignedTransaction:cipher.encrypt(base64,{executionId,preparationId,keyVersion:"test-v1"}),artifact:{signature:`signature-${generation}-${executionId}`,signedTransactionDigest:generation.toString(16).repeat(64).slice(0,64),cluster:"solana-devnet",mint:"mint",rawAmount:"1000000",destination:"destination",sourceTokenAccount:"source",decimals:6,recentBlockhash:`blockhash-${generation}`,lastValidBlockHeight:"100",signerKeyId:"signer",signerKeyVersion:"1",signerPublicKey:"public",policyHash:POLICY,submissionProviderId:"submit-rpc",reconciliationProviderId:"reconcile-rpc"},preparedAt:NOW};}

test("PostgreSQL persists immutable complete artifact and enforces owner and economic uniqueness",async()=>{const value=await repo.persistPreparation(prepared());assert.equal(value.artifact.sourceTokenAccount,"source");assert.equal(await repo.findPreparation(executionId,"other"),undefined);await assert.rejects(()=>pool.query("UPDATE devnet_execution_preparations SET amount_units=2 WHERE preparation_id=$1",[value.preparationId]));await assert.rejects(()=>repo.persistPreparation({...prepared(2),artifact:{...prepared(2).artifact,signature:value.artifact.signature}}));});

test("PostgreSQL commitment concurrency grants one ephemeral authorization and restart is reconciliation-only",async()=>{const value=await repo.persistPreparation(prepared()),command={executionId,actorSubject:ACTOR,preparationId:value.preparationId,commitmentId:randomUUID(),committedAt:NOW};const[a,b]=await Promise.all([repo.commitSubmission(command),repo.commitSubmission(command)]);assert.equal([a,b].filter(x=>x.submissionAuthorized).length,1);const restarted=new PostgresDevnetExecutionStateRepository(pool);assert.equal((await restarted.commitSubmission(command)).submissionAuthorized,false);assert.deepEqual(await restarted.listPreparationEligible(),[]);assert.equal((await restarted.listReconciliationEligible())[0].state,"SUBMISSION_COMMITTED_RECONCILE_ONLY");await assert.rejects(()=>pool.query("UPDATE devnet_submission_commitments SET committed_at=now() WHERE execution_id=$1",[executionId]));});

test("PostgreSQL permits replacement before commitment and forbids it afterward",async()=>{const first=await repo.persistPreparation(prepared()),secondInput=prepared(2),second=await repo.replaceExpiredPreparation({priorPreparationId:first.preparationId,replacement:secondInput,abandonedAt:NOW});assert.equal(second.generation,2);await repo.commitSubmission({executionId,actorSubject:ACTOR,preparationId:second.preparationId,commitmentId:randomUUID(),committedAt:NOW});await assert.rejects(()=>repo.replaceExpiredPreparation({priorPreparationId:second.preparationId,replacement:prepared(3),abandonedAt:NOW}),/reconciliation-only|never-contacted/);});

test("PostgreSQL reconciliation provenance is owner-scoped, append-only, and terminal-monotonic",async()=>{const value=await repo.persistPreparation(prepared());await repo.commitSubmission({executionId,actorSubject:ACTOR,preparationId:value.preparationId,commitmentId:randomUUID(),committedAt:NOW});const pending=await repo.recordReconciliationObservation({observationId:randomUUID(),executionId,actorSubject:ACTOR,preparationId:value.preparationId,providerId:"reconcile-rpc",outcome:"PENDING",observedAt:NOW,slot:"10",confirmationStatus:"processed"});assert.equal(pending.preparation.state,"ACCEPTED_PENDING");const stale=await repo.recordReconciliationObservation({observationId:randomUUID(),executionId,actorSubject:ACTOR,preparationId:value.preparationId,providerId:"reconcile-rpc",outcome:"MISSING",observedAt:NOW});assert.equal(stale.preparation.state,"ACCEPTED_PENDING");const settled=await repo.recordReconciliationObservation({observationId:randomUUID(),executionId,actorSubject:ACTOR,preparationId:value.preparationId,providerId:"reconcile-rpc",outcome:"SETTLED",observedAt:NOW,slot:"11",confirmationStatus:"finalized"});assert.equal(settled.preparation.state,"SETTLED");await assert.rejects(()=>repo.recordReconciliationObservation({observationId:randomUUID(),executionId,actorSubject:ACTOR,preparationId:value.preparationId,providerId:"reconcile-rpc",outcome:"PENDING",observedAt:NOW}),/Terminal/);assert.equal((await repo.listReconciliationObservations(executionId,ACTOR)).length,3);assert.deepEqual(await repo.listReconciliationObservations(executionId,"other"),[]);await assert.rejects(()=>pool.query("UPDATE devnet_reconciliation_observations SET outcome='UNKNOWN' WHERE execution_id=$1",[executionId]));});
