import {randomUUID} from "node:crypto";
import type {ExternalPrincipal} from "../auth/externalPrincipal";
import {hasActivePaymentAccess} from "../allowlist/allowlistEntry";
import {AccountAccessDeniedError,AccountProvisioningService} from "../identity/accountProvisioningService";
import {rawUsdcToDisplay,usdcAmountToRaw} from "../payments/paymentIntentValidation";
import type {PaymentPersistence} from "../storage/storageContracts";
import type {ExecutionRepository} from "../executions/executionRepository";
import type {RecipientDirectoryService} from "../recipients/recipientDirectoryService";
import {PaymentIntentApplicationError,PaymentIntentService} from "../services/paymentIntentService";
import type {PaymentRequestPartySnapshot,PaymentRequestRecord,PaymentRequestRepository} from "./paymentRequestTypes";
import {PaymentRequestVersionConflictError} from "./paymentRequestTypes";
import {paymentRequestHash} from "./paymentRequestValidation";

export class PaymentRequestApplicationError extends Error{constructor(readonly kind:"INVALID"|"ACCESS_DENIED"|"NOT_FOUND"|"CONFLICT",message:string){super(message);this.name="PaymentRequestApplicationError"}}
export class PaymentRequestService{
 constructor(private accounts:AccountProvisioningService,private payments:PaymentPersistence,private requests:PaymentRequestRepository,private directory:RecipientDirectoryService,private intents:PaymentIntentService,private executions?:ExecutionRepository,private clock=()=>new Date().toISOString(),private id=()=>randomUUID()){}
 async create(principal:ExternalPrincipal,input:{idempotencyKey:string;payerAccountId:string;amount:string;purpose:string|null}){const actor=await this.actor(principal);await this.access(actor.actorSubject);let payer,requester;try{[payer,requester]=await Promise.all([this.directory.resolvePublicRecipient(actor.accountId,input.payerAccountId),this.directory.resolveOwnPayableRecipient(actor.accountId)])}catch{throw new PaymentRequestApplicationError("NOT_FOUND","Payment recipient was not found.")}const amountRaw=usdcAmountToRaw(input.amount),now=this.clock(),hash=paymentRequestHash({requesterAccountId:actor.accountId,payerAccountId:payer.accountId,amountRaw,purpose:input.purpose});const claim=await this.requests.claim({requestId:this.id(),requesterAccountId:actor.accountId,requesterActorSubject:actor.actorSubject,payerAccountId:payer.accountId,requesterSnapshot:snapshot(requester,now),payerSnapshot:snapshot(payer,now),amountRaw,asset:"USDC",purpose:input.purpose,requestHash:hash,idempotencyKey:input.idempotencyKey,occurredAt:now});if(claim.outcome==="HASH_CONFLICT")throw new PaymentRequestApplicationError("CONFLICT","Idempotency key was already used for a different payment request.");return{paymentRequest:publicRequest(claim.request,actor.accountId),created:claim.outcome==="CLAIMED"}}
 async find(principal:ExternalPrincipal,id:string){const actor=await this.actor(principal),request=await this.refresh(await this.requests.find(id));if(!request||!visible(request,actor.accountId))throw notFound();return publicRequest(request,actor.accountId)}
 async list(principal:ExternalPrincipal,limit:number){const actor=await this.actor(principal);if(!Number.isSafeInteger(limit)||limit<1||limit>50)throw new PaymentRequestApplicationError("INVALID","Payment request limit must be between 1 and 50.");return Promise.all((await this.requests.listVisible(actor.accountId,limit)).map(async r=>publicRequest((await this.refresh(r))!,actor.accountId)))}
 async accept(principal:ExternalPrincipal,id:string,input:{expectedVersion:bigint;trustAcknowledgment?:{acknowledged:true}}){const actor=await this.actor(principal);await this.access(actor.actorSubject);const request=await this.ownedPending(id,actor.accountId,"payer",input.expectedVersion);let intent;try{intent=await this.intents.create(principal,{idempotencyKey:`payment-request:${request.requestId}`,recipientType:"payment_identity",recipientAccountId:request.requesterAccountId,amount:rawUsdcToDisplay(request.amountRaw),purpose:request.purpose,...(input.trustAcknowledgment?{trustAcknowledgment:input.trustAcknowledgment}:{})})}catch(error){if(error instanceof PaymentIntentApplicationError)throw new PaymentRequestApplicationError(error.kind,error.message);throw error}try{const updated=await this.requests.transition({requestId:id,expectedVersion:input.expectedVersion,actorAccountId:actor.accountId,toStatus:"ACCEPTED",occurredAt:this.clock(),linkedPaymentIntentId:intent.paymentIntent.id});return{paymentRequest:publicRequest(updated,actor.accountId),paymentIntent:intent.paymentIntent,applied:true}}catch(error){if(!(error instanceof PaymentRequestVersionConflictError))throw error;const concurrent=await this.requests.find(id);if(concurrent?.status==="ACCEPTED"&&concurrent.linkedPaymentIntentId===intent.paymentIntent.id)return{paymentRequest:publicRequest(concurrent,actor.accountId),paymentIntent:intent.paymentIntent,applied:false};throw conflict()}}
 async decline(principal:ExternalPrincipal,id:string,expectedVersion:bigint){return this.change(principal,id,expectedVersion,"payer","DECLINED")}
 async cancel(principal:ExternalPrincipal,id:string,expectedVersion:bigint){return this.change(principal,id,expectedVersion,"requester","CANCELLED")}
 private async change(principal:ExternalPrincipal,id:string,version:bigint,role:"payer"|"requester",status:"DECLINED"|"CANCELLED"){const actor=await this.actor(principal);const request=await this.ownedPending(id,actor.accountId,role,version);try{return{paymentRequest:publicRequest(await this.requests.transition({requestId:id,expectedVersion:version,actorAccountId:actor.accountId,toStatus:status,occurredAt:this.clock()}),actor.accountId),applied:true}}catch(error){if(error instanceof PaymentRequestVersionConflictError)throw conflict();throw error}}
 private async ownedPending(id:string,accountId:string,role:"payer"|"requester",version:bigint){const request=await this.requests.find(id);if(!request||request[role==="payer"?"payerAccountId":"requesterAccountId"]!==accountId)throw notFound();if(request.status!=="PENDING"||request.version!==version)throw conflict();return request}
 private async refresh(request?:PaymentRequestRecord){if(!request||request.status!=="ACCEPTED"||!request.linkedPaymentIntentId||!this.executions)return request;const receipt=await this.executions.findReceiptByPaymentIntent(request.linkedPaymentIntentId);if(!receipt)return request;return await this.requests.markPaidByPaymentIntent({paymentIntentId:request.linkedPaymentIntentId,executionId:receipt.executionId,receiptId:receipt.receiptId,paidAt:receipt.settledAt})??request}
 private async actor(principal:ExternalPrincipal){try{return(await this.accounts.resolve(principal)).account}catch(error){if(error instanceof AccountAccessDeniedError)throw new PaymentRequestApplicationError("ACCESS_DENIED","Payment request access is unavailable.");throw error}}
 private async access(actorSubject:string){if(!hasActivePaymentAccess(await this.payments.findAllowlistEntry(actorSubject),this.clock()))throw new PaymentRequestApplicationError("ACCESS_DENIED","Beta payment access is unavailable.")}
}
function snapshot(v:{accountId:string;username:string;displayName:string;accountType:string;verificationState:string},at:string):PaymentRequestPartySnapshot{return Object.freeze({accountId:v.accountId,username:v.username,displayName:v.displayName,accountType:v.accountType as PaymentRequestPartySnapshot["accountType"],verificationState:v.verificationState as PaymentRequestPartySnapshot["verificationState"],capturedAt:at,schemaVersion:1})}
function publicRequest(r:PaymentRequestRecord,viewer:string){return Object.freeze({requestId:r.requestId,role:r.requesterAccountId===viewer?"requester" as const:"payer" as const,direction:r.requesterAccountId===viewer?"requested" as const:"request_received" as const,status:r.status.toLowerCase(),version:r.version.toString(),requestHash:r.requestHash,requester:serialize(r.requesterSnapshot),payer:serialize(r.payerSnapshot),amountRaw:r.amountRaw.toString(),amount:rawUsdcToDisplay(r.amountRaw),asset:r.asset,purpose:r.purpose,createdAt:r.createdAt,updatedAt:r.updatedAt,...(r.acceptedAt?{acceptedAt:r.acceptedAt}:{}),...(r.declinedAt?{declinedAt:r.declinedAt}:{}),...(r.cancelledAt?{cancelledAt:r.cancelledAt}:{}),...(r.expiredAt?{expiredAt:r.expiredAt}:{}),...(r.paidAt?{paidAt:r.paidAt}:{}),...(r.linkedPaymentIntentId?{linkedPaymentIntentId:r.linkedPaymentIntentId}:{}),...(r.linkedExecutionId?{linkedExecutionId:r.linkedExecutionId}:{}),...(r.linkedReceiptId?{linkedReceiptId:r.linkedReceiptId}:{})})}
function serialize(s:PaymentRequestPartySnapshot){return{accountId:s.accountId,username:s.username,displayName:s.displayName,accountType:s.accountType.toLowerCase(),verificationState:s.verificationState.toLowerCase(),capturedAt:s.capturedAt,schemaVersion:1 as const}}
function visible(r:PaymentRequestRecord,a:string){return r.requesterAccountId===a||r.payerAccountId===a}function notFound(){return new PaymentRequestApplicationError("NOT_FOUND","Payment request was not found.")}function conflict(){return new PaymentRequestApplicationError("CONFLICT","Payment request changed or cannot make that transition.")}
