import { createHash, randomUUID } from "node:crypto";
import { PublicKey } from "@solana/web3.js";
import type { RailExecutionCommand } from "zephyon-protocol";
import type { ExternalPrincipal } from "../auth/externalPrincipal";
import { hasActivePaymentAccess } from "../allowlist/allowlistEntry";
import { AccountAccessDeniedError, AccountProvisioningService } from "../identity/accountProvisioningService";
import type { PaymentRecord } from "../payments/paymentTypes";
import type { PaymentPersistence } from "../storage/storageContracts";
import type { DevnetExecutionStateRepository, PersistedDevnetPreparation } from "./devnetExecutionState";
import { DevnetOrchestrationService } from "./devnetOrchestrationService";
import { DevnetReconciliationService } from "./devnetReconciliationService";
import { CIRCLE_SOLANA_DEVNET_USDC_DECIMALS, CIRCLE_SOLANA_DEVNET_USDC_MINT } from "./canonicalDevnetAsset";

export type BrowserDevnetStatus="preparing"|"prepared"|"submitting"|"accepted"|"reconciling"|"settled"|"failed"|"unknown_reconciliation_required";
export type BrowserDevnetProjection=Readonly<{paymentIntentId:string;executionId:string;network:"solana-devnet";rail:"solana";asset:"USDC";amount:string;amountRaw:string;recipientWallet:string;status:BrowserDevnetStatus;transactionSignature?:string;providerStatus?:"accepted"|"rejected"|"unknown"|"settled";settledAt?:string;failureCategory?:"provider_rejected"|"chain_failed"|"internal_validation";reconciliationPending:boolean;receiptId?:string}>;
export type BrowserDevnetAggregate=Readonly<{executionId:string;paymentIntentId:string;actorSubject:string;providerIdempotencyKey:string;amountRaw:string;recipientWallet:string;purpose:string|null;createdAt:string;receiptId?:string;settledAt?:string}>;
export interface BrowserDevnetExecutionStore{
 createOrGet(input:Readonly<{executionId:string;paymentIntentId:string;actorSubject:string;providerIdempotencyKey:string;policyHash:string;now:string}>):Promise<Readonly<{aggregate:BrowserDevnetAggregate;created:boolean}>>;
 find(paymentIntentId:string,actorSubject:string):Promise<BrowserDevnetAggregate|undefined>;
 applyLifecycle(input:Readonly<{aggregate:BrowserDevnetAggregate;preparation:PersistedDevnetPreparation;signature?:string;observedAt:string;failureCode?:string}>):Promise<BrowserDevnetAggregate>;
}
export class BrowserDevnetError extends Error{constructor(readonly kind:"DISABLED"|"ACCESS_DENIED"|"NOT_FOUND"|"INVALID"|"CONFLICT",message:string){super(message);this.name="BrowserDevnetError";}}
export type BrowserDevnetPolicy=Readonly<{exposureEnabled:boolean;preparationEnabled:boolean;submissionEnabled:boolean;reconciliationEnabled:boolean;policyHash:string;maxRawAmount:bigint}>;

export class BrowserDevnetExecutionService{
 constructor(private accounts:AccountProvisioningService,private payments:PaymentPersistence,private store:BrowserDevnetExecutionStore,private states:DevnetExecutionStateRepository,private orchestration:DevnetOrchestrationService|undefined,private reconciliation:DevnetReconciliationService|undefined,private policy:BrowserDevnetPolicy,private clock=()=>new Date().toISOString(),private id=()=>randomUUID()){}
 async execute(principal:ExternalPrincipal,paymentIntentId:string,body:unknown){
  this.requireExposure();const actor=await this.actor(principal);await this.requireAllowlist(actor.actorSubject);const payment=await this.requirePayment(paymentIntentId,actor.actorSubject);this.validateRequest(payment,body);
  if(!this.policy.preparationEnabled||!this.policy.submissionEnabled||!this.orchestration)throw new BrowserDevnetError("DISABLED","Devnet execution is temporarily unavailable.");
  const providerIdempotencyKey=createHash("sha256").update(`zephipay-browser-devnet-v1:${payment.id}`).digest("hex"),created=await this.store.createOrGet({executionId:this.id(),paymentIntentId:payment.id,actorSubject:actor.actorSubject,providerIdempotencyKey,policyHash:this.policy.policyHash,now:this.clock()}),aggregate=created.aggregate;
  let preparation=await this.states.findPreparation(aggregate.executionId,actor.actorSubject);
	  if(!preparation){try{preparation=await this.orchestration.prepare({preparationId:aggregate.executionId,executionId:aggregate.executionId,paymentIntentId:payment.id,actorSubject:actor.actorSubject,generation:1},this.command(payment,aggregate.executionId,providerIdempotencyKey));}catch(error){preparation=await this.states.findPreparation(aggregate.executionId,actor.actorSubject);if(!preparation)throw error;}}
	  if(preparation.state==="PREPARED_NOT_CONTACTED"){try{preparation=await this.orchestration.refreshExpiredPreContact(aggregate.executionId,actor.actorSubject,stableUuid(`${aggregate.executionId}:${preparation.generation+1}`),this.command(payment,aggregate.executionId,providerIdempotencyKey));}catch(error){if(!(error instanceof Error)||error.message!=="Devnet preparation blockhash remains valid.")throw error;}}
  await this.store.applyLifecycle({aggregate,preparation,observedAt:this.clock()});
  const submitted=await this.orchestration.submitPrepared({executionId:aggregate.executionId,actorSubject:actor.actorSubject,commitmentId:aggregate.executionId,providerIdempotencyKey});
  const durable="preparation"in submitted?submitted.preparation:preparation;await this.store.applyLifecycle({aggregate,preparation:durable,signature:durable.artifact.signature,observedAt:this.clock(),...("observation"in submitted&&submitted.observation.providerErrorCode?{failureCode:submitted.observation.providerErrorCode}:{})});
  return Object.freeze({created:created.created,execution:await this.project(payment,aggregate.executionId,actor.actorSubject)});
 }
 async find(principal:ExternalPrincipal,paymentIntentId:string){this.requireExposure();const actor=await this.actor(principal),payment=await this.requirePayment(paymentIntentId,actor.actorSubject),aggregate=await this.store.find(paymentIntentId,actor.actorSubject);if(!aggregate)throw new BrowserDevnetError("NOT_FOUND","Devnet execution was not found.");return this.project(payment,aggregate.executionId,actor.actorSubject);}
 async recoverPreparation(paymentIntentId:string,actorSubject:string){
  if(!this.policy.preparationEnabled||!this.orchestration)return false;
  const payment=await this.requirePayment(paymentIntentId,actorSubject),aggregate=await this.store.find(paymentIntentId,actorSubject);
  if(!aggregate)return false;
  const providerIdempotencyKey=createHash("sha256").update(`zephipay-browser-devnet-v1:${payment.id}`).digest("hex");
  if(aggregate.providerIdempotencyKey!==providerIdempotencyKey)return false;
  let preparation=await this.states.findPreparation(aggregate.executionId,actorSubject);
  if(!preparation){preparation=await this.orchestration.prepare({preparationId:aggregate.executionId,executionId:aggregate.executionId,paymentIntentId:payment.id,actorSubject,generation:1},this.command(payment,aggregate.executionId,providerIdempotencyKey));await this.store.applyLifecycle({aggregate,preparation,observedAt:this.clock()});return true;}
  if(preparation.state!=="PREPARED_NOT_CONTACTED")return false;
  try{preparation=await this.orchestration.refreshExpiredPreContact(aggregate.executionId,actorSubject,stableUuid(`${aggregate.executionId}:${preparation.generation+1}`),this.command(payment,aggregate.executionId,providerIdempotencyKey));}
  catch(error){if(error instanceof Error&&error.message==="Devnet preparation blockhash remains valid.")return false;throw error;}
  await this.store.applyLifecycle({aggregate,preparation,observedAt:this.clock()});return true;
 }
 async reconcileOwned(paymentIntentId:string,actorSubject:string){if(!this.policy.reconciliationEnabled||!this.reconciliation)return false;const payment=await this.requirePayment(paymentIntentId,actorSubject),aggregate=await this.store.find(paymentIntentId,actorSubject);if(!aggregate||aggregate.providerIdempotencyKey!==createHash("sha256").update(`zephipay-browser-devnet-v1:${payment.id}`).digest("hex"))return false;const result=await this.reconciliation.reconcile(aggregate.executionId,actorSubject);await this.store.applyLifecycle({aggregate,preparation:result.preparation,signature:result.preparation.artifact.signature,observedAt:result.observation.observedAt,...(result.observation.errorCode?{failureCode:result.observation.errorCode}:{})});await this.project(payment,aggregate.executionId,actorSubject);return true;}
 // @ts-expect-error Node supports Array.at; the configured TypeScript library predates its declaration.
 private async project(payment:PaymentRecord,executionId:string,actorSubject:string):Promise<BrowserDevnetProjection>{const aggregate=await this.store.find(payment.id,actorSubject);if(!aggregate)throw new BrowserDevnetError("NOT_FOUND","Devnet execution was not found.");const preparation=await this.states.findPreparation(executionId,actorSubject),submissions=await this.states.listSubmissionObservations(executionId,actorSubject),reconciliations=await this.states.listReconciliationObservations(executionId,actorSubject),lastSubmission=submissions.at(-1),lastReconciliation=reconciliations.at(-1),state=preparation?.state,status:BrowserDevnetStatus=!preparation?"preparing":state==="PREPARED_NOT_CONTACTED"?"prepared":state==="SUBMISSION_COMMITTED_RECONCILE_ONLY"?"submitting":state==="ACCEPTED_PENDING"?(lastReconciliation?.outcome==="PENDING"?"reconciling":"accepted"):state==="UNKNOWN_RECONCILIATION_REQUIRED"?"unknown_reconciliation_required":state==="SETTLED"?"settled":"failed";return Object.freeze({paymentIntentId:payment.id,executionId,network:"solana-devnet",rail:"solana",asset:"USDC",amount:display(payment.amountRaw),amountRaw:payment.amountRaw.toString(),recipientWallet:payment.recipientAddress,status,...(preparation&&state!=="PREPARED_NOT_CONTACTED"?{transactionSignature:preparation.artifact.signature}:{}),...(lastSubmission?{providerStatus:lastSubmission.outcome==="ACCEPTED"?"accepted":lastSubmission.outcome==="SETTLED"?"settled":lastSubmission.outcome==="REJECTED"?"rejected":"unknown"}:{}),...(aggregate.settledAt?{settledAt:aggregate.settledAt}:{}),...(state==="FAILED"?{failureCategory:lastSubmission?.outcome==="REJECTED"?"provider_rejected" as const:lastReconciliation?.outcome==="FAILED"?"chain_failed" as const:"internal_validation" as const}:{}),reconciliationPending:["SUBMISSION_COMMITTED_RECONCILE_ONLY","ACCEPTED_PENDING","UNKNOWN_RECONCILIATION_REQUIRED"].includes(state??""),...(aggregate.receiptId?{receiptId:aggregate.receiptId}:{})});}
 private command(payment:PaymentRecord,executionId:string,key:string):RailExecutionCommand{return{schemaVersion:1,requestId:`browser:${executionId}`,correlationId:`payment:${payment.id}`,executionId,paymentIntentId:payment.id,transactionId:executionId,requestedAt:this.clock(),actorId:`actor:${createHash("sha256").update(payment.actorSubject).digest("hex").slice(0,32)}`,recipientId:`wallet:${payment.recipientAddress}`,amount:{asset:"USDC",units:payment.amountRaw.toString(),decimals:CIRCLE_SOLANA_DEVNET_USDC_DECIMALS},destination:{type:"wallet",network:"solana-devnet",address:payment.recipientAddress},rail:"solana",providerIdempotencyKey:key}as RailExecutionCommand;}
 private validateRequest(payment:PaymentRecord,body:unknown){if(!body||typeof body!=="object"||Array.isArray(body)||Object.keys(body as object).some(k=>!["requestHash","expectedVersion","mode"].includes(k)))throw new BrowserDevnetError("INVALID","Devnet execute request contains unsupported fields.");const value=body as Record<string,unknown>;if(value.mode!=="solana-devnet")throw new BrowserDevnetError("INVALID","Solana Devnet mode is required.");if(value.requestHash!==payment.requestHash||String(value.expectedVersion)!==payment.version.toString())throw new BrowserDevnetError("CONFLICT","Payment intent confirmation is stale or mismatched.");if(payment.status!=="PROCESSING"||!payment.userConfirmedAt)throw new BrowserDevnetError("CONFLICT","Payment intent is not confirmed for Devnet execution.");if(payment.recipientType!=="DIRECT_WALLET"||payment.network!=="solana-devnet"||payment.rail!=="solana"||payment.asset!=="USDC"||payment.mintAddress!==CIRCLE_SOLANA_DEVNET_USDC_MINT)throw new BrowserDevnetError("CONFLICT","Payment intent is not eligible for Solana Devnet execution.");try{if(new PublicKey(payment.recipientAddress).toBase58()!==payment.recipientAddress)throw new Error();}catch{throw new BrowserDevnetError("INVALID","Recipient wallet is invalid.");}if(payment.amountRaw<=0n||payment.amountRaw>this.policy.maxRawAmount)throw new BrowserDevnetError("INVALID","Payment amount is outside the enabled Devnet bounds.");}
 private async actor(p:ExternalPrincipal){try{return(await this.accounts.resolve(p)).account;}catch(e){if(e instanceof AccountAccessDeniedError)throw new BrowserDevnetError("ACCESS_DENIED","Payment access is unavailable.");throw e;}}
 private async requirePayment(id:string,actor:string){const payment=await this.payments.findPayment(id);if(!payment||payment.actorSubject!==actor)throw new BrowserDevnetError("NOT_FOUND","Payment intent was not found.");return payment;}
 private async requireAllowlist(actor:string){if(!hasActivePaymentAccess(await this.payments.findAllowlistEntry(actor),this.clock()))throw new BrowserDevnetError("ACCESS_DENIED","Beta payment access is unavailable.");}
 private requireExposure(){if(!this.policy.exposureEnabled)throw new BrowserDevnetError("DISABLED","Browser Devnet execution is not enabled.");}
}
function display(raw:bigint){const value=raw.toString().padStart(7,"0"),whole=value.slice(0,-6),fraction=value.slice(-6).replace(/0+$/,"");return fraction?`${whole}.${fraction}`:whole;}
function stableUuid(value:string){const hex=createHash("sha256").update(value).digest("hex").slice(0,32).split("");hex[12]="4";hex[16]=((Number.parseInt(hex[16],16)&3)|8).toString(16);return`${hex.slice(0,8).join("")}-${hex.slice(8,12).join("")}-${hex.slice(12,16).join("")}-${hex.slice(16,20).join("")}-${hex.slice(20).join("")}`;}
