import { PublicKey } from "@solana/web3.js";
import type { Pool } from "pg";
import { signedTransactionDigest, type RailExecutionCommand, type SolanaSubmissionRpc } from "zephyon-protocol";
import { SingleAttemptDevnetJsonRpc, type JsonRpcFetch } from "../adapters/solana/devnetJsonRpc";
import { ReconciliationDevnetBlockDataSource } from "../adapters/solana/liveDevnetProviders";
import { PostgresDevnetExecutionStateRepository } from "../storage/postgres/postgresDevnetExecutionStateRepository";
import { CIRCLE_SOLANA_DEVNET_USDC_DECIMALS, CIRCLE_SOLANA_DEVNET_USDC_MINT } from "./canonicalDevnetAsset";
import { parseDevnetLiveConfiguration, type DevnetLiveConfiguration } from "./devnetLiveConfiguration";
import type { DevnetExecutionStateRepository, PersistedDevnetPreparation } from "./devnetExecutionState";
import { DevnetOrchestrationService, type DevnetReconciliationProvider } from "./devnetOrchestrationService";
import { deriveDevnetAssociatedSourceTokenAccount, devnetPreparationPolicy, hashDevnetPolicy } from "./devnetPreparationPolicy";
import { InjectedDevnetTransactionSigner } from "./injectedDevnetSigner";
import { Aes256GcmPreparedTransactionCipher } from "./preparedTransactionCipher";

type Environment=Readonly<Record<string,string|undefined>>;
export type E6bRefreshExecution=Readonly<{paymentIntentId:string;actorSubject:string;executionMode:string;rail:string;network:string;policyHash:string;providerIdempotencyKey:string}>;
export type E6bRefreshRequest=Readonly<{config:DevnetLiveConfiguration;databaseUrl:string;actorSubject:string;paymentIntentId:string;executionId:string;existingPreparationId:string;existingGeneration:number;replacementPreparationId:string;expectedPolicyHash:string;destination:string;rawAmount:string}>;
export type E6bRefreshDependencies=Readonly<{repository:DevnetExecutionStateRepository;loadExecution():Promise<E6bRefreshExecution|undefined>;fetch:JsonRpcFetch}>;
export type E6bRefreshResult=Readonly<{verdict:"REFRESHED_PRE_CONTACT";executionId:string;priorPreparationId:string;priorGeneration:number;replacementPreparationId:string;replacementGeneration:number;mint:string;sourceTokenAccount:string;destination:string;rawAmount:string;decimals:number;canonicalPolicyHash:string;signerPublicKey:string;signerKeyId:string;signerKeyVersion:string;recentBlockhash:string;lastValidBlockHeight:string;signedTransactionDigest:string;transactionSignature:string;durableState:"PREPARED_NOT_CONTACTED";submissionCommitmentCount:0;submissionObservationCount:0;sendTransactionCalls:0;rpcMethods:readonly["getBlockHeight","getLatestBlockhash"]}>;
const CONFIRMATION="REFRESH_EXPIRED_E6B_PREPARATION_PRE_CONTACT";

export function parseE6bRefreshRequest(env:Environment=process.env):E6bRefreshRequest{
  if(env.E6B_REFRESH_OPERATOR_CONFIRMATION!==CONFIRMATION)throw new Error("E6B refresh exact operator confirmation is required.");const config=parseDevnetLiveConfiguration(env);
  if(!config.enabled||!config.preparationEnabled||!config.reconciliationEnabled||config.submissionEnabled)throw new Error("E6B refresh requires integration, preparation, and reconciliation ON with submission OFF.");
  if(!config.reconciliationUrl||!config.reconciliationProviderId||!config.submissionProviderId||!config.encryptionKey||!config.encryptionKeyVersion||!config.signerSecretKey||!config.signerKeyId||!config.signerKeyVersion||!config.signerPublicKey||!config.mint||config.decimals===undefined||!config.sourceTokenAccount)throw new Error("E6B refresh configuration is incomplete.");
  if(config.mint!==CIRCLE_SOLANA_DEVNET_USDC_MINT||config.decimals!==CIRCLE_SOLANA_DEVNET_USDC_DECIMALS||deriveDevnetAssociatedSourceTokenAccount(config.mint,config.signerPublicKey)!==config.sourceTokenAccount)throw new Error("E6B refresh requires canonical Circle Solana Devnet USDC signer economics.");
  const expectedPolicyHash=hex(required(env,"E6B_REFRESH_EXPECTED_POLICY_HASH")),canonical=hashDevnetPolicy(devnetPreparationPolicy({mint:config.mint,decimals:config.decimals,sourceTokenAccount:config.sourceTokenAccount,signerKeyId:config.signerKeyId,signerKeyVersion:config.signerKeyVersion,signerPublicKey:config.signerPublicKey,submissionProviderId:config.submissionProviderId,reconciliationProviderId:config.reconciliationProviderId}));if(canonical!==expectedPolicyHash)throw new Error("E6B refresh policy does not match canonical configuration.");
  const destination=publicKey(required(env,"E6B_REFRESH_EXPECTED_DESTINATION")),rawAmount=required(env,"E6B_REFRESH_EXPECTED_RAW_AMOUNT");if(!/^[1-9]\d*$/.test(rawAmount)||rawAmount!=="1000")throw new Error("E6B refresh requires the expected tiny canonical raw amount.");
  return Object.freeze({config,databaseUrl:localDatabaseUrl(required(env,"E6B_REFRESH_DATABASE_URL")),actorSubject:required(env,"E6B_REFRESH_ACTOR_SUBJECT"),paymentIntentId:required(env,"E6B_REFRESH_PAYMENT_ID"),executionId:required(env,"E6B_REFRESH_EXECUTION_ID"),existingPreparationId:required(env,"E6B_REFRESH_EXISTING_PREPARATION_ID"),existingGeneration:integer(required(env,"E6B_REFRESH_EXISTING_GENERATION")),replacementPreparationId:required(env,"E6B_REFRESH_REPLACEMENT_PREPARATION_ID"),expectedPolicyHash,destination,rawAmount});
}

export async function runE6bPreparationRefresh(request:E6bRefreshRequest,deps:E6bRefreshDependencies):Promise<E6bRefreshResult>{
  const execution=await deps.loadExecution();assertExecution(request,execution);const prior=await deps.repository.findPreparation(request.executionId,request.actorSubject);if(!prior)throw new Error("E6B refresh preparation was not found for the supplied owner.");
  const commitment=await deps.repository.findCommitment(request.executionId,request.actorSubject),submissions=await deps.repository.listSubmissionObservations(request.executionId,request.actorSubject);if(commitment||submissions.length>0)throw new Error("E6B refresh is forbidden after the submission boundary or provider contact.");assertPrior(request,prior);
  const cipher=new Aes256GcmPreparedTransactionCipher(request.config.encryptionKey!,request.config.encryptionKeyVersion!);authenticate(cipher,prior);
  const signer=new InjectedDevnetTransactionSigner({secretKey:request.config.signerSecretKey!,keyId:request.config.signerKeyId!,keyVersion:request.config.signerKeyVersion!,publicKey:request.config.signerPublicKey!}),rpc=new SingleAttemptDevnetJsonRpc(request.config.reconciliationUrl!,request.config.requestTimeoutMs,deps.fetch),blocks=new ReconciliationDevnetBlockDataSource(rpc),reconciliation:DevnetReconciliationProvider=Object.freeze({identity:Object.freeze({providerId:request.config.reconciliationProviderId!,network:"devnet",role:"reconciliation"}),async observeSignature(){throw new Error("E6B refresh cannot reconcile.");}}),submission:SolanaSubmissionRpc=Object.freeze({identity:Object.freeze({providerId:request.config.submissionProviderId!,network:"devnet",role:"submission"}),async submitExactSignedTransaction(){throw new Error("E6B refresh cannot submit.");}}),service=new DevnetOrchestrationService(deps.repository,cipher,{cluster:"solana-devnet",asset:"USDC",mint:request.config.mint!,decimals:request.config.decimals!,sourceTokenAccount:request.config.sourceTokenAccount!,policyHash:request.expectedPolicyHash,submissionProviderId:request.config.submissionProviderId!,reconciliationProviderId:request.config.reconciliationProviderId!},blocks,signer,blocks,reconciliation,submission,{submissionEnabled:false,reconciliationEnabled:false}),command=commandFor(request,execution!.providerIdempotencyKey),replacement=await service.refreshExpiredPreContact(request.executionId,request.actorSubject,request.replacementPreparationId,command),authenticated=await service.loadRuntimePreparation(request.executionId,request.actorSubject);
  if(!authenticated||authenticated.signedTransactionDigest!==replacement.artifact.signedTransactionDigest||replacement.state!=="PREPARED_NOT_CONTACTED"||replacement.generation!==prior.generation+1)throw new Error("E6B refresh replacement could not be authenticated.");if(await deps.repository.findCommitment(request.executionId,request.actorSubject)||(await deps.repository.listSubmissionObservations(request.executionId,request.actorSubject)).length>0)throw new Error("E6B refresh crossed the submission boundary.");
  const a=replacement.artifact;return Object.freeze({verdict:"REFRESHED_PRE_CONTACT",executionId:replacement.executionId,priorPreparationId:prior.preparationId,priorGeneration:prior.generation,replacementPreparationId:replacement.preparationId,replacementGeneration:replacement.generation,mint:a.mint,sourceTokenAccount:a.sourceTokenAccount,destination:a.destination,rawAmount:a.rawAmount,decimals:a.decimals,canonicalPolicyHash:a.policyHash,signerPublicKey:a.signerPublicKey,signerKeyId:a.signerKeyId,signerKeyVersion:a.signerKeyVersion,recentBlockhash:a.recentBlockhash,lastValidBlockHeight:a.lastValidBlockHeight,signedTransactionDigest:a.signedTransactionDigest,transactionSignature:a.signature,durableState:"PREPARED_NOT_CONTACTED",submissionCommitmentCount:0,submissionObservationCount:0,sendTransactionCalls:0,rpcMethods:Object.freeze(["getBlockHeight","getLatestBlockhash"]as const)});
}
export function postgresE6bRefreshDependencies(pool:Pool,request:E6bRefreshRequest,fetch:JsonRpcFetch=globalThis.fetch as JsonRpcFetch):E6bRefreshDependencies{return{repository:new PostgresDevnetExecutionStateRepository(pool),fetch,async loadExecution(){const result=await pool.query("SELECT payment_intent_id,actor_subject,execution_mode,selected_rail,settlement_network,policy_hash,provider_idempotency_key FROM payment_executions WHERE execution_id=$1",[request.executionId]),row=result.rows[0];return row?Object.freeze({paymentIntentId:String(row.payment_intent_id),actorSubject:String(row.actor_subject),executionMode:String(row.execution_mode),rail:String(row.selected_rail),network:String(row.settlement_network),policyHash:Buffer.from(row.policy_hash??[]).toString("hex"),providerIdempotencyKey:String(row.provider_idempotency_key)}):undefined;}};}
function assertExecution(r:E6bRefreshRequest,e:E6bRefreshExecution|undefined){if(!e||e.paymentIntentId!==r.paymentIntentId||e.actorSubject!==r.actorSubject||e.executionMode!=="devnet_validation"||e.rail!=="solana"||e.network!=="solana-devnet"||e.policyHash!==r.expectedPolicyHash)throw new Error("E6B refresh execution does not match operator expectations.");}
function assertPrior(r:E6bRefreshRequest,p:PersistedDevnetPreparation){const a=p.artifact,c=r.config;if(p.preparationId!==r.existingPreparationId||p.generation!==r.existingGeneration||p.state!=="PREPARED_NOT_CONTACTED"||p.paymentIntentId!==r.paymentIntentId||a.cluster!=="solana-devnet"||a.policyHash!==r.expectedPolicyHash||a.mint!==c.mint||a.decimals!==c.decimals||a.sourceTokenAccount!==c.sourceTokenAccount||a.destination!==r.destination||a.rawAmount!==r.rawAmount||a.signerKeyId!==c.signerKeyId||a.signerKeyVersion!==c.signerKeyVersion||a.signerPublicKey!==c.signerPublicKey||a.submissionProviderId!==c.submissionProviderId||a.reconciliationProviderId!==c.reconciliationProviderId)throw new Error("E6B refresh preparation does not match operator expectations.");}
function authenticate(cipher:Aes256GcmPreparedTransactionCipher,p:PersistedDevnetPreparation){const value=cipher.decrypt(p.encryptedSignedTransaction,{executionId:p.executionId,preparationId:p.preparationId,keyVersion:p.encryptedSignedTransaction.keyVersion});if(signedTransactionDigest(value)!==p.artifact.signedTransactionDigest)throw new Error("E6B refresh authenticated bytes do not match persisted digest.");}
function commandFor(r:E6bRefreshRequest,providerIdempotencyKey:string):RailExecutionCommand{return{schemaVersion:1,requestId:`request:e6b-refresh:${r.replacementPreparationId}`,correlationId:`payment:e6b-refresh:${r.paymentIntentId}`,executionId:r.executionId,paymentIntentId:r.paymentIntentId,transactionId:r.executionId,requestedAt:new Date().toISOString(),actorId:`actor:e6b-refresh:${r.actorSubject}`,recipientId:`recipient:e6b-refresh:${r.destination}`,amount:{asset:"USDC",units:r.rawAmount,decimals:r.config.decimals!},destination:{type:"wallet",network:"solana-devnet",address:r.destination},rail:"solana",providerIdempotencyKey}as RailExecutionCommand;}
function required(env:Environment,name:string){const value=env[name]?.trim();if(!value)throw new Error(`${name} is required for E6B refresh.`);return value;}function integer(value:string){const n=Number(value);if(!Number.isSafeInteger(n)||n<1)throw new Error("E6B refresh generation is invalid.");return n;}function hex(value:string){if(!/^[a-f0-9]{64}$/.test(value))throw new Error("E6B refresh policy hash is invalid.");return value;}function publicKey(value:string){let key:PublicKey;try{key=new PublicKey(value);}catch{throw new Error("E6B refresh destination is invalid.");}if(key.toBase58()!==value)throw new Error("E6B refresh destination is invalid.");return value;}function localDatabaseUrl(value:string){let url:URL;try{url=new URL(value);}catch{throw new Error("E6B refresh database URL is invalid.");}const host=url.hostname.replace(/^\[|\]$/g,"");if(!["127.0.0.1","localhost","::1"].includes(host)||!["postgres:","postgresql:"].includes(url.protocol)||!url.pathname.slice(1))throw new Error("E6B refresh requires an explicit loopback PostgreSQL URL.");return value;}
