import { randomUUID } from "node:crypto";
import { PublicKey } from "@solana/web3.js";
import type { Pool } from "pg";
import { classifyDevnetBlockhash, signedTransactionDigest, type RailExecutionCommand, type SolanaSubmissionRpc } from "zephyon-protocol";
import { SingleAttemptDevnetJsonRpc, type JsonRpcFetch } from "../adapters/solana/devnetJsonRpc";
import { HeliusDevnetSubmissionRpc, IndependentDevnetReconciliationRpc, ReconciliationDevnetBlockDataSource } from "../adapters/solana/liveDevnetProviders";
import { PostgresDevnetExecutionStateRepository } from "../storage/postgres/postgresDevnetExecutionStateRepository";
import { CIRCLE_SOLANA_DEVNET_USDC_DECIMALS, CIRCLE_SOLANA_DEVNET_USDC_MINT } from "./canonicalDevnetAsset";
import { parseDevnetLiveConfiguration, type DevnetLiveConfiguration } from "./devnetLiveConfiguration";
import type { DevnetExecutionStateRepository, PersistedDevnetPreparation } from "./devnetExecutionState";
import { DevnetOrchestrationService } from "./devnetOrchestrationService";
import { deriveDevnetAssociatedSourceTokenAccount, devnetPreparationPolicy, hashDevnetPolicy } from "./devnetPreparationPolicy";
import { InjectedDevnetTransactionSigner } from "./injectedDevnetSigner";
import { Aes256GcmPreparedTransactionCipher } from "./preparedTransactionCipher";

type Environment=Readonly<Record<string,string|undefined>>;
export type E6FinalExecution=Readonly<{paymentIntentId:string;actorSubject:string;executionMode:string;rail:string;network:string;policyHash:string;providerIdempotencyKey:string}>;
export type E6FinalRequest=Readonly<{config:DevnetLiveConfiguration;databaseUrl:string;actorSubject:string;paymentIntentId:string;executionId:string;currentPreparationId:string;currentGeneration:number;currentDigest:string;currentSignature:string;replacementPreparationId:string;commitmentId:string;expectedPolicyHash:string;destination:string;rawAmount:string;expectedSignerPublicKey:string;expectedSignerKeyId:string;expectedSignerKeyVersion:string;expectedSourceTokenAccount:string;expectedMint:string;expectedDecimals:number}>;
export type E6FinalDependencies=Readonly<{repository:DevnetExecutionStateRepository;loadExecution():Promise<E6FinalExecution|undefined>;fetch:JsonRpcFetch;afterRefresh?():Promise<void>;clock?:()=>string;idFactory?:()=>string}>;
export type E6FinalResult=Readonly<{verdict:"SUBMISSION_ATTEMPTED"|"RECONCILIATION_ONLY";oldPreparationId:string;oldGeneration:number;oldState:"PREPARED_NOT_CONTACTED";refreshed:boolean;newPreparationId:string;newGeneration:number;lastValidBlockHeight:string;freshDigest:string;freshTransactionSignature:string;commitmentId:string;submissionProviderId:"helius-devnet-submit";providerCallCount:number;typedSubmissionOutcome:"ACCEPTED"|"REJECTED"|"UNKNOWN_RECONCILIATION_REQUIRED"|"NOT_ATTEMPTED";contactCertainty:"ACCEPTED"|"MAY_HAVE_OCCURRED"|"NOT_STARTED";resultingDurableState:string;reconciliationRequired:boolean;rpcMethods:readonly string[];providerStatus:string}>;
const CONFIRMATION="REFRESH_AND_SUBMIT_EXACT_DEVNET_TRANSACTION_ONCE",SUBMISSION_PROVIDER="helius-devnet-submit",RECONCILIATION_PROVIDER="solana-public-devnet-reconcile";

export function parseE6FinalRequest(env:Environment=process.env):E6FinalRequest{
  if(env.E6_FINAL_OPERATOR_CONFIRMATION!==CONFIRMATION)throw new Error("E6 final exact operator confirmation is required.");const config=parseDevnetLiveConfiguration(env);
  if(!config.enabled||!config.preparationEnabled||!config.reconciliationEnabled||!config.submissionEnabled)throw new Error("E6 final requires integration, preparation, reconciliation, and submission enabled.");
  if(config.submissionProviderId!==SUBMISSION_PROVIDER||config.reconciliationProviderId!==RECONCILIATION_PROVIDER||!config.submissionUrl||!config.submissionApiKey||!config.reconciliationUrl||!config.encryptionKey||!config.encryptionKeyVersion||!config.signerSecretKey||!config.signerKeyId||!config.signerKeyVersion||!config.signerPublicKey||!config.mint||config.decimals===undefined||!config.sourceTokenAccount)throw new Error("E6 final configuration or provider identity is invalid.");
  const expectedSignerPublicKey=publicKey(required(env,"E6_FINAL_EXPECTED_SIGNER_PUBLIC_KEY")),expectedSourceTokenAccount=publicKey(required(env,"E6_FINAL_EXPECTED_SOURCE_ATA")),expectedMint=publicKey(required(env,"E6_FINAL_EXPECTED_MINT")),expectedDecimals=integer(required(env,"E6_FINAL_EXPECTED_DECIMALS"),0),expectedSignerKeyId=required(env,"E6_FINAL_EXPECTED_SIGNER_KEY_ID"),expectedSignerKeyVersion=required(env,"E6_FINAL_EXPECTED_SIGNER_KEY_VERSION");
  if(expectedMint!==CIRCLE_SOLANA_DEVNET_USDC_MINT||expectedDecimals!==CIRCLE_SOLANA_DEVNET_USDC_DECIMALS||expectedSignerPublicKey!==config.signerPublicKey||expectedSignerKeyId!==config.signerKeyId||expectedSignerKeyVersion!==config.signerKeyVersion||expectedSourceTokenAccount!==config.sourceTokenAccount||expectedMint!==config.mint||expectedDecimals!==config.decimals||deriveDevnetAssociatedSourceTokenAccount(expectedMint,expectedSignerPublicKey)!==expectedSourceTokenAccount)throw new Error("E6 final canonical signer economics do not match configuration.");
  const expectedPolicyHash=hex(required(env,"E6_FINAL_EXPECTED_POLICY_HASH")),canonical=hashDevnetPolicy(devnetPreparationPolicy({mint:expectedMint,decimals:expectedDecimals,sourceTokenAccount:expectedSourceTokenAccount,signerKeyId:expectedSignerKeyId,signerKeyVersion:expectedSignerKeyVersion,signerPublicKey:expectedSignerPublicKey,submissionProviderId:SUBMISSION_PROVIDER,reconciliationProviderId:RECONCILIATION_PROVIDER}));if(canonical!==expectedPolicyHash)throw new Error("E6 final canonical policy mismatch.");
  const rawAmount=required(env,"E6_FINAL_EXPECTED_RAW_AMOUNT");if(rawAmount!=="1000")throw new Error("E6 final requires exactly 1000 raw units.");const currentPreparationId=uuid(required(env,"E6_FINAL_CURRENT_PREPARATION_ID")),replacementPreparationId=uuid(required(env,"E6_FINAL_REPLACEMENT_PREPARATION_ID"));if(currentPreparationId===replacementPreparationId)throw new Error("E6 final replacement preparation ID must be new.");
  return Object.freeze({config,databaseUrl:localDatabaseUrl(required(env,"E6_FINAL_DATABASE_URL")),actorSubject:required(env,"E6_FINAL_ACTOR_SUBJECT"),paymentIntentId:uuid(required(env,"E6_FINAL_PAYMENT_ID")),executionId:uuid(required(env,"E6_FINAL_EXECUTION_ID")),currentPreparationId,currentGeneration:integer(required(env,"E6_FINAL_CURRENT_GENERATION"),1),currentDigest:hex(required(env,"E6_FINAL_CURRENT_SIGNED_TRANSACTION_DIGEST")),currentSignature:required(env,"E6_FINAL_CURRENT_TRANSACTION_SIGNATURE"),replacementPreparationId,commitmentId:uuid(required(env,"E6_FINAL_COMMITMENT_ID")),expectedPolicyHash,destination:publicKey(required(env,"E6_FINAL_EXPECTED_DESTINATION")),rawAmount,expectedSignerPublicKey,expectedSignerKeyId,expectedSignerKeyVersion,expectedSourceTokenAccount,expectedMint,expectedDecimals});
}

export async function runE6FinalRefreshAndSubmit(request:E6FinalRequest,deps:E6FinalDependencies):Promise<E6FinalResult>{
  const execution=await deps.loadExecution();assertExecution(request,execution);const initial=await deps.repository.findPreparation(request.executionId,request.actorSubject);if(!initial)throw new Error("E6 final preparation was not found for this owner.");const existingCommitment=await deps.repository.findCommitment(request.executionId,request.actorSubject),existingObservations=await deps.repository.listSubmissionObservations(request.executionId,request.actorSubject);assertPreparation(request,initial,request.currentPreparationId,request.currentGeneration,request.currentDigest,request.currentSignature);const cipher=new Aes256GcmPreparedTransactionCipher(request.config.encryptionKey!,request.config.encryptionKeyVersion!);authenticate(cipher,initial);
  if(existingCommitment||initial.state!=="PREPARED_NOT_CONTACTED"||existingObservations.length>0)return finalResult(request,initial,false,"RECONCILIATION_ONLY",0,"NOT_ATTEMPTED","NOT_STARTED",[],"RECONCILIATION_ONLY");if(!request.config.submissionEnabled)throw new Error("E6 final submission capability is disabled.");
  const rpcMethods:string[]=[],fetch:JsonRpcFetch=async(url,init)=>{const method=boundedMethod(init.body);rpcMethods.push(method);return deps.fetch(url,init);},reconciliationRpc=new SingleAttemptDevnetJsonRpc(request.config.reconciliationUrl!,request.config.requestTimeoutMs,fetch),blocks=new ReconciliationDevnetBlockDataSource(reconciliationRpc),currentHeight=await blocks.getCurrentDevnetBlockHeight(),disposition=classifyDevnetBlockhash(initial.state,initial.artifact.lastValidBlockHeight,currentHeight);
  const signer=new InjectedDevnetTransactionSigner({secretKey:request.config.signerSecretKey!,keyId:request.expectedSignerKeyId,keyVersion:request.expectedSignerKeyVersion,publicKey:request.expectedSignerPublicKey}),submissionRpc=new SingleAttemptDevnetJsonRpc(request.config.submissionUrl!,request.config.requestTimeoutMs,fetch,request.config.submissionApiKey),helius=new HeliusDevnetSubmissionRpc(SUBMISSION_PROVIDER,submissionRpc),reconciliation=new IndependentDevnetReconciliationRpc(RECONCILIATION_PROVIDER,reconciliationRpc);let providerCalls=0;const counted:SolanaSubmissionRpc=Object.freeze({identity:helius.identity,async submitExactSignedTransaction(bytes:Uint8Array){providerCalls++;return helius.submitExactSignedTransaction(bytes);}}),cachedHeight=Object.freeze({async getCurrentDevnetBlockHeight(){return currentHeight;}}),service=new DevnetOrchestrationService(deps.repository,cipher,{cluster:"solana-devnet",asset:"USDC",mint:request.expectedMint,decimals:request.expectedDecimals,sourceTokenAccount:request.expectedSourceTokenAccount,policyHash:request.expectedPolicyHash,submissionProviderId:SUBMISSION_PROVIDER,reconciliationProviderId:RECONCILIATION_PROVIDER},blocks,signer,cachedHeight,reconciliation,counted,{submissionEnabled:true,reconciliationEnabled:true},deps.clock,deps.idFactory??randomUUID),command=commandFor(request,execution!.providerIdempotencyKey);let active=initial,refreshed=false;
  if(disposition==="SAFE_TO_PREPARE_FRESH"){active=await service.refreshExpiredPreContact(request.executionId,request.actorSubject,request.replacementPreparationId,command);refreshed=true;if(deps.afterRefresh)await deps.afterRefresh();}else if(disposition!=="VALID")throw new Error("E6 final committed preparation is reconciliation-only.");
  const reloaded=await deps.repository.findPreparation(request.executionId,request.actorSubject);if(!reloaded||reloaded.preparationId!==active.preparationId||reloaded.generation!==(refreshed?initial.generation+1:initial.generation)||reloaded.state!=="PREPARED_NOT_CONTACTED")throw new Error("E6 final active preparation changed before commitment.");assertEconomics(request,reloaded);authenticate(cipher,reloaded);if(await deps.repository.findCommitment(request.executionId,request.actorSubject)||(await deps.repository.listSubmissionObservations(request.executionId,request.actorSubject)).length>0)throw new Error("E6 final submission boundary changed before authorization.");
  const submitted=await service.submitPrepared({executionId:request.executionId,actorSubject:request.actorSubject,commitmentId:request.commitmentId,providerIdempotencyKey:execution!.providerIdempotencyKey});if(!submitted.attempted)return finalResult(request,submitted.preparation,refreshed,"RECONCILIATION_ONLY",providerCalls,"NOT_ATTEMPTED","NOT_STARTED",rpcMethods,String(submitted.reason));const outcome=submitted.observation.outcome==="ACCEPTED"||submitted.observation.outcome==="SETTLED"?"ACCEPTED":submitted.observation.outcome==="REJECTED"?"REJECTED":"UNKNOWN_RECONCILIATION_REQUIRED";return finalResult(request,submitted.preparation,refreshed,"SUBMISSION_ATTEMPTED",providerCalls,outcome,submitted.observation.contactCertainty,rpcMethods,submitted.observation.providerErrorCode??outcome);
}
export function postgresE6FinalDependencies(pool:Pool,request:E6FinalRequest,fetch:JsonRpcFetch=globalThis.fetch as JsonRpcFetch):E6FinalDependencies{return{repository:new PostgresDevnetExecutionStateRepository(pool),fetch,async loadExecution(){const result=await pool.query("SELECT payment_intent_id,actor_subject,execution_mode,selected_rail,settlement_network,policy_hash,provider_idempotency_key FROM payment_executions WHERE execution_id=$1",[request.executionId]),row=result.rows[0];return row?Object.freeze({paymentIntentId:String(row.payment_intent_id),actorSubject:String(row.actor_subject),executionMode:String(row.execution_mode),rail:String(row.selected_rail),network:String(row.settlement_network),policyHash:Buffer.from(row.policy_hash??[]).toString("hex"),providerIdempotencyKey:String(row.provider_idempotency_key)}):undefined;}};}
function assertExecution(r:E6FinalRequest,e:E6FinalExecution|undefined){if(!e||e.paymentIntentId!==r.paymentIntentId||e.actorSubject!==r.actorSubject||e.executionMode!=="devnet_validation"||e.rail!=="solana"||e.network!=="solana-devnet"||e.policyHash!==r.expectedPolicyHash)throw new Error("E6 final execution does not match operator expectations.");}
function assertPreparation(r:E6FinalRequest,p:PersistedDevnetPreparation,id:string,generation:number,digest:string,signature:string){if(p.preparationId!==id||p.generation!==generation||p.artifact.signedTransactionDigest!==digest||p.artifact.signature!==signature)throw new Error("E6 final current preparation identity does not match operator expectations.");assertEconomics(r,p);}
function assertEconomics(r:E6FinalRequest,p:PersistedDevnetPreparation){const a=p.artifact;if(p.paymentIntentId!==r.paymentIntentId||p.actorSubject!==r.actorSubject||a.cluster!=="solana-devnet"||a.policyHash!==r.expectedPolicyHash||a.mint!==r.expectedMint||a.decimals!==r.expectedDecimals||a.sourceTokenAccount!==r.expectedSourceTokenAccount||a.destination!==r.destination||a.rawAmount!==r.rawAmount||a.signerPublicKey!==r.expectedSignerPublicKey||a.signerKeyId!==r.expectedSignerKeyId||a.signerKeyVersion!==r.expectedSignerKeyVersion||a.submissionProviderId!==SUBMISSION_PROVIDER||a.reconciliationProviderId!==RECONCILIATION_PROVIDER)throw new Error("E6 final preparation economics do not match operator expectations.");}
function authenticate(cipher:Aes256GcmPreparedTransactionCipher,p:PersistedDevnetPreparation){const value=cipher.decrypt(p.encryptedSignedTransaction,{executionId:p.executionId,preparationId:p.preparationId,keyVersion:p.encryptedSignedTransaction.keyVersion});if(signedTransactionDigest(value)!==p.artifact.signedTransactionDigest)throw new Error("E6 final authenticated bytes do not match persisted digest.");}
function commandFor(r:E6FinalRequest,providerIdempotencyKey:string):RailExecutionCommand{return{schemaVersion:1,requestId:`request:e6-final:${r.replacementPreparationId}`,correlationId:`payment:e6-final:${r.paymentIntentId}`,executionId:r.executionId,paymentIntentId:r.paymentIntentId,transactionId:r.executionId,requestedAt:new Date().toISOString(),actorId:`actor:e6-final:${r.actorSubject}`,recipientId:`recipient:e6-final:${r.destination}`,amount:{asset:"USDC",units:r.rawAmount,decimals:r.expectedDecimals},destination:{type:"wallet",network:"solana-devnet",address:r.destination},rail:"solana",providerIdempotencyKey}as RailExecutionCommand;}
function finalResult(r:E6FinalRequest,p:PersistedDevnetPreparation,refreshed:boolean,verdict:E6FinalResult["verdict"],calls:number,outcome:E6FinalResult["typedSubmissionOutcome"],certainty:E6FinalResult["contactCertainty"],methods:string[],status:string):E6FinalResult{return Object.freeze({verdict,oldPreparationId:r.currentPreparationId,oldGeneration:r.currentGeneration,oldState:"PREPARED_NOT_CONTACTED",refreshed,newPreparationId:p.preparationId,newGeneration:p.generation,lastValidBlockHeight:p.artifact.lastValidBlockHeight,freshDigest:p.artifact.signedTransactionDigest,freshTransactionSignature:p.artifact.signature,commitmentId:r.commitmentId,submissionProviderId:SUBMISSION_PROVIDER,providerCallCount:calls,typedSubmissionOutcome:outcome,contactCertainty:certainty,resultingDurableState:p.state,reconciliationRequired:p.state!=="PREPARED_NOT_CONTACTED",rpcMethods:Object.freeze([...methods]),providerStatus:status.slice(0,128)});}
function boundedMethod(body:string){try{const method=JSON.parse(body).method;if(typeof method==="string"&&method.length<=64)return method;}catch{}throw new Error("E6 final RPC request method is invalid.");}function required(env:Environment,name:string){const value=env[name]?.trim();if(!value)throw new Error(`${name} is required for E6 final.`);return value;}function integer(value:string,min:number){const n=Number(value);if(!Number.isSafeInteger(n)||n<min)throw new Error("E6 final integer expectation is invalid.");return n;}function hex(value:string){if(!/^[a-f0-9]{64}$/.test(value))throw new Error("E6 final digest or policy hash is invalid.");return value;}function uuid(value:string){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value))throw new Error("E6 final identifier must be a UUID.");return value;}function publicKey(value:string){let key:PublicKey;try{key=new PublicKey(value);}catch{throw new Error("E6 final public key expectation is invalid.");}if(key.toBase58()!==value)throw new Error("E6 final public key expectation is invalid.");return value;}function localDatabaseUrl(value:string){let url:URL;try{url=new URL(value);}catch{throw new Error("E6 final database URL is invalid.");}const host=url.hostname.replace(/^\[|\]$/g,"");if(!["127.0.0.1","localhost","::1"].includes(host)||!["postgres:","postgresql:"].includes(url.protocol)||!url.pathname.slice(1))throw new Error("E6 final requires an explicit loopback PostgreSQL URL.");return value;}
