import type{DevnetTransactionSigner,SolanaSubmissionRpc}from"zephyon-protocol";import{SingleAttemptDevnetJsonRpc,type JsonRpcFetch}from"../adapters/solana/devnetJsonRpc";import{HeliusDevnetSubmissionRpc,IndependentDevnetReconciliationRpc,ReconciliationDevnetBlockDataSource}from"../adapters/solana/liveDevnetProviders";import{AdaptiveWorkerLoop,RECONCILIATION_POLL_DELAYS_MS}from"../executions/adaptiveWorkerLoop";import{Aes256GcmPreparedTransactionCipher}from"./preparedTransactionCipher";import type{DevnetExecutionStateRepository}from"./devnetExecutionState";import{DevnetOrchestrationService}from"./devnetOrchestrationService";import type{DevnetRecoveryHandlers,DevnetRecoveryOperationalEvent}from"./devnetRecoveryWorker";import{DevnetRecoveryWorker}from"./devnetRecoveryWorker";import type{DevnetRecoveryRepository}from"./devnetRecoveryRepository";import type{DevnetLiveConfiguration}from"./devnetLiveConfiguration";import{InjectedDevnetTransactionSigner}from"./injectedDevnetSigner";import{devnetPreparationPolicy,hashDevnetPolicy}from"./devnetPreparationPolicy";import{DevnetReconciliationService}from"./devnetReconciliationService";
export type LiveDevnetComposition=Readonly<{orchestration?:DevnetOrchestrationService;reconciliation?:DevnetReconciliationService;recoveryWorker:DevnetRecoveryWorker;workerLoop:AdaptiveWorkerLoop;submissionProvider?:HeliusDevnetSubmissionRpc;reconciliationProvider?:IndependentDevnetReconciliationRpc;blockDataSource?:ReconciliationDevnetBlockDataSource}>;
export type LiveDevnetCompositionDependencies=Readonly<{executionState:DevnetExecutionStateRepository;recoveryRepository:DevnetRecoveryRepository;signer?:DevnetTransactionSigner;recoveryHandlers:DevnetRecoveryHandlers;recoveryObserver?:(event:DevnetRecoveryOperationalEvent)=>void;fetch?:JsonRpcFetch;workerId:string}>;
/** Internal, inert composition. Construction never starts polling or performs RPC. */
export function createLiveDevnetComposition(config:DevnetLiveConfiguration,deps:LiveDevnetCompositionDependencies):LiveDevnetComposition{
  if(!config.enabled)throw new Error("Live Devnet composition requires enabled configuration.");
  const submissionRpc=config.submissionUrl?new SingleAttemptDevnetJsonRpc(config.submissionUrl,config.requestTimeoutMs,deps.fetch,config.submissionApiKey):undefined,reconciliationRpc=config.reconciliationUrl?new SingleAttemptDevnetJsonRpc(config.reconciliationUrl,config.requestTimeoutMs,deps.fetch):undefined;
  const submissionProvider=submissionRpc?new HeliusDevnetSubmissionRpc(config.submissionProviderId!,submissionRpc):undefined,reconciliationProvider=reconciliationRpc?new IndependentDevnetReconciliationRpc(config.reconciliationProviderId!,reconciliationRpc):undefined,blockDataSource=reconciliationRpc?new ReconciliationDevnetBlockDataSource(reconciliationRpc):undefined;
  const reconciliation=config.reconciliationEnabled&&reconciliationProvider?new DevnetReconciliationService(deps.executionState,reconciliationProvider,config.reconciliationProviderId!):undefined;
  let orchestration:DevnetOrchestrationService|undefined;
  if(config.preparationEnabled){if(!reconciliationProvider||!blockDataSource)throw new Error("Preparation requires reconciliation-side Devnet block infrastructure.");const signer=signerBoundary(config,deps.signer),policy=devnetPreparationPolicy({mint:config.mint!,decimals:config.decimals!,sourceTokenAccount:config.sourceTokenAccount!,signerKeyId:config.signerKeyId!,signerKeyVersion:config.signerKeyVersion!,signerPublicKey:config.signerPublicKey!,submissionProviderId:config.submissionProviderId!,reconciliationProviderId:config.reconciliationProviderId!}),authoritativeSubmission:SolanaSubmissionRpc=submissionProvider??Object.freeze({identity:Object.freeze({providerId:config.submissionProviderId!,network:"devnet" as const,role:"submission" as const}),async submitExactSignedTransaction():Promise<never>{throw new Error("Devnet submission infrastructure is not configured.");}});orchestration=new DevnetOrchestrationService(deps.executionState,new Aes256GcmPreparedTransactionCipher(config.encryptionKey!,config.encryptionKeyVersion!),Object.freeze({cluster:"solana-devnet",asset:"USDC",mint:policy.mint,decimals:policy.decimals,sourceTokenAccount:policy.sourceTokenAccount,policyHash:hashDevnetPolicy(policy),submissionProviderId:policy.providers.submission,reconciliationProviderId:policy.providers.reconciliation}),blockDataSource,signer,blockDataSource,reconciliationProvider,authoritativeSubmission,{submissionEnabled:config.submissionEnabled,reconciliationEnabled:config.reconciliationEnabled});}
  const recoveryWorker=new DevnetRecoveryWorker(deps.recoveryRepository,deps.recoveryHandlers,deps.workerId,{preparationEnabled:config.preparationEnabled,reconciliationEnabled:config.reconciliationEnabled},undefined,undefined,deps.recoveryObserver),workerLoop=new AdaptiveWorkerLoop(()=>recoveryWorker.iterate(),undefined,undefined,undefined,RECONCILIATION_POLL_DELAYS_MS);return Object.freeze({...(orchestration?{orchestration}:{}),...(reconciliation?{reconciliation}:{}),recoveryWorker,workerLoop,...(submissionProvider?{submissionProvider}:{}),...(reconciliationProvider?{reconciliationProvider}:{}),...(blockDataSource?{blockDataSource}:{})});
}
function signerBoundary(config:DevnetLiveConfiguration,delegate?:DevnetTransactionSigner):DevnetTransactionSigner{const signer=delegate??(config.signerSecretKey?new InjectedDevnetTransactionSigner({secretKey:config.signerSecretKey,keyId:config.signerKeyId!,keyVersion:config.signerKeyVersion!,publicKey:config.signerPublicKey!}):undefined);if(!signer)throw new Error("An externally injected server-side Devnet signer is required when preparation is enabled.");if(signer.keyId!==config.signerKeyId||signer.keyVersion!==config.signerKeyVersion||signer.publicKey!==config.signerPublicKey)throw new Error("Injected Devnet signer identity does not match configured metadata.");return signer;}
