import { execFile, execFileSync } from "node:child_process";
import { generateKeyPairSync, randomBytes } from "node:crypto";
import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { createServer } from "node:net";
import path from "node:path";
import { promisify } from "node:util";
import { Pool } from "pg";
import { exportJWK, SignJWT } from "jose";
import { PAYMENT_POSTGRES_POOL_CONFIG } from "../../src/storage/postgres/postgresPool";
import { verifyEconomicInvariants } from "./invariants";
import { certificationReport, type RunManifest } from "./report";
import { controlDisposableDatabase, saturatePool, triggerStatementTimeout } from "./faults";
import { AdaptiveWorkerLoop } from "../../src/executions/adaptiveWorkerLoop";
import { PaymentExecutionWorker } from "../../src/executions/executionWorker";
import { PostgresExecutionRepository } from "../../src/storage/postgres/postgresExecutionRepository";
import { PostgresPaymentPersistence } from "../../src/storage/postgres/postgresPaymentPersistence";

const exec=promisify(execFile);
async function main():Promise<void>{
const root=path.resolve(process.cwd());
const requestedScenario=process.argv[2]??"stage0";if(!["stage0","smoke","baseline-read","baseline-write","stage2-read","fault-gates"].includes(requestedScenario))throw new Error(`Unknown R4 scenario ${requestedScenario}.`);const scenario=requestedScenario;const seed=process.env.R4_SEED?.trim()||`r4-${scenario}`;
const adminUrl=process.env.R4_ADMIN_DATABASE_URL?.trim();if(!adminUrl)throw new Error("R4_ADMIN_DATABASE_URL is required and must name a disposable local PostgreSQL service.");
const parsedAdmin=new URL(adminUrl);if(!["127.0.0.1","localhost"].includes(parsedAdmin.hostname))throw new Error("R4 database must be local.");
const database=`r4_${Date.now()}_${randomBytes(4).toString("hex")}`;const databaseUrl=new URL(adminUrl);databaseUrl.pathname=`/${database}`;
const artifactDir=path.join(root,".artifacts","r4",`${new Date().toISOString().replace(/[:.]/g,"-")}-${scenario}`);const temporary=await mkdtemp(path.join(tmpdir(),"zephipay-r4-"));
const admin=new Pool({connectionString:adminUrl,max:1});let backend:Awaited<typeof import("../../src/server")>["runningBackend"]|undefined;let databasePool:Pool|undefined;
const backendStdout:string[]=[],backendStderr:string[]=[],resourceSamples:unknown[]=[],postgresSamples:unknown[]=[];const originalLog=console.log,originalInfo=console.info,originalWarn=console.warn,originalError=console.error;let sampleTimer:ReturnType<typeof setInterval>|undefined;
try{
  await mkdir(artifactDir,{recursive:true});await admin.query(`CREATE DATABASE "${database}"`);
  databasePool=new Pool({connectionString:databaseUrl.toString(),max:2});
  const migrationFiles=(await readdir(path.join(root,"migrations"))).filter(name=>/^\d{3}_.+\.sql$/.test(name)).sort();
  if(migrationFiles.length!==11)throw new Error(`Expected 11 migrations, found ${migrationFiles.length}.`);
  for(const file of migrationFiles)await databasePool.query(await readFile(path.join(root,"migrations",file),"utf8"));
  const {privateKey,publicKey}=generateKeyPairSync("rsa",{modulusLength:2048});const publicJwk={...(await exportJWK(publicKey)),alg:"RS256",kid:"r4-local"};
  const localPort=await availablePort();process.env.NODE_ENV="test";process.env.PORT=String(localPort);process.env.POSTGRES_ENABLED="true";process.env.DATABASE_URL=databaseUrl.toString();process.env.AUTH_ENABLED="true";process.env.AUTH0_ISSUER="https://r4.local.test/";process.env.AUTH0_AUDIENCE="https://api.r4.local.test";process.env.PAYMENTS_ENABLED="false";process.env.SYNTHETIC_BETA_IDENTITIES_ENABLED="false";process.env.SVM_ADDRESS="2w2nqMemQzjwKMk3jEmtXnBqGBXGJLs8FNfb5Khb8E7J";
  console.log=(...values:unknown[])=>{backendStdout.push(logLine(values));originalLog(...values);};console.info=(...values:unknown[])=>{backendStdout.push(logLine(values));originalInfo(...values);};console.warn=(...values:unknown[])=>{backendStderr.push(logLine(values));originalWarn(...values);};console.error=(...values:unknown[])=>{backendStderr.push(logLine(values));originalError(...values);};const compiledAuth=require(path.join(root,"dist/auth/localHarnessAuth.js")) as typeof import("../../src/auth/localHarnessAuth");compiledAuth.configureLocalHarnessAuth({publicKey:publicJwk});backend=(require(path.join(root,"dist/server.js")) as typeof import("../../src/server")).runningBackend;
  if(!backend.server.listening)await new Promise<void>(resolve=>backend!.server.once("listening",resolve));const address=backend.server.address();if(!address||typeof address==="string")throw new Error("R4 backend did not bind a local TCP port.");const base=`http://127.0.0.1:${address.port}`;
  const sample=async()=>{const at=new Date().toISOString();resourceSamples.push({at,cpu:process.cpuUsage(),memory:process.memoryUsage(),pool:{total:backend!.postgresPool?.totalCount,idle:backend!.postgresPool?.idleCount,waiting:backend!.postgresPool?.waitingCount}});try{postgresSamples.push({at,...(await databasePool!.query("SELECT count(*)::int connections,count(*) FILTER (WHERE state='active')::int active FROM pg_stat_activity WHERE datname=current_database()")).rows[0]});}catch{/* Teardown may overlap the last sample. */}};await sample();sampleTimer=setInterval(()=>{void sample();},250);sampleTimer.unref();
  const token=async(subject:string,scope:string)=>new SignJWT({iss:process.env.AUTH0_ISSUER,aud:process.env.AUTH0_AUDIENCE,sub:subject,scope}).setProtectedHeader({alg:"RS256",kid:"r4-local",typ:"JWT"}).setIssuedAt().setExpirationTime("10m").sign(privateKey);
  const principalCount=scenario==="stage2-read"?50:scenario==="baseline-read"?10:scenario==="baseline-write"?71:scenario==="fault-gates"?4:2;const principals:Array<{index:number;actorSubject:string;account:string;read:string;write:string;otherRead:string;recipient:string;intentId?:string;requestHash?:string;expectedVersion?:string}>=[];for(let index=0;index<principalCount;index++){const subject=`r4|${seed}|${index}`,account=await token(subject,"read:account"),read=await token(subject,"read:payments"),write=await token(subject,"write:payments");const response=await fetch(`${base}/api/account/me`,{headers:{Authorization:`Bearer ${account}`}});if(response.status!==200)throw new Error(`Principal seed failed with ${response.status}.`);const body=await response.json() as {account:{actorSubject:string}};await databasePool.query("INSERT INTO beta_allowlist(actor_subject) VALUES($1) ON CONFLICT(actor_subject) DO NOTHING",[body.account.actorSubject]);principals.push({index,actorSubject:body.account.actorSubject,account,read,write,otherRead:"",recipient:"2w2nqMemQzjwKMk3jEmtXnBqGBXGJLs8FNfb5Khb8E7J"});}principals[0].otherRead=principals[1].read;principals[1].otherRead=principals[0].read;
  const owner=principals[0],jsonHeaders={Authorization:`Bearer ${owner.write}`,"Content-Type":"application/json","Idempotency-Key":"r4-seeded-intent-0001"};const created=await fetch(`${base}/api/payment-intents`,{method:"POST",headers:jsonHeaders,body:JSON.stringify({recipient:owner.recipient,amount:"1",purpose:"R4 baseline"})});if(created.status!==201)throw new Error(`Payment seed create failed with ${created.status}.`);const intent=(await created.json() as any).paymentIntent;const confirmation=await fetch(`${base}/api/payment-intents/${intent.id}/confirm`,{method:"POST",headers:{Authorization:`Bearer ${owner.write}`,"Content-Type":"application/json"},body:JSON.stringify({requestHash:intent.requestHash,expectedVersion:"0"})});if(confirmation.status!==200)throw new Error(`Payment seed confirmation failed with ${confirmation.status}.`);const executionBody=JSON.stringify({requestHash:intent.requestHash,expectedVersion:"1"});const executed=await fetch(`${base}/api/payment-intents/${intent.id}/execute`,{method:"POST",headers:{Authorization:`Bearer ${owner.write}`,"Content-Type":"application/json"},body:executionBody});if(executed.status!==202)throw new Error(`Payment seed execution failed with ${executed.status}.`);let receiptStatus=404;for(let attempt=0;attempt<50&&receiptStatus!==200;attempt++){await new Promise(resolve=>setTimeout(resolve,100));receiptStatus=(await fetch(`${base}/api/payment-intents/${intent.id}/receipt`,{headers:{Authorization:`Bearer ${owner.read}`}})).status;}if(receiptStatus!==200)throw new Error("Payment seed did not settle.");const replay=await fetch(`${base}/api/payment-intents/${intent.id}/execute`,{method:"POST",headers:{Authorization:`Bearer ${owner.write}`,"Content-Type":"application/json"},body:executionBody});if(replay.status!==200)throw new Error(`Payment replay failed with ${replay.status}.`);const denied=await fetch(`${base}/api/payment-intents/${intent.id}/receipt`,{headers:{Authorization:`Bearer ${principals[1].read}`}});if(denied.status!==404)throw new Error(`Cross-account receipt read returned ${denied.status}.`);Object.assign(owner,{intentId:intent.id,requestHash:intent.requestHash,expectedVersion:"1"});
  const ready=await fetch(`${base}/health/ready`);const account=await fetch(`${base}/api/account/me`,{headers:{Authorization:`Bearer ${principals[0].account}`}});const activity=await fetch(`${base}/api/activity?limit=20`,{headers:{Authorization:`Bearer ${principals[0].read}`}});if([ready.status,account.status,activity.status].some(status=>status!==200))throw new Error("Stage 0 HTTP baseline failed.");
  let faultResults:Record<string,unknown>|undefined;let faultIntentId:string|undefined;let k6Summary:Record<string,unknown>={stage0:{ready:ready.status,account:account.status,activity:activity.status}};let k6Version="not-run";
  if(scenario==="fault-gates"){
    const container=process.env.R4_DB_CONTAINER?.trim();if(!container)throw new Error("R4_DB_CONTAINER is required for fault gates.");
    if(sampleTimer)clearInterval(sampleTimer);sampleTimer=undefined;const liveDuringPause=fetch(`${base}/health/live`);await controlDisposableDatabase(container,"pause");const readyDuringPause=await Promise.all(Array.from({length:20},()=>fetch(`${base}/health/ready`)));const liveStatus=(await liveDuringPause).status;await controlDisposableDatabase(container,"unpause");let recoveredReady=503;for(let attempt=0;attempt<30&&recoveredReady!==200;attempt++){await new Promise(resolve=>setTimeout(resolve,100));recoveredReady=(await fetch(`${base}/health/ready`)).status;}sampleTimer=setInterval(()=>{void sample();},250);sampleTimer.unref();
    const held=await saturatePool(backend.postgresPool!);const saturatedReady=await fetch(`${base}/health/ready`);const normalStarted=performance.now();const saturatedRequest=await fetch(`${base}/api/activity?limit=20`,{headers:{Authorization:`Bearer ${principals[0].read}`}}).then(response=>({status:response.status,error:""}),error=>({status:0,error:error instanceof Error?error.message:"fetch failed"}));const saturatedDurationMs=performance.now()-normalStarted;const waitingDuringSaturation=backend.postgresPool!.waitingCount;held.release();let readyAfterSaturationStatus=503;for(let attempt=0;attempt<70&&readyAfterSaturationStatus!==200;attempt++){await new Promise(resolve=>setTimeout(resolve,100));readyAfterSaturationStatus=(await fetch(`${base}/health/ready`)).status;}const waitingAfterRecovery=backend.postgresPool!.waitingCount;
    let timeoutCode="";try{await triggerStatementTimeout(backend.postgresPool!,25);}catch(error){timeoutCode=String((error as {code?:string}).code??"");}const healthyAfterTimeout=await backend.postgresPool!.query("SELECT 1 AS ok");
    const delays:Array<{delayMs:number;outcome:string}>=[];let workerCalls=0;const failureLoop=new AdaptiveWorkerLoop(async()=>{workerCalls++;if(workerCalls===1)throw new Error("R4 deterministic iteration failure");return workerCalls===2;},(delayMs,outcome)=>delays.push({delayMs,outcome}));failureLoop.start();await new Promise(resolve=>setTimeout(resolve,500));await failureLoop.stopAndDrain();
    const activePrincipal=principals[2],activeHeaders={Authorization:`Bearer ${activePrincipal.write}`,"Content-Type":"application/json","Idempotency-Key":"r4-sigterm-active-0001"};const activeCreated=await fetch(`${base}/api/payment-intents`,{method:"POST",headers:activeHeaders,body:JSON.stringify({recipient:activePrincipal.recipient,amount:"1",purpose:"R4 SIGTERM"})});const activeIntent=(await activeCreated.json() as any).paymentIntent;const activeConfirmed=await fetch(`${base}/api/payment-intents/${activeIntent.id}/confirm`,{method:"POST",headers:{Authorization:`Bearer ${activePrincipal.write}`,"Content-Type":"application/json"},body:JSON.stringify({requestHash:activeIntent.requestHash,expectedVersion:"0"})});const activeExecuted=await fetch(`${base}/api/payment-intents/${activeIntent.id}/execute`,{method:"POST",headers:{Authorization:`Bearer ${activePrincipal.write}`,"Content-Type":"application/json"},body:JSON.stringify({requestHash:activeIntent.requestHash,expectedVersion:"1"})});faultIntentId=activeIntent.id;const lockClient=await databasePool.connect();await lockClient.query("BEGIN");await lockClient.query("SELECT execution_id FROM payment_executions WHERE payment_intent_id=$1 FOR UPDATE",[activeIntent.id]);await new Promise(resolve=>setTimeout(resolve,150));const activeReads=Promise.all(Array.from({length:20},()=>fetch(`${base}/api/activity?limit=20`,{headers:{Authorization:`Bearer ${activePrincipal.read}`}}).catch(()=>undefined)));process.kill(process.pid,"SIGTERM");await new Promise<void>(resolve=>setImmediate(resolve));const shutdown=backend.shutdownCoordinator.shutdown("SIGTERM");const shutdownReady=await backend.readinessService.check();await new Promise(resolve=>setTimeout(resolve,250));await lockClient.query("ROLLBACK");lockClient.release();await Promise.all([shutdown,activeReads]);const snapshotBeforeWait=(require(path.join(root,"dist/observability/reliabilityObservability.js")) as typeof import("../../src/observability/reliabilityObservability")).reliabilityMetricsSnapshot();await new Promise(resolve=>setTimeout(resolve,300));const snapshotAfterWait=(require(path.join(root,"dist/observability/reliabilityObservability.js")) as typeof import("../../src/observability/reliabilityObservability")).reliabilityMetricsSnapshot();const recoveryWorker=new PaymentExecutionWorker(new PostgresPaymentPersistence(databasePool),new PostgresExecutionRepository(databasePool),"r4-restart-recovery");for(let attempt=0;attempt<10;attempt++){await recoveryWorker.processNext();await recoveryWorker.reconcileNext();const recovered=await databasePool.query("SELECT status FROM payment_executions WHERE payment_intent_id=$1",[activeIntent.id]);if(recovered.rows[0]?.status==="SETTLED")break;}
    faultResults={postgresUnavailable:{liveStatus,readyStatuses:[...new Set(readyDuringPause.map(response=>response.status))],probeCount:20,recoveredReady},poolSaturation:{readyStatus:saturatedReady.status,requestStatus:saturatedRequest.status,requestDurationMs:saturatedDurationMs,waitingDuringSaturation,waitingAfterRecovery,recoveredReady:readyAfterSaturationStatus},statementTimeout:{code:timeoutCode,continuedHealth:Number(healthyAfterTimeout.rows[0]?.ok)===1},workerFailure:{calls:workerCalls,delays},sigterm:{createStatus:activeCreated.status,confirmStatus:activeConfirmed.status,executeStatus:activeExecuted.status,readiness:shutdownReady,workerTicksBefore:(snapshotBeforeWait.counters as any)["worker.tick"],workerTicksAfter:(snapshotAfterWait.counters as any)["worker.tick"]}};
    const faultPassed=liveStatus===200&&readyDuringPause.every(response=>response.status===503)&&recoveredReady===200&&saturatedReady.status===503&&[0,500].includes(saturatedRequest.status)&&saturatedDurationMs<7_000&&waitingDuringSaturation<=1&&waitingAfterRecovery===0&&readyAfterSaturationStatus===200&&timeoutCode==="57014"&&Number(healthyAfterTimeout.rows[0]?.ok)===1&&delays.some(value=>value.outcome==="failure"&&value.delayMs===250)&&shutdownReady.ready===false&&(faultResults.sigterm as any).workerTicksBefore===(faultResults.sigterm as any).workerTicksAfter;if(!faultPassed)throw new Error(`Fault gate failed: ${JSON.stringify(faultResults)}`);
  } else if(scenario!=="stage0"){
    const isRead=scenario!=="baseline-write",workloadPrincipals=scenario==="baseline-write"?principals.slice(1):principals;const principalFile=path.join(temporary,"principals.json");await writeFile(principalFile,JSON.stringify(workloadPrincipals),{mode:0o600});
    const k6Binary=process.env.R4_K6_BIN?.trim()||"k6";k6Version=execFileSync(k6Binary,["version"],{encoding:"utf8"}).trim();const summaryFile=path.join(artifactDir,"k6-summary.json");const vus=scenario==="stage2-read"?50:scenario==="smoke"?2:10,duration=scenario==="smoke"?"3s":"60s",rate=scenario==="baseline-write"?1:2,executor=scenario==="baseline-read"||scenario==="stage2-read"?"constant-vus":"constant-arrival-rate";
    await exec(k6Binary,["run","--summary-export",summaryFile,"-e",`BASE_URL=${base}`,"-e",`PRINCIPALS_FILE=${principalFile}`,"-e",`VUS=${vus}`,"-e",`RPS=${rate}`,"-e",`DURATION=${duration}`,"-e",`EXECUTOR=${executor}`,"-e",`PACE_SECONDS=${scenario==="baseline-read"||scenario==="stage2-read"?2.5:0}`,"-e",`SAMPLE_READY=${scenario==="stage2-read"?"false":"true"}`,path.join(root,"load/k6",isRead?"read-baseline.js":"payment-lifecycle.js")]);k6Summary=JSON.parse(await readFile(summaryFile,"utf8"));
  }
  const measuredIterations=Number(((k6Summary.metrics??{}) as Record<string,{count?:number}>).iterations?.count??0);const invariants=await verifyEconomicInvariants(databasePool,{crossAccountReadsDenied:denied.status===404,expectedPaymentCount:scenario==="baseline-write"?1+measuredIterations:scenario==="fault-gates"?2:1,expectedPayments:[{actorSubject:owner.actorSubject,idempotencyKey:"r4-seeded-intent-0001"}],expectedSettledIntentIds:[intent.id,...(faultIntentId?[faultIntentId]:[])]});if(!invariants.passed)throw new Error(`Economic invariants failed: ${JSON.stringify(invariants.violations)}`);
  const commit=(await exec("git",["rev-parse","HEAD"],{cwd:root})).stdout.trim();const postgresVersion=String((await databasePool.query("SHOW server_version")).rows[0]?.server_version);
  const manifest:RunManifest={commit,nodeVersion:process.version,k6Version,postgresVersion,scenario,seed,vus:scenario==="stage2-read"?50:scenario==="stage0"||scenario==="fault-gates"?1:scenario==="smoke"?2:10,arrivalRate:scenario==="baseline-write"?1:scenario==="smoke"?2:0,duration:scenario==="stage0"||scenario==="fault-gates"?"functional":scenario==="smoke"?"3s":"60s",pool:{...PAYMENT_POSTGRES_POOL_CONFIG}};
  if(sampleTimer)clearInterval(sampleTimer);sampleTimer=undefined;await sample();const compiledObservability=require(path.join(root,"dist/observability/reliabilityObservability.js")) as typeof import("../../src/observability/reliabilityObservability");await writeFile(path.join(artifactDir,"manifest.json"),JSON.stringify(manifest,null,2));await writeFile(path.join(artifactDir,"invariants.json"),JSON.stringify(invariants,null,2));if(faultResults)await writeFile(path.join(artifactDir,"fault-results.json"),JSON.stringify(faultResults,null,2));await writeFile(path.join(artifactDir,"reliability.json"),JSON.stringify(compiledObservability.reliabilityMetricsSnapshot(),null,2));await writeFile(path.join(artifactDir,"resource-samples.json"),JSON.stringify(resourceSamples,null,2));await writeFile(path.join(artifactDir,"postgres-samples.json"),JSON.stringify(postgresSamples,null,2));await writeFile(path.join(artifactDir,"backend.stdout.log"),backendStdout.join("\n")+"\n");await writeFile(path.join(artifactDir,"backend.stderr.log"),backendStderr.join("\n")+"\n");await writeFile(path.join(artifactDir,"report.md"),certificationReport(manifest,k6Summary,invariants));console.log(`R4 ${scenario} PASS`,{artifactDir});
}catch(error){originalError("R4 harness body failed",error);throw error;}finally{
  if(sampleTimer)clearInterval(sampleTimer);if(backend)await backend.shutdownCoordinator.shutdown("R4_HARNESS");await writeFile(path.join(artifactDir,"backend.stdout.log"),backendStdout.join("\n")+"\n").catch(()=>undefined);await writeFile(path.join(artifactDir,"backend.stderr.log"),backendStderr.join("\n")+"\n").catch(()=>undefined);await databasePool?.end();await admin.query(`SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname=$1`,[database]);await admin.query(`DROP DATABASE IF EXISTS "${database}"`);await admin.end();await rm(temporary,{recursive:true,force:true});console.log=originalLog;console.info=originalInfo;console.warn=originalWarn;console.error=originalError;
}
}

void main().catch(error=>{console.error("R4 harness failed",error instanceof Error?error.message:"unknown error");process.exitCode=1;});

async function availablePort():Promise<number>{const server=createServer();await new Promise<void>((resolve,reject)=>server.once("error",reject).listen(0,"127.0.0.1",resolve));const address=server.address();if(!address||typeof address==="string")throw new Error("Could not reserve a loopback port.");await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));return address.port;}
function logLine(values:unknown[]):string{return values.map(value=>typeof value==="string"?value:JSON.stringify(value)).join(" ");}
