// Explicit reviewed allowlist, independent of live role grants. Update deliberately with the SQL provisioning contract.
export const authorityPrivilegePolicy = {
  identity: {
    tables: {
      accounts: {SELECT:["*"], INSERT:["*"], UPDATE:["status","version","updated_at"]},
      external_identities: {SELECT:["*"], INSERT:["*"]},
      account_sessions: {SELECT:["*"], INSERT:["*"], UPDATE:["revoked_at"]},
      account_security_events: {SELECT:["*"], INSERT:["*"]},
      economic_session_bindings: {SELECT:["*"], INSERT:["issuer","provider_subject","provider_session_reference","account_session_id"]},
      economic_authority_events: {INSERT:["event_type","actor","intent_id","generation","finalization_id","consent_id","runtime_id","reference"]},
    },
    functions: [],
    sequences: {account_security_events_event_id_seq:{USAGE:["*"]}, economic_authority_events_event_id_seq:{USAGE:["*"]}},
  },
  app: {
    tables: {
      "economic_authority_incidents": {"SELECT":["*"]},
      "economic_observer_report_summary": {"SELECT":["*"]},
      "economic_authority_trace": {"SELECT":["*"]},
      "accounts": {"SELECT":["*"],"UPDATE":["account_id"]},
      "account_sessions": {"SELECT":["*"],"UPDATE":["session_id"]},
      "external_identities": {"SELECT":["*"]},
      "economic_network_registry": {"SELECT":["*"],"UPDATE":["registry_id"]},
      "economic_asset_registry": {"SELECT":["*"],"UPDATE":["registry_id"]},
      "economic_attempt_heads": {"SELECT":["*"],"INSERT":["intent_id","principal_id","current_generation"],"UPDATE":["current_generation"]},
      "economic_attempts": {"SELECT":["*"],"INSERT":["intent_id","generation","attempt_id","fence_token","envelope_digest","envelope","message_digest","recent_blockhash","requested_exposure_id"],"UPDATE":["state","finalization_id"]},
      "economic_consent_evidence": {"SELECT":["*"],"UPDATE":["consent_id"]},
      "economic_runtime_evidence": {"SELECT":["*"],"UPDATE":["decision_id"]},
      "economic_sponsor_budgets": {"SELECT":["*"],"UPDATE":["budget_id"]},
      "economic_finalizations": {"SELECT":["*"],"UPDATE":["finalization_id"],"INSERT":["finalization_id","intent_id","generation","tuple","tuple_digest","consent_id","runtime_id","payment_registry_id","fee_registry_id","budget_id","budget_version","exposure_id","base_requested","priority_requested","rent_requested","signer_operation_id","customer_artifact"]},
      "economic_authority_events": {"SELECT":["*"],"INSERT":["event_type","actor","intent_id","generation","finalization_id","consent_id","runtime_id","reference"]},
      "economic_callback_evidence": {"SELECT":["*"],"INSERT":["evidence_id","intent_id","generation","artifact_digest","artifact","validation"]},
      "economic_session_bindings": {"SELECT":["*"]},
      "economic_budget_heads": {"SELECT":["*"],"UPDATE":["family_id"]},
      "economic_budget_versions": {"SELECT":["*"]},
      "economic_signer_contact_authority": {"SELECT":["*"]},
      "economic_expiry_records": {"SELECT":["*"]},
      "economic_effect_evidence": {"SELECT":["*"]},
      "economic_exposure_projection": {"SELECT":["*"]},
    },
    functions: ["economic_record_incident(uuid,text,text)", "economic_commit_signer_contact(uuid)", "economic_expire_never_contacted(uuid,text)", "economic_record_signer_unknown(uuid)", "economic_apply_finalized_accounting(uuid,uuid)"],
    sequences: {"economic_authority_events_event_id_seq": {"USAGE": ["*"]}},
  },
  issuer: {
    tables: {
      economic_confirmation_policies: {SELECT:["*"]},
      economic_confirmation_policy_heads: {SELECT:["*"], UPDATE:["deployment_id"]},
      economic_confirmation_summary: {SELECT:["*"]},
      economic_confirmation_challenges: {SELECT:["*"], INSERT:["challenge_id","request_id","account_id","principal_id","account_session_id","account_version","envelope_digest","intent_id","generation","action","environment","issuer","provider_subject","configuration","configuration_revision","policy_fingerprint","policy_revision","provider_revision","authentication_digest","transaction_id","nonce","requested_at","expires_at","reauthentication"]},
      economic_confirmation_consumptions: {SELECT:["*"], INSERT:["challenge_id","consent_id","authentication_digest","reauthentication_digest","confirmation_request_digest","authentication_time","assurance","confirmed_at","expires_at"]},
      economic_attempt_heads: {SELECT:["*"], UPDATE:["intent_id"]},
      "accounts": {"SELECT":["*"],"UPDATE":["account_id"]},
      "account_sessions": {"SELECT":["*"],"UPDATE":["session_id"]},
      "external_identities": {"SELECT":["*"]},
      "economic_network_registry": {"UPDATE":["registry_id"],"SELECT":["*"]},
      "economic_asset_registry": {"UPDATE":["registry_id"],"SELECT":["*"]},
      "economic_attempts": {"SELECT":["*"]},
      "economic_consent_evidence": {"SELECT":["*"],"INSERT":["consent_id","envelope_digest","principal_id","issuer","audience","context","provider_subject","authentication_reference","session_reference","authenticated_at","confirmed_at","expires_at","account_session_id"],"UPDATE":["revoked_at"]},
      "economic_runtime_evidence": {"SELECT":["*"],"INSERT":["decision_id","envelope_digest","issuer","policy_version","evidence_digest","binding","network","scope","valid_from","valid_until"],"UPDATE":["revoked_at"]},
      "economic_session_bindings": {"SELECT":["*"],"INSERT":["issuer","provider_subject","provider_session_reference","account_session_id"]},
      "economic_authority_events": {"INSERT":["event_type","actor","intent_id","generation","finalization_id","consent_id","runtime_id","reference"]},
    },
    functions: [],
    sequences: {"economic_authority_events_event_id_seq": {"USAGE": ["*"]}},
  },
  signer: {
    tables: {
      "economic_signer_reports": {"SELECT":["*"]},
      "economic_authority_incidents": {"SELECT":["*"]},
      "economic_network_registry": {"SELECT":["*"]},
      "economic_asset_registry": {"SELECT":["*"]},
      "economic_attempt_heads": {"SELECT":["*"],"UPDATE":["intent_id"]},
      "economic_attempts": {"SELECT":["*"]},
      "economic_consent_evidence": {"SELECT":["*"]},
      "economic_runtime_evidence": {"SELECT":["*"]},
      "economic_sponsor_budgets": {"SELECT":["*"],"UPDATE":["budget_id"]},
      "economic_finalizations": {"SELECT":["*"],"UPDATE":["signer_state","exposure_state","result_artifact","artifact_reference","final_transaction_id","refusal_reference","updated_at","version"]},
      "economic_authority_events": {"SELECT":["*"],"INSERT":["event_type","actor","intent_id","generation","finalization_id","consent_id","runtime_id","reference"]},
      "economic_callback_evidence": {"SELECT":["*"]},
      "economic_session_bindings": {"SELECT":["*"]},
      "economic_budget_heads": {"SELECT":["*"],"UPDATE":["family_id"]},
      "economic_budget_versions": {"SELECT":["*"]},
      "economic_signer_contact_authority": {"SELECT":["*"]},
      "economic_expiry_records": {"SELECT":["*"]},
      "economic_effect_evidence": {"SELECT":["*"]},
      "economic_exposure_projection": {"SELECT":["*"]},
    },
    functions: ["economic_record_signer_conflict(uuid,jsonb,bytea)","economic_record_incident(uuid,text,text)"],
    sequences: {"economic_authority_events_event_id_seq": {"USAGE": ["*"]}},
  },
  observer: {
    tables: {
      "economic_authority_incidents": {"SELECT":["*"]},
      "economic_observer_reports": {"SELECT":["*"]},
      "economic_observer_operations": {"SELECT":["*"]},
      "economic_effect_evidence": {"SELECT":["*"],"INSERT":["evidence_id","finalization_id","kind","network","transaction_id","reference","base_consumed","priority_consumed","rent_consumed"]},
    },
    functions: ["economic_record_incident(uuid,text,text)", "economic_ingest_observation(uuid,text,jsonb)"],
    sequences: {},
  },
  reader: {
    tables: {
      economic_confirmation_summary: {SELECT:["*"]},
      "economic_signer_report_summary": {"SELECT":["*"]},
      "economic_authority_incidents": {"SELECT":["*"]},
      "economic_observer_report_summary": {"SELECT":["*"]},
      "economic_authority_trace": {"SELECT":["*"]},
      "economic_observer_operations": {"SELECT":["*"]},
      "economic_exposure_projection": {"SELECT":["*"]},
      "economic_expiry_records": {"SELECT":["*"]},
      "economic_authority_events": {"SELECT":["*"]},
      "economic_network_registry": {"SELECT":["*"]},
      "economic_asset_registry": {"SELECT":["*"]},
      "economic_sponsor_budgets": {"SELECT":["*"]},
      "economic_budget_heads": {"SELECT":["*"]},
      "economic_budget_versions": {"SELECT":["*"]},
    },
    functions: [],
    sequences: {},
  },
} as const;
export type EconomicAuthorityRole = keyof typeof authorityPrivilegePolicy;
