import type{Pool}from"pg";import{canonicalPaymentFlow,type ActorFlow}from"./e2eTypes";
export type DevnetInvariantFacts=Readonly<{actorFlow:ActorFlow;canonicalPaymentFlow:string;paymentStatus:string;paymentVersion:string;executionStatus:string;preparationState:string;receiptCount:number;commitmentCount:number;submissionCount:number;settlementEventCount:number;reconciliationCount:number;commitmentBeforeSubmission:boolean;reconciliationUsesPersistedSignature:boolean;mockExecutionCount:number;preparationCount:number;submissionAuthorityAvailable:boolean}>;
export async function auditDevnetInvariants(pool:Pool,paymentId:string,executionId:string,baseline?:Readonly<{paymentVersion:string;settlementEventCount:number}>,actorFlow:ActorFlow="H2H"):Promise<Readonly<{facts:DevnetInvariantFacts;violations:string[]}>>{
 const r=await pool.query(`SELECT p.status payment_status,p.version::text payment_version,e.status execution_status,prep.lifecycle_state preparation_state,
 (SELECT count(*)::int FROM payment_execution_receipts WHERE execution_id=e.execution_id) receipt_count,
 (SELECT count(*)::int FROM devnet_submission_commitments WHERE execution_id=e.execution_id) commitment_count,
 (SELECT count(*)::int FROM devnet_submission_observations WHERE execution_id=e.execution_id) submission_count,
 (SELECT count(*)::int FROM payment_events WHERE payment_id=p.id AND event_type='SETTLEMENT_CONFIRMED') settlement_event_count,
 (SELECT count(*)::int FROM devnet_reconciliation_observations WHERE execution_id=e.execution_id) reconciliation_count,
 NOT EXISTS(SELECT 1 FROM devnet_submission_observations so JOIN devnet_submission_commitments c USING(execution_id) WHERE so.execution_id=e.execution_id AND so.observed_at<c.committed_at) commitment_before_submission,
 NOT EXISTS(SELECT 1 FROM devnet_reconciliation_observations ro JOIN devnet_submission_commitments c USING(execution_id) WHERE ro.execution_id=e.execution_id AND c.transaction_signature<>prep.transaction_signature) reconciliation_uses_signature,
 (SELECT count(*)::int FROM payment_executions WHERE payment_intent_id=p.id AND execution_mode='mock_beta') mock_execution_count,
 (SELECT count(*)::int FROM devnet_execution_preparations WHERE execution_id=e.execution_id AND lifecycle_state<>'ABANDONED_PRE_CONTACT') preparation_count
 FROM payments p JOIN payment_executions e ON e.payment_intent_id=p.id LEFT JOIN devnet_execution_preparations prep ON prep.execution_id=e.execution_id WHERE p.id=$1 AND e.execution_id=$2`,[paymentId,executionId]);
 if(!r.rows[0])throw new Error("E2E payment execution was not found.");const x=r.rows[0],facts:DevnetInvariantFacts=Object.freeze({actorFlow,canonicalPaymentFlow:canonicalPaymentFlow(actorFlow),paymentStatus:x.payment_status,paymentVersion:x.payment_version,executionStatus:x.execution_status,preparationState:x.preparation_state,receiptCount:x.receipt_count,commitmentCount:x.commitment_count,submissionCount:x.submission_count,settlementEventCount:x.settlement_event_count,reconciliationCount:x.reconciliation_count,commitmentBeforeSubmission:x.commitment_before_submission,reconciliationUsesPersistedSignature:x.reconciliation_uses_signature,mockExecutionCount:x.mock_execution_count,preparationCount:x.preparation_count,submissionAuthorityAvailable:x.commitment_count===0});const v:string[]=[];
 if(facts.commitmentCount!==1)v.push("commitment count must equal one");if(facts.submissionCount>1)v.push("submission observations exceed one");if(facts.receiptCount>1)v.push("execution receipts exceed one");if(facts.settlementEventCount>1)v.push("settlement events exceed one");if(!facts.commitmentBeforeSubmission)v.push("commitment does not precede submission");if(!facts.reconciliationUsesPersistedSignature)v.push("reconciliation signature differs from commitment");if(facts.mockExecutionCount!==0)v.push("Mock execution exists for Devnet scenario");if(facts.preparationCount!==1)v.push("preparation was regenerated after commitment");if(facts.submissionAuthorityAvailable)v.push("submission authority remains available after commitment");if(facts.paymentStatus==="COMPLETED"&&!(facts.executionStatus==="SETTLED"&&facts.preparationState==="SETTLED"&&facts.receiptCount===1))v.push("payment completed without authoritative settlement");if(facts.receiptCount&&facts.executionStatus!=="SETTLED")v.push("receipt exists before authoritative settlement");if(baseline&&facts.paymentStatus==="COMPLETED"&&(facts.paymentVersion!==baseline.paymentVersion||facts.settlementEventCount!==baseline.settlementEventCount))v.push("duplicate completion caused version or event churn");return Object.freeze({facts,violations:v});
}
