import{PublicKey}from"@solana/web3.js";import type{DevnetLiveConfiguration}from"../devnet/devnetLiveConfiguration";import{CIRCLE_SOLANA_DEVNET_USDC_DECIMALS,CIRCLE_SOLANA_DEVNET_USDC_MINT}from"../devnet/canonicalDevnetAsset";import{canonicalPaymentFlow,type ActorFlow,type E2eMode,type E2eScenario,type SyntheticTestActor}from"./e2eTypes";
export const LIVE_CANARY_CONFIRMATION="I_UNDERSTAND_THIS_SUBMITS_DEVNET_USDC";
export const LIVE_CANARY_TIMING=Object.freeze({preparationTimeoutMs:30_000,reconciliationPollMs:2_000,settlementTimeoutMs:120_000,overallTimeoutMs:180_000});
export const LIVE_FAILURE_STAGES=["PRECONDITION_FAILED","IDENTITY_FAILED","PAYMENT_INTENT_FAILED","CONFIRMATION_FAILED","PREPARATION_FAILED","COMMITMENT_FAILED","SUBMISSION_REJECTED","SUBMISSION_AMBIGUOUS","RECONCILIATION_FAILED","SETTLEMENT_TIMEOUT","RECEIPT_FAILED","COMPLETION_FAILED","INVARIANT_FAILED"]as const;export type LiveFailureStage=typeof LIVE_FAILURE_STAGES[number];
export type LiveCanaryInput=Readonly<{mode:E2eMode;scenario:E2eScenario;explicitLiveFlag:boolean;liveConfirmation:string|undefined;network:string;amountRaw:bigint;mint:string;decimals:number;actorFlow:ActorFlow;source:SyntheticTestActor;destination:SyntheticTestActor;config:DevnetLiveConfiguration;existingCommitmentCount:number}>;
export function assertLiveDevnetCanary(input:LiveCanaryInput):void{
 if(input.mode!=="LIVE_DEVNET_CANARY"||!input.explicitLiveFlag)fail("Live Devnet requires explicit --live-devnet invocation.");if(input.liveConfirmation!==LIVE_CANARY_CONFIRMATION)fail("Live Devnet confirmation is missing.");
 if(input.scenario!=="human-to-human-happy-path")fail("Only the H2H happy path supports a live canary.");if(input.network!=="solana-devnet")fail("Only solana-devnet is permitted; Mainnet is rejected.");if(input.amountRaw<=0n||input.amountRaw>1000n)fail("Live canary amount must be 1..1000 raw USDC units.");
 if(input.mint!==CIRCLE_SOLANA_DEVNET_USDC_MINT||input.config.mint!==CIRCLE_SOLANA_DEVNET_USDC_MINT)fail("Canonical Circle Devnet USDC mint is required.");if(input.decimals!==CIRCLE_SOLANA_DEVNET_USDC_DECIMALS||input.config.decimals!==6)fail("Devnet USDC decimals must equal six.");
 for(const actor of[input.source,input.destination])if(actor.actorClass!=="synthetic_test"||actor.testOrigin!=="codex_e2e")fail("Live canary actors must be codex_e2e synthetic_test actors.");if(input.source.actorKind!=="human"||input.destination.actorKind!=="human"||input.actorFlow!=="H2H"||canonicalPaymentFlow(input.actorFlow)!=="P2P")fail("Live canary flow must be human H2H/P2P.");
 if(!input.destination.devnetDestinationAddress||input.destination.destinationRelationship!=="configured_test_destination_not_ownership")fail("Synthetic destination requires explicit non-ownership Devnet test metadata.");try{if(new PublicKey(input.destination.devnetDestinationAddress).toBase58()!==input.destination.devnetDestinationAddress)throw new Error();}catch{fail("Synthetic destination Devnet address is invalid.");}
 const c=input.config;if(!c.enabled||!c.preparationEnabled||!c.submissionEnabled||!c.reconciliationEnabled)fail("Live integration, preparation, submission, and reconciliation must be enabled.");if(!c.encryptionKey||!c.encryptionKeyVersion)fail("Preparation encryption configuration is missing.");if(!c.signerSecretKey||!c.signerKeyId||!c.signerKeyVersion||!c.signerPublicKey)fail("Server signer configuration is missing.");if(!c.submissionProviderId||!c.submissionUrl||!c.submissionApiKey)fail("Submission provider configuration is missing.");if(!c.reconciliationProviderId||!c.reconciliationUrl)fail("Reconciliation provider configuration is missing.");if(input.existingCommitmentCount!==0)fail("A committed execution is observe/reconcile-only and cannot enter live submission.");
}
function fail(message:string):never{throw Object.assign(new Error(message),{failureStage:"PRECONDITION_FAILED"as const});}
export function withTimeout<T>(operation:Promise<T>,milliseconds:number,label:string):Promise<T>{let timer:NodeJS.Timeout;return Promise.race([operation,new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(Object.assign(new Error(`${label} timed out.`),{failureStage:label==="settlement"?"SETTLEMENT_TIMEOUT":"PREPARATION_FAILED"})),milliseconds);})]).finally(()=>clearTimeout(timer!));}
