import{randomUUID}from"node:crypto";import{base58}from"@scure/base";import{Keypair,Transaction}from"@solana/web3.js";import type{Pool}from"pg";import type{DevnetTransactionSigner,SolanaChainObservation,SolanaSubmissionRpc}from"zephyon-protocol";
import type{ExternalPrincipal}from"../auth/externalPrincipal";import{AccountProvisioningService}from"../identity/accountProvisioningService";import{PaymentIntentService}from"../services/paymentIntentService";import{PostgresIdentityPersistence}from"../storage/postgres/postgresIdentityPersistence";import{PostgresPaymentPersistence}from"../storage/postgres/postgresPaymentPersistence";import{PostgresE2eReliabilityRepository}from"../storage/postgres/postgresE2eReliabilityRepository";import{PostgresBrowserDevnetExecutionStore}from"../storage/postgres/postgresBrowserDevnetExecutionStore";import{PostgresDevnetExecutionStateRepository}from"../storage/postgres/postgresDevnetExecutionStateRepository";import{BrowserDevnetExecutionService}from"../devnet/browserDevnetExecution";import{DevnetOrchestrationService,type DevnetReconciliationProvider}from"../devnet/devnetOrchestrationService";import{DevnetReconciliationService}from"../devnet/devnetReconciliationService";import{Aes256GcmPreparedTransactionCipher}from"../devnet/preparedTransactionCipher";import{CIRCLE_SOLANA_DEVNET_USDC_MINT}from"../devnet/canonicalDevnetAsset";import{auditDevnetInvariants}from"./devnetInvariantEngine";import{actorFlowForScenario,AGENT_SCENARIO_BLOCKERS,UNSUPPORTED_AGENT_SCENARIOS,type E2eScenario}from"./e2eTypes";
import{PostgresDevnetRecoveryRepository}from"../storage/postgres/postgresDevnetRecoveryRepository";
const NOW="2026-08-15T18:00:00.000Z",ISSUER="https://codex-e2e.invalid/",POLICY_HASH="a".repeat(64),SOURCE_ACCOUNT="10000000-0000-4000-8000-000000000001",DEST_ACCOUNT="10000000-0000-4000-8000-000000000002";const payer=Keypair.fromSeed(Buffer.alloc(32,31)),sourceToken=Keypair.fromSeed(Buffer.alloc(32,32)).publicKey.toBase58(),destinationWallet=Keypair.fromSeed(Buffer.alloc(32,33)).publicKey.toBase58();let deterministicBlockhashSeed=50;
class OfflineSubmission implements SolanaSubmissionRpc{readonly identity={providerId:"codex-offline-submit",network:"devnet"as const,role:"submission"as const};calls=0;constructor(private ambiguity:boolean){}async submitExactSignedTransaction(bytes:Uint8Array){this.calls++;if(this.calls>1)throw new Error("offline invariant: second submission attempted");if(this.ambiguity)throw new Error("deterministic post-contact ambiguity");const transaction=Transaction.from(bytes);return{signature:base58.encode(transaction.signature!),acceptedAt:NOW};}}
class OfflineReconciliation implements DevnetReconciliationProvider{readonly identity={providerId:"codex-offline-reconcile",network:"devnet"as const,role:"reconciliation"as const};signatures:string[]=[];observation:SolanaChainObservation={status:"settled",observedAt:NOW,settledAt:NOW,slot:"484124271",confirmationStatus:"finalized"};async observeSignature(signature:string){this.signatures.push(signature);return{...this.observation,signature,historySearched:true as const,providerId:this.identity.providerId,contextSlot:"484124272"};}}
const signer:DevnetTransactionSigner={keyId:"codex-offline-signer",keyVersion:"1",publicKey:payer.publicKey.toBase58(),async signTransaction(bytes){const tx=Transaction.from(bytes);tx.partialSign(payer);return{signature:base58.encode(tx.signature!),signedTransactionBase64:tx.serialize().toString("base64")};}};
export class OfflineDevnetE2eHarness{
 constructor(private readonly pool:Pool,private readonly clock=()=>NOW){}
 async run(scenario:E2eScenario){const started=Date.now(),runs=new PostgresE2eReliabilityRepository(this.pool),runId=randomUUID();if((UNSUPPORTED_AGENT_SCENARIOS as readonly string[]).includes(scenario)){await runs.startRun({runId,scenarioName:scenario,testOrigin:"codex_e2e",mode:"OFFLINE",sourceActorKind:scenario==="agent-to-human"||scenario==="agent-to-agent"?"agent":"human",destinationActorKind:scenario==="human-to-agent"||scenario==="agent-to-agent"?"agent":"human",actorFlow:actorFlowForScenario(scenario),startedAt:this.clock()});return runs.finishRun(runId,{result:"UNSUPPORTED",completedAt:this.clock(),invariantViolations:[],durationMs:Date.now()-started,failureStage:undefined,failureReason:undefined,...{}});}
  const actors=await this.fixtures(runs),identity=new PostgresIdentityPersistence(this.pool),payments=new PostgresPaymentPersistence(this.pool),accounts=new AccountProvisioningService(identity),principal=this.principal("synthetic-human-a"),paymentService=new PaymentIntentService(accounts,payments,{clock:this.clock});await runs.startRun({runId,scenarioName:scenario,testOrigin:"codex_e2e",mode:"OFFLINE",sourceActorId:actors.source.syntheticActorId,destinationActorId:actors.destination.syntheticActorId,sourceActorKind:"human",destinationActorKind:"human",actorFlow:"H2H",startedAt:this.clock()});let paymentId:string|undefined,executionId:string|undefined;
  try{const created=await paymentService.create(principal,{idempotencyKey:`codex-e2e:${runId}`,amount:"0.001",purpose:`codex_e2e:${scenario}`,recipient:destinationWallet});paymentId=created.paymentIntent.id;const confirmed=await paymentService.confirm(principal,{paymentId,requestHash:created.paymentIntent.requestHash,expectedVersion:BigInt(created.paymentIntent.version),requestId:`confirm:${runId}`});if(scenario==="duplicate-confirm"){const duplicate=await paymentService.confirm(principal,{paymentId,requestHash:created.paymentIntent.requestHash,expectedVersion:BigInt(created.paymentIntent.version)});if(duplicate.applied)throw new Error("duplicate confirmation was applied");}
   const ambiguity=scenario==="recover-after-ambiguous-response",submission=new OfflineSubmission(ambiguity),reconcile=new OfflineReconciliation(),services=this.services(accounts,payments,submission,reconcile),body={requestHash:confirmed.paymentIntent.requestHash,expectedVersion:confirmed.paymentIntent.version,mode:"solana-devnet"};const executed=await services.browser.execute(principal,paymentId,body);executionId=executed.execution.executionId;
   if(["duplicate-execute","recover-after-ambiguous-response"].includes(scenario))await services.browser.execute(principal,paymentId,body);
   if(scenario==="refresh-after-execute")await services.browser.find(principal,paymentId);
   const active=scenario==="restart-after-commit"||scenario==="reconciliation-recovery"?this.services(accounts,payments,submission,reconcile):services;await active.browser.reconcileOwnedWithRecoveryLease(paymentId,actors.source.actorSubject);
   const initial=await auditDevnetInvariants(this.pool,paymentId,executionId);if(["receipt-idempotency","payment-completion-idempotency","duplicate-execute"].includes(scenario)){await active.browser.reconcileOwnedWithRecoveryLease(paymentId,actors.source.actorSubject);const replay=await auditDevnetInvariants(this.pool,paymentId,executionId,{paymentVersion:initial.facts.paymentVersion,settlementEventCount:initial.facts.settlementEventCount});initial.violations.push(...replay.violations);}
   if(submission.calls!==1)initial.violations.push("submission provider call count must equal one");if(ambiguity&&submission.calls!==1)initial.violations.push("ambiguous response caused a second submission");if(reconcile.signatures.some(signature=>signature!==reconcile.signatures[0]))initial.violations.push("reconciliation did not use one persisted signature");if(initial.violations.length)throw Object.assign(new Error(initial.violations.join("; ")),{violations:initial.violations});const complete=await runs.finishRun(runId,{result:"PASSED",completedAt:this.clock(),paymentIntentId:paymentId,executionId,invariantViolations:[],finalPaymentStatus:initial.facts.paymentStatus,finalExecutionStatus:initial.facts.executionStatus,receiptCount:initial.facts.receiptCount,commitmentCount:initial.facts.commitmentCount,submissionCount:initial.facts.submissionCount,durationMs:Date.now()-started});return complete;
  }catch(error){const violations=Array.isArray((error as any)?.violations)?(error as any).violations:[];return runs.finishRun(runId,{result:"FAILED",completedAt:this.clock(),paymentIntentId:paymentId,executionId,failureStage:executionId?"reconciliation":"payment_or_execution",failureReason:error instanceof Error?error.message:"unknown failure",invariantViolations:violations,durationMs:Date.now()-started});}}
 private services(accounts:AccountProvisioningService,payments:PostgresPaymentPersistence,submission:OfflineSubmission,reconcile:OfflineReconciliation){const states=new PostgresDevnetExecutionStateRepository(this.pool),store=new PostgresBrowserDevnetExecutionStore(this.pool),recovery=new PostgresDevnetRecoveryRepository(this.pool,states),cipher=new Aes256GcmPreparedTransactionCipher(Buffer.alloc(32,41),"codex-offline-v1",()=>Buffer.alloc(12,42)),policy={cluster:"solana-devnet"as const,asset:"USDC",mint:CIRCLE_SOLANA_DEVNET_USDC_MINT,decimals:6,sourceTokenAccount:sourceToken,policyHash:POLICY_HASH,submissionProviderId:submission.identity.providerId,reconciliationProviderId:reconcile.identity.providerId},blockhash=Keypair.fromSeed(Buffer.alloc(32,deterministicBlockhashSeed++)).publicKey.toBase58(),orchestration=new DevnetOrchestrationService(states,cipher,policy,{async getLatestDevnetBlockhash(){return{recentBlockhash:blockhash,lastValidBlockHeight:"999999999"};}},signer,{async getCurrentDevnetBlockHeight(){return"1";}},reconcile,submission,{submissionEnabled:true,reconciliationEnabled:true},this.clock,randomUUID),reconciliation=new DevnetReconciliationService(states,reconcile,reconcile.identity.providerId,this.clock,randomUUID),browser=new BrowserDevnetExecutionService(accounts,payments,store,states,orchestration,reconciliation,recovery,`codex-offline-manual-${randomUUID()}`,{exposureEnabled:true,preparationEnabled:true,submissionEnabled:true,reconciliationEnabled:true,policyHash:POLICY_HASH,maxRawAmount:1000n},this.clock,randomUUID);return{browser};}
 private async fixtures(runs:PostgresE2eReliabilityRepository){if(process.env.NODE_ENV!=="test")throw new Error("Offline E2E authentication is available only under NODE_ENV=test.");const identity=new PostgresIdentityPersistence(this.pool),payments=new PostgresPaymentPersistence(this.pool);for(const[id,accountId]of[["synthetic-human-a",SOURCE_ACCOUNT],["synthetic-human-b",DEST_ACCOUNT]]as const){await identity.provisionExternalIdentity({accountId,identityId:accountId.replace(/0001$/,id.endsWith("a")?"0011":"0012"),issuer:ISSUER,subject:id,occurredAt:this.clock()});const account=await identity.findAccount(accountId);if(!account)throw new Error("fixture account provisioning failed");await runs.createActor({syntheticActorId:id,accountId,actorClass:"synthetic_test",actorKind:"human",testOrigin:"codex_e2e",...(id.endsWith("b")?{devnetDestinationAddress:destinationWallet,destinationRelationship:"configured_test_destination_not_ownership"as const}:{}),createdAt:this.clock()});if(!(await payments.findAllowlistEntry(account.actorSubject)))await payments.createAllowlistEntry({actorSubject:account.actorSubject,note:"codex_e2e synthetic fixture"});}const source=await runs.findActor("synthetic-human-a"),destination=await runs.findActor("synthetic-human-b"),sourceAccount=await identity.findAccount(SOURCE_ACCOUNT);if(!source||!destination||!sourceAccount)throw new Error("synthetic fixtures unavailable");return{source:{...source,actorSubject:sourceAccount.actorSubject},destination};}
 private principal(subject:string):ExternalPrincipal{return Object.freeze({issuer:ISSUER,providerSubject:subject,scopes:Object.freeze(["payments:write"])});}
}
export function unsupportedReason(scenario:typeof UNSUPPORTED_AGENT_SCENARIOS[number]){return AGENT_SCENARIO_BLOCKERS[scenario].join(", ");}
